### ISSUE TITLE
iOS build fails when --disable-proxy

### ISSUE THREAD

**Issue by jnavarrom** [curl/curl#6025]
### I did this

Updated from curl 7.51.0 to 7.72.0. Tried building for iOS (or simulator arch x86_64):

```
./configure --host=aarch64-apple-darwin --enable-static --disable-shared --with-secure-transport --with-zlib --disable-manual --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-proxy --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-sspi --enable-ipv6 --disable-smb
make
```

```
vtls/sectransp.c:1157:7: warning: 'CFURLCreateDataAndPropertiesFromResource' is deprecated: first deprecated in iOS 7.0 - For resource data, use the CFReadStream API. For file resource
      properties, use CFURLCopyResourcePropertiesForKeys. [-Wdeprecated-declarations]
      CFURLCreateDataAndPropertiesFromResource(NULL,
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFURLAccess.h:52:9: note: 
      'CFURLCreateDataAndPropertiesFromResource' has been explicitly marked deprecated here
Boolean CFURLCreateDataAndPropertiesFromResource(CFAllocatorRef alloc, CFURLRef url, CFDataRef *resourceData, CFDictionaryRef *properties, CFArrayRef desiredProperties, SInt32 *errorCo...
        ^
vtls/sectransp.c:1402:56: error: no member named 'http_proxy' in 'struct connectdata'
  const char * const hostname = SSL_IS_PROXY() ? conn->http_proxy.host.name :
                                                 ~~~~  ^
vtls/sectransp.c:2382:56: error: no member named 'http_proxy' in 'struct connectdata'
  const char * const hostname = SSL_IS_PROXY() ? conn->http_proxy.host.name :
                                                 ~~~~  ^
```

### I expected the following

Successful build.

### curl/libcurl version

Compilation works on 7.70.0 and fails on 7.72.0 and 7.71.0

### operating system

build host: macOS 10.15.6 with Xcode 12
iOS target: -miphoneos-version-min=10.0

Using curl 7.70.0 compilation works  but using curl 7.71.0 compilation fails. So, I think the issue could be introduced https://github.com/curl/curl/pull/5466 (but not sure)

**Comment by bagder** [comment]
The Secure Transport related code seems to not have gotten the necessary updates in that change...
