### PR TITLE
mbedtls: re-add an error check

### PR DESCRIPTION
**Pull request by vszakats**
While adding support for key blobs, this check moved after some logic
and its update to the error code was no longer checked.

Detected by clang-tidy:
```
Users/runner/work/curl/curl/lib/vtls/mbedtls.c:768:7: error: Value stored to 'ret' is never read [clang-analyzer-deadcode.DeadStores,-warnings-as-errors]
  768 |       ret = MBEDTLS_ERR_PK_TYPE_MISMATCH;
      |       ^
```
https://github.com/curl/curl/actions/runs/13953249156/job/39057979349?pr=16764#step:12:178

Regression from 05e0453050def7323fbc8210886f909819edcc5f #7157
Cherry-picked from #16764

### CODE REVIEW

**Comment by testclutch** [comment]
Analysis of PR #16766 at [f7ca4664](https://github.com/curl/curl/commit/f7ca466470f71c391dcdd78d155efa57c3acc8c1):

[Test 3000 failed](https://github.com/curl/curl/actions/runs/13954267776/job/39062551334#check-step-15), which has NOT been flaky recently, so **there could be a real issue in this PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)
