### ISSUE TITLE
sudo make is not working in curl git repository (last step)for both quiche and ngtcp2

### ISSUE THREAD

**Issue by harriish** [curl/curl#5347]
$sudo make
Making all in lib
make[1]: Entering directory '/home/ubuntu/curl/lib'
make  all-am
make[2]: Entering directory '/home/ubuntu/curl/lib'
  CC       libcurl_la-altsvc.lo
In file included from quic.h:29:0,
                 from urldata.h:136,
                 from altsvc.c:30:
vquic/ngtcp2.h:30:10: fatal error: nghttp3/nghttp3.h: No such file or directory
 #include <nghttp3/nghttp3.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1349: recipe for target 'libcurl_la-altsvc.lo' failed
make[2]: *** [libcurl_la-altsvc.lo] Error 1
make[2]: Leaving directory '/home/ubuntu/curl/lib'
Makefile:773: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/curl/lib'
Makefile:979: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by bagder** [comment]
First, don't use `sudo` when building. It's just wrong.

Then, how did you configure your build before you invoked 'make` ?

**Comment by harriish** [comment]
1) sometimes it displays permission denied or recursive errors, so i used sudo

2)consider quiche version, 
building boringssl and quiche was okk and it enables the alt-svc and quiche feature. I just followed the commands.
the only thing messed up was with make
%%%%%%%%%%%%%%%%%%%%%
 % cd ..
 % git clone https://github.com/curl/curl
 % cd curl
 % ./buildconf
 % ./configure LDFLAGS="-Wl,-rpath,$PWD/../quiche/target/release" --with-ssl=$PWD/../quiche/deps/boringssl/.openssl --with-quiche=$PWD/../quiche/target/release --enable-alt-svc
 % make
%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by bagder** [comment]
You should not need sudo for running make, If you do, something is wrong already and that should be fixed first before continuing. Never run make and build things as root; it is not safe.

When you run make as a user do you get the same error? Can you show us the summary from the end of your `configure` run and if the problem persists, invoke make with `make V=1`, and show us the full command line of the source file that files.

**Comment by harriish** [comment]
Hi 
I will send, please give me sometime

**Comment by emilengler** [comment]
I think the error comes from some envionment variable errors. Maybe the $PWD value is set wrong with sudo or it uses a different one

**Comment by harriish** [comment]
![Screenshot from 2020-05-06 17-15-55](https://user-images.githubusercontent.com/43529736/81245334-fe650380-9014-11ea-8169-b7e8f05f3001.png)

**Comment by harriish** [comment]
i tried with creating two empty directories namely somewhere2 and somewhere3 and instead of giving $PWD  gave /home/ubuntu/somewhere2 and /home/ubuntu/somewhere3 .
In this pic, it clearly shows that nghttp3 is enabled and i end up the same fatal error. 

P.S. i dont know exactly why it shows curl 7.70.1 but i have curl 7.70.0 installed and when i type "curl --http3" it says curl: option --http3: the installed libcurl version doesn't support this.

I dont know , I think I messed up

![Screenshot from 2020-05-06 22-53-01](https://user-images.githubusercontent.com/43529736/81245467-53a11500-9015-11ea-824b-7627337a9d36.png)

**Comment by jay** [comment]
You will need to do what @bagder said, `make V=1`  and show us the output. No screenshots please, just paste in the failed command and its output.

**Comment by bagder** [comment]
`make V=1` must be with an uppercase `V` to have an effect - it will then show the entire compile command lines when building. (Trying to figure out why your compile seems to say that it has ngtcp2 enabled.)

**Comment by bagder** [comment]
> i dont know exactly why it shows curl 7.70.1 

If you build from git right now it shows 7.70.1-DEV because that is the work-in-progress version we're working on.

**Comment by harriish** [comment]
ubuntu@idrac-4QRSV02:~/curl$ make V=1
Making all in lib
make[1]: Entering directory '/home/ubuntu/curl/lib'
make  all-am
make[2]: Entering directory '/home/ubuntu/curl/lib'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H   -I../include -I../lib -I../lib  -DBUILDING_LIBCURL  -DCURL_HIDDEN_SYMBOLS -isystem /usr/local/include -isystem /home/ubuntu/curl/../quiche/deps/boringssl/.openssl/include -isystem /home/ubuntu/curl/../quiche/deps/boringssl/.openssl/include/openssl -isystem /usr/local/include -isystem /home/ubuntu/quiche/include  -fvisibility=hidden -Werror-implicit-function-declaration -O2 -Wno-system-headers  -MT libcurl_la-altsvc.lo -MD -MP -MF .deps/libcurl_la-altsvc.Tpo -c -o libcurl_la-altsvc.lo `test -f 'altsvc.c' || echo './'`altsvc.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /usr/local/include -isystem /home/ubuntu/curl/../quiche/deps/boringssl/.openssl/include -isystem /home/ubuntu/curl/../quiche/deps/boringssl/.openssl/include/openssl -isystem /usr/local/include -isystem /home/ubuntu/quiche/include -fvisibility=hidden -Werror-implicit-function-declaration -O2 -Wno-system-headers -MT libcurl_la-altsvc.lo -MD -MP -MF .deps/libcurl_la-altsvc.Tpo -c altsvc.c  -fPIC -DPIC -o .libs/libcurl_la-altsvc.o
In file included from quic.h:29:0,
                 from urldata.h:136,
                 from altsvc.c:30:
vquic/ngtcp2.h:30:10: fatal error: nghttp3/nghttp3.h: No such file or directory
 #include <nghttp3/nghttp3.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1349: recipe for target 'libcurl_la-altsvc.lo' failed
make[2]: *** [libcurl_la-altsvc.lo] Error 1
make[2]: Leaving directory '/home/ubuntu/curl/lib'
Makefile:773: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/curl/lib'
Makefile:979: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by harriish** [comment]
before that

./configure LDFLAGS="-Wl,-rpath,$PWD/../quiche/target/release" --with-ssl=$PWD/../quiche/deps/boringssl/.openssl --with-quiche=$PWD/../quiche/target/release --enable-alt-svc

shall I remove $PWD and put /home/ubuntu with prefix ?

**Comment by emilengler** [comment]
> shall I remove $PWD and put /home/ubuntu with prefix ?

It's worth to give it a try at least.
The problem is that it cannot find `nghttp3/nghttp3.h`.
Is there something like an include folder in the quiche folder? If so you can include it with `./configure CFLAGS="-I../path/to/include"`

**Comment by emilengler** [comment]
But keep in mind that this is a bug tracker, not for support. I would suggest asking on the curl mailing list or the #curl channel on freenode if you want a live chat

**Comment by harriish** [comment]
I have more to ask 

1) Earlier I have installed curl 7.70.0 manually and procedure is
rm -rf curl*
wget https://curl.haxx.se/download/curl-7.70.0.zip
unzip curl-7.70.0.zip
cd curl-7.70.0
./configure --with-ssl --with-zlib --with-gssapi --enable-ldap --enable-ldaps --with-libssh --with-nghttp2
make
make install

2) next was curl -V which shows
curl 7.70.0 (x86_64-pc-linux-gnu) libcurl/7.70.0 OpenSSL/1.1.1 zlib/1.2.11 brotli/1.0.4 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2020-04-29
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL TLS-SRP UnixSockets

3) when i typed curl --http3 this was the error 
ubuntu@idrac-4QRSV02:~/curl$ curl --http3
curl: option --http3: the installed libcurl version doesn't support this
curl: try 'curl --help' or 'curl --manual' for more information

4) then i tried 
ubuntu@idrac-4QRSV02:~/curl$ sudo apt list --installed | grep 'curl'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libcurl3-gnutls/bionic-updates,bionic-security,now 7.58.0-2ubuntu3.8 amd64 [installed,automatic]
libcurl4/bionic-updates,bionic-security,now 7.58.0-2ubuntu3.8 amd64 [installed,automatic]

**Comment by harriish** [comment]
> > shall I remove $PWD and put /home/ubuntu with prefix ?
> 
> It's worth to give it a try at least.
> The problem is that it cannot find `nghttp3/nghttp3.h`.
> Is there something like an include folder in the quiche folder? If so you can include it with `./configure CFLAGS="-I../path/to/include"`

-->i tried giving /home/ubuntu and it says it is a bad prefix . 
--> tried this ./configure CFLAGS="-I../path/to/include, it configured but make still got the same errors

**Comment by bagder** [comment]
It's not an issue with `$PWD`. The question is how come it thinks ngtcp2 is enabled which causes this:
~~~
 vquic/ngtcp2.h:30:10: fatal error: nghttp3/nghttp3.h: No such file or directory
~~~

It does not happen when I build with quiche support on my dev machine. Have you made sure you cleaned up properly from previous build attempts?

> curl: option --http3: the installed libcurl version doesn't support this

... which happened because in that build you hadn't enabled HTTP/3 support.

**Comment by bagder** [comment]
When I build curl 7.70.0 from the git tag (with quiche), it works fine and I end up with:
~~~
$ ./src/curl -V
curl 7.70.0-DEV (x86_64-pc-linux-gnu) libcurl/7.70.0-DEV BoringSSL zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) nghttp2/1.40.0 quiche/0.3.0 librtmp/2.3
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli Debug HTTP2 HTTP3 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL TrackMemory UnixSockets

**Comment by harriish** [comment]
> It's not an issue with `$PWD`. The question is how come it thinks ngtcp2 is enabled which causes this:
> 
> ```
>  vquic/ngtcp2.h:30:10: fatal error: nghttp3/nghttp3.h: No such file or directory
> ```
> 
> It does not happen when I build with quiche support on my dev machine. Have you made sure you cleaned up properly from previous build attempts?
> 
> > curl: option --http3: the installed libcurl version doesn't support this
> 
> ... which happened because in that build you hadn't enabled HTTP/3 support.

i did.
but i think I messed up by installing curl 7.70.0 manually instead of pulling from git. I think I messed up there. Though i removed curl 7.70.0 files and also with commands like sudo apt-get remove curl.
sudo apt-get purge curl
it still has its presence .

**Comment by bagder** [comment]
"apt-get (install, purge, remove etc) curl" has no meaning for your own-built curl. Now you're just trying random things without logic. I would advice against that as you'll end up hurting yourself.

If your own built curl "still has its presence" after you removed the build directory it is because you installed it, which then put it in the installation prefix directory tree.

Nothing of this seems to be curl bugs or issues really...

**Comment by harriish** [comment]
> It's not an issue with `$PWD`. The question is how come it thinks ngtcp2 is enabled which causes this:
> 
> ```
>  vquic/ngtcp2.h:30:10: fatal error: nghttp3/nghttp3.h: No such file or directory
> ```
> 
> It does not happen when I build with quiche support on my dev machine. Have you made sure you cleaned up properly from previous build attempts?
> 
> > curl: option --http3: the installed libcurl version doesn't support this
> 
> ... which happened because in that build you hadn't enabled HTTP/3 support.

Daniel you are right , I got you now. 
Please listen me, i have two linux ubuntu devices
one is my local machine and the other is a MAAS device (given by my university) which is also ubuntu.

When i did in my local machine it  displays HTTP2:disabled (--with-nghttp2) when i run ./configure LDFLAGS
whereas when i did in the MAAS machine it displays HTTP2: enabled (nghttp2).
This is where the mess is. 

I will figure it out my own . Thanks for your response and thank you everyone.

**Comment by bagder** [comment]
No, that's not it. That's **nghttp2** and I mentioned **ngtcp2**.

But we're not getting anywhere here since you keep changing focus, moving to the next and you don't provide enough info in any stage. We can't help you this way. I will stop answering now until order ensues, or just close this issue unless it doesn't.
