### ISSUE TITLE
PolarSSL: version 1.3.8 now required

### ISSUE THREAD

**Issue by MarcelRaad** [curl/curl#1401]
### I did this

Tried to build curl with PolarSSL on Ubuntu 14.04 Trusty Tahr. It compiled, but linking failed because of an undefined reference to `ssl_session_init` which was introduced in 9f498de9a28e4a4a3f73108756fb7e50af9ec014 and is only available in PolarSSL versions 1.3.8 and 1.3.9. Ubuntu Trusty comes with PolarSSL 1.3.4.

### I expected the following

Either the minimum version documented in INTERNALS.md bumped to 1.3.8 and the minimum `POLARSSL_VERSION_NUMBER` in polarssl.c bumped to `0x01030800` or a successful compilation.

### curl/libcurl version

git master f9d1e9a27f7e11d98a6f8f3b016e320018977a7c

### operating system

Ubuntu Trusty

**Comment by bagder** [comment]
I'm inclined to say that we simply raise the bar to 1.3.8 unless someone steps forward and do the work to make sure older versions get supported again.

Reading up on [recent security details](https://tls.mbed.org/tech-updates/releases/mbedtls-2.4.2-2.1.7-and-1.3.19-released), it seems PolarSSL users shouldn't use anything other than 1.3.19 anyway...

**Comment by jay** [comment]
We could fix it I think. That call in the final two versions of PolarSSL is just this
~~~c
void ssl_session_init( ssl_session *session )
{
    memset( session, 0, sizeof(ssl_session) );
}
~~~
Regarding security for PolarSSL in Trusty I assume it gets security fixes for their LTS?

**Comment by MarcelRaad** [comment]
> We could fix it I think. That call in the final two versions of PolarSSL is just this

Right, as there won't be new versions of PolarSSL, we don't need to consider future changes to `ssl_session_init`. If @bagder agrees and nobody's faster than me, I'll change that to just use the memset.

**Comment by bagder** [comment]
I'm totally fine with that!
