### PR TITLE
configure: fix the -ldl check for openssl, add -lpthread check

### LINKED ISSUE #1426: configure check for static openssl dependency -ldl is broken
### I did this

I ran configure with a custom ssl path to static openssl and it could not detect that -ldl is required. In my case the detection is never done because HAVECRYPTO is never properly detected.

configure will [check for crypto lib](https://github.com/curl/curl/blob/curl-7_53_1/configure.ac#L1512-L1525) by trying to link using function HMAC_Update and HMAC_Init_ex. The problem is at this point the -lssl (which requires -ldl in this static case) is already in LIBS and therefore is used for the link test:

~~~
configure:22350: checking for HMAC_Update in -lcrypto
configure:22372: gcc -o conftest -O2 -Wno-system-headers   -I/home/owner/openssl-1.0.2k/../openssl/include  -L/home/owner/openssl/lib -L/home/owner/openssl-1.0.2k/../openssl/lib conftest.c -lcrypto  -lssl -lcrypto -llber -lldap -lz  >&5
/home/owner/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
...
~~~

So HAVECRYPTO is never set yes and the subsequent checks that should be done are never called. One of those is the [check for -ldl](https://github.com/curl/curl/blob/curl-7_53_1/configure.ac#L1528-L1566). So -lssl I think would have to be removed somehow for the HAVECRYPTO test. Also -lcrypto is already in LIBS at this point as well so maybe we could just skip the test in that case.

Since -ldl afaik is required by -lssl static I don't know why we're only testing it if HAVECRYPTO, and it should probably be tested regardless.

Also I think SSLeay_add_all_algorithms in the -ldl test will need to be replaced for a function that is also in OpenSSL 1.1.0.

Ref: #1420
/cc @tessus

### PR DESCRIPTION
**Pull request by bagder**
The check for if -ldl is needed to build with (a statically built)
openssl was broken. This repairs the check, and adds a check for
-lpthread as well since OpenSSL 1.1.0+ does in fact require -lpthread so
only adding -ldl for a static openssl build is no longer enough.

Reported-by: Jay Satiro
Fixes #1426

### CODE REVIEW

**Comment by bagder** [comment]
Turns out this PR doesn't fix the #1426 case but it *did* fix my test builds using a static OpenSSL 1.1.0 devel version (from git master) so unless someone objects I intend to merge this soon. It removes the need to specify `LIBS="-ldl -lpthread" ./configure`

**Comment by bagder** [comment]
> it looks like you've changed the -ldl check to only occur when HMAC_Init_ex link fails

Yes. When building with a static openssl that requires -ldl, trying to link the library to use HMAC_Init_ex fails. The previous (current) way to check for -ldl is pointless since it will fail to detect openssl completely before even considering the -ldl issue.

> Also at this point there may already be -lssl -lcrypto from pkg-config which seems like we could skip these crypto checks then

Maybe, but I would prefer to have the -ldl and -lpthread checks only get tried when it fails without those libs and I only want to add those specific libs to try to fix the build and not make conclusions or guesses about the other libs that are used or not used.

Hence the flow with this patch goes like this:

1. openssl is detected fine so far
2. verifty that can link fine with `HMAC_Init_ex`, if yes, then we're good. if not
3. retry the link but now with `-ldl` added to LIBS. If it succeeds we're good, if not
4. retry the link but now *also* add `-lpthread` to LIBS. If it succeeds we're good, if not we fail the libcrypto detection

I've tested this with a static openssl from their git master and with this fix, it works without any custom LIBS set, but without this patch it will fail to detect a static only openssl completely.
