### PR TITLE
build: bump minimum required mingw-w64 to v3.0 (from v1.0)

### PR DESCRIPTION
**Pull request by vszakats**
mingw-w64 3.0 was released on 2013-09-20. Offered by Debian jessie.

1.0 and 2.0 were released in 2011. It seems unlikely that many people
use them. The oldest downloadable toolchain (that I know of) comes with
3.0. Due to this, older versions weren't CI tested, and probably seldom
tested elsewhere. The last bugfix update for both 1.0 and 2.0 was
released in 2015.

curl can now assume availability of these 3.0 features/fixes:
- 64-bit file offsets.
- `ADDRESS_FAMILY` type.
- `__MINGW_PRINTF_FORMAT` macro. (in public curl headers)

Public curl headers keep supporting older mingw-w64 versions.

Fixes #17984

---

- [x] rebase on #18032. (No longer needed)
- [x] add mingw-w64 4.8.1 dl-mingw job, disable examples.
- [x] add mingw-w64 version check for configure?
  Since in autotools this needs verbose code and feeling overkill, let's do this if this is causing an actual issue.
  The version is checked in source anyway. CMake does check, but it's just 3 extra lines.
  The patch is in the commit history and may become useful if curl happens to bump this requirement higher.
- [x] perhaps even detect and show mingw-w64 version as in cmake? [I don't know how to implement this]
- [ ] drop logic dealing with missing `ADDRESS_FAMILY` type.
- [ ] review remaining uses of `__MINGW32__` throughout the code, see if all is still needed.
  in particular in: lib/vtls/schannel_int.h and lib/curl_setup.h

### CODE REVIEW

**Comment by vszakats** [comment]
curl confirmed to build with mingw-w64 3.0, via a temporary CI job within this PR.

Though the job failed building lib517 due to an unrelated problem. I'll address in
a separate PR and then add this job permanently in this PR. → #18032

**Comment by vszakats** [comment]
I'm considering bumping the minimum further, possibly to v4, v5 or v6.

- mingw-w64 v3 (and v2) have a bug when targeting Vista+.
  It includes `windns.h` which collides with curl internal symbols.
  Fixed in v4.
  ```
  lib/doh.h:54:3: error: expected identifier before numeric constant
     DNS_TYPE_A = 1,
     ^
  ```
  Ref: https://github.com/curl/curl/actions/runs/16551209676/job/46806303365?pr=18009
  (Though fixing this in curl by namespacing these symbols is also an option)
  → https://github.com/curl/curl/pull/18041
- Going v4 allows dropping the workaround for missing
  `CERT_CHAIN_EXCLUSIVE_ENABLE_CA_FLAG` macro.
- v5 and older requires a workaround for `if_nametoindex` due to a header bug.
- mingw-w64 v5 and older target Server 2003 (~XP) by default
- mingw-w64 v6, v7, v8 target Server 2003 (~XP) with an option to override at build time.
  (the toolchains we use do not change this default)
- mingw-w64 v9 and later (as of v13) target Win10 by default
  (the toolchains we use do not change this default)

v4 was released on 2015-Mar-05. Never offered by Debian, also not present in well-known pre-built toolchains.
v5 was released on 2016-Oct-17. Offered by Debian stretch.
v6 was released on 2018-Sep-14. Offered by Debian buster.

https://github.com/curl/curl/discussions/17984#discussioncomment-13882549
