### PR TITLE
http: split Curl_http_input_auth into sub functions

### LINKED ISSUE #16412: GHA/curl-for-win: failing since commit d1fc1c4a854 due to lib/http.c compiler warning
### I did this

Seen with GCC 13.0.0 on Windows, unity mode:
```
In file included from /home/runner/work/curl/curl/curl/_x86-win-ucrt-bld/lib/CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c:190:
/home/runner/work/curl/curl/curl/lib/http.c: In function 'Curl_http_input_auth':
/home/runner/work/curl/curl/curl/lib/http.c:1053:11: error: potential null pointer dereference [-Werror=null-dereference]
 1053 |     while(*auth && *auth != ',') /* read up to the next comma */
      |           ^~~~~
```
Ref: https://github.com/curl/curl/actions/runs/13445342926/job/37569288864#step:3:5784

It's probably one of those annoying ones, but it wasn't there before this patch.

### I expected the following

CI passing

### curl/libcurl version

d1fc1c4a854d5cc809cc4ae59a9511900228023a

### operating system

(any?)

### PR DESCRIPTION
**Pull request by bagder**
To help the compiler realize that 'auth' cannot go NULL within Curl_http_input_auth.

Fixes #16412
Reported-by: Viktor Szakats

### CODE REVIEW

**Comment by testclutch** [comment]
Analysis of PR #16416 at [e326fbaa](https://github.com/curl/curl/commit/e326fbaa3e2355fae1b86f1a9aaa53860acd629a):

[Test 1917 failed](https://github.com/curl/curl/actions/runs/13452660260/job/37589877447#check-step-42), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test 3018 failed](https://github.com/curl/curl/actions/runs/13452660260/job/37589877447#check-step-42), which has NOT been flaky recently, so **there could be a real issue in this PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by bagder** [comment]
Turned out a somewhat large fix just to silence the warning, but I think the outcome is pretty nice.

**Comment by vszakats** [comment]
> Turned out a somewhat large fix just to silence the warning, but I think the outcome is pretty nice.

Thanks!

It fixed it, the CI job is green now:
https://github.com/curl/curl/actions/runs/13457013630/job/37603155459
