### ISSUE TITLE
Building for *-windows-msvc using clang fails

### ISSUE THREAD

**Issue by joostn** [curl/curl#16707]
### I did this

Hi,

I'm cross building libcurl as a static library for Windows using clang and the MSVC runtime (so not mingw). This is broken since commit https://github.com/curl/curl/commit/12a6de2f660dd692cce93cb65ce6e3ec126bb531 which adds 
```
if(HAVE_BORINGSSL OR HAVE_AWSLC)
    if(OPENSSL_USE_STATIC_LIBS AND CMAKE_C_COMPILER_ID MATCHES "Clang")
      list(APPEND CURL_LIBS "stdc++")
      list(APPEND CMAKE_REQUIRED_LIBRARIES "stdc++")
    endif()
  endif()
```
As I'm using a static boringssl it attempts to link in libstdc++ which is not available in my environment.

During configure, this and other tests fail:
Check size of curl_off_t - failed
because try_compile() is failing.

Subsequently building fails with this error:
```
src/thirdparty-curl/lib/curl_setup.h:569:6: warning: 'SIZEOF_CURL_OFF_T' is not defined, evaluates to 0 [-Wundef]
  569 | #if (SIZEOF_CURL_OFF_T < 8)
      |      ^
src/thirdparty-curl/lib/curl_setup.h:570:2: error: "too small curl_off_t"
  570 | #error "too small curl_off_t"
```

For reference, my cmake toolchain file looks like this:
```
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ARM64)
set(CMAKE_SYSROOT /nix/store/hgmym4h8w91mhph3hq12g5diim2ysjwp-msvcsdk-14.40.33807)

set(CMAKE_C_COMPILER "/nix/store/js4wi2r81mdi4yxmds890jplbwhi1jnz-clang-18.1.8/bin/clang")
set(CMAKE_CXX_COMPILER "/nix/store/js4wi2r81mdi4yxmds890jplbwhi1jnz-clang-18.1.8/bin/clang++")
set(CMAKE_AR "/nix/store/36jks332pa120yr5hqjljcnqlb6vb3ky-llvm-binutils-18.1.8/bin/llvm-ar")
set(CMAKE_RANLIB "/nix/store/36jks332pa120yr5hqjljcnqlb6vb3ky-llvm-binutils-18.1.8/bin/llvm-ranlib")
set(CMAKE_STRIP "/nix/store/36jks332pa120yr5hqjljcnqlb6vb3ky-llvm-binutils-18.1.8/bin/llvm-strip")
set(CMAKE_RC_COMPILER "/nix/store/1xynjs08cwcpx7lx5czl52imshj8h6av-llvm-rc-with-clang-1.0/bin/llvm-rc")

set(NH_C_CXX_FLAGS 
    "-target aarch64-windows-msvc -march=armv8.2-a -Wno-nonportable-include-path -fno-omit-frame-pointer -Xclang -internal-isystem -Xclang /nix/store/hgmym4h8w91mhph3hq12g5diim2ysjwp-msvcsdk-14.40.33807/include -Xclang -internal-isystem -Xclang /nix/store/vvaf9fxzhr4yshg05ks22s67zb0hmg83-windowssdk-26100.3037.250123-2219/include/ucrt -Xclang -internal-isystem -Xclang /nix/store/vvaf9fxzhr4yshg05ks22s67zb0hmg83-windowssdk-26100.3037.250123-2219/include/um -Xclang -internal-isystem -Xclang /nix/store/vvaf9fxzhr4yshg05ks22s67zb0hmg83-windowssdk-26100.3037.250123-2219/include/shared -Xclang -internal-isystem -Xclang /nix/store/vvaf9fxzhr4yshg05ks22s67zb0hmg83-windowssdk-26100.3037.250123-2219/include/winrt -D_CRT_SECURE_NO_WARNINGS=1 -resource-dir /nix/store/h9n103k0pmmrdiv2brww9zavm2vqjgf8-clang-18.1.8-lib/lib/clang/18" 
)
set(NH_LINKER_FLAGS "-L/nix/store/hgmym4h8w91mhph3hq12g5diim2ysjwp-msvcsdk-14.40.33807/lib/arm64 -L/nix/store/vvaf9fxzhr4yshg05ks22s67zb0hmg83-windowssdk-26100.3037.250123-2219/lib/ucrt/arm64 -L/nix/store/vvaf9fxzhr4yshg05ks22s67zb0hmg83-windowssdk-26100.3037.250123-2219/lib/um/arm64")

set(CMAKE_C_FLAGS "${NH_C_CXX_FLAGS} ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${NH_C_CXX_FLAGS} ${CMAKE_CXX_FLAGS}")
set(CMAKE_RC_FLAGS "${NH_C_CXX_FLAGS} ${CMAKE_RC_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${NH_LINKER_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${NH_LINKER_FLAGS}")

# Disable pkg-config completely, we don't need it for Windows:
set(ENV{PKG_CONFIG_LIBDIR} "")

set(CMAKE_FIND_ROOT_PATH "/var/notexist")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)  # find programs on the host
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)   # libraries, includes only under CMAKE_SYSROOT
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```

I'm configuring as follows:
```
/nix/store/01dapiw4pjrc9s0166dcyg9xkw0rv01z-cmake-3.31.5/bin/cmake \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_TOOLCHAIN_FILE:FILEPATH=/nix/store/gv678gz6g2mvzvh65d8izq7sf8zvf4bx-windows_aarch64toolchain.cmake \
-DCMAKE_MSVC_RUNTIME_LIBRARY='MultiThreaded' \
-DCMAKE_POLICY_DEFAULT_CMP0091=NEW \
-DCMAKE_MAKE_PROGRAM=/nix/store/24fw7j8585szpxvag9icwm692daa49s3-ninja-1.12.1/bin/ninja \
-DCMAKE_RC_COMPILER=/nix/store/1xynjs08cwcpx7lx5czl52imshj8h6av-llvm-rc-with-clang-1.0/bin/llvm-rc \
-DCMAKE_DEBUG_POSTFIX='' \
-DBUILD_SHARED_LIBS=OFF \
-DBUILD_CURL_EXE=OFF \
-DCURL_USE_LIBSSH2=OFF \
-DUSE_NGHTTP2=OFF \
-DBUILD_TESTING=OFF \
-DCURL_USE_OPENSSL=ON \
-DOPENSSL_USE_STATIC_LIBS=ON \
-DOPENSSL_INCLUDE_DIR=thirdparty/boringssl-0.20250114.0-prefix/include \
-DOPENSSL_CRYPTO_LIBRARY=thirdparty/boringssl-0.20250114.0-prefix/lib/crypto.lib \
-DOPENSSL_SSL_LIBRARY=thirdparty/boringssl-0.20250114.0-prefix/lib/ssl.lib \
-DCURL_USE_MBEDTLS=OFF \
-DCURL_STATICLIB=ON \
-DCURL_USE_LIBPSL=OFF \
-DCURL_ENABLE_SSL=ON \
-DCURL_DISABLE_LDAP=ON \
-DUSE_LIBIDN2=OFF \
-DZLIB_INCLUDE_DIR=thirdparty/zlib-51b7f2a-prefix/include \
-DZLIB_LIBRARY=thirdparty/zlib-51b7f2a-prefix/lib/z.lib \
-DCMAKE_INSTALL_PREFIX=thirdparty/curl-curl-8_12_1-prefix \
-GNinja \
-S thirdparty/curl-curl-8_12_1-prefix/src/thirdparty-curl -B thirdparty/curl-curl-8_12_1-prefix/src/thirdparty-curl-build
```

I was able to work around the issue by removing the two stdc++ references, but leaving this bug report for reference.

I'm not sure how to properly fix the issue; libstdc++ might be needed on Windows with mingw, so we would somehow need to discern between the msvc runtime and the mingw runtime?

### I expected the following

I expected a successful build.

### curl/libcurl version

curl 8.12.1

### operating system

Linux bird 6.12.12 #1-NixOS SMP PREEMPT_DYNAMIC Sat Feb  1 17:39:40 UTC 2025 x86_64 GNU/Linux

**Comment by vszakats** [comment]
Thanks for your report. Does this patch fix your build?
```
--- i/CMakeLists.txt
+++ w/CMakeLists.txt
@@ -811,7 +811,7 @@ if(CURL_USE_OPENSSL)
   cmake_pop_check_state()
 
   if(HAVE_BORINGSSL OR HAVE_AWSLC)
-    if(OPENSSL_USE_STATIC_LIBS AND CMAKE_C_COMPILER_ID MATCHES "Clang")
+    if(OPENSSL_USE_STATIC_LIBS AND CMAKE_C_COMPILER_ID MATCHES "Clang" AND NOT MSVC)
       list(APPEND CURL_LIBS "stdc++")
       list(APPEND CMAKE_REQUIRED_LIBRARIES "stdc++")
     endif()
```

**Comment by vszakats** [comment]
> Also, adding -lstdc++ seems wrong to me in other circumstances as well; we might be building against libc++.

BoringSSL/AWS-LC require a C++ lib and it was broken by default when linking statically.
The workaround for customizing the C++ library, is not enabling `OPENSSL_USE_STATIC_LIBS`
and passing all the custom libs via manual means. Which seems similar to what was needed before this patch (to handle all cases).

What would be a better way to fix it?

**Comment by vszakats** [comment]
> No it doesn't, I tried already. I'm using clang on linux. Only the microsoft emulating clang-cl.exe sets MSVC to true, not the regular clang.

Since you're passing BoringSSL libs manually already, dropping `-DOPENSSL_USE_STATIC_LIBS=ON` might work to fix your build, by avoiding the condition to enable `stdc++`.

Other than that we'd need a way to detect this build case, aka plain clang + MSVC SDK. (It's something we don't currently test in CI.)

**Comment by joostn** [comment]
Ah yes, setting -DOPENSSL_USE_STATIC_LIBS=OFF fixes it!

Apologies, I should have tried that.

**Comment by vszakats** [comment]
Thanks! I'm making a "best effort" attempt to mitigate this in #16708.

Let me know if that fixes the issue. If not, your `CMAKE_EXE_LINKER_FLAGS` `CMAKE_SHARED_LINKER_FLAGS` values would help tweaking the logic.
