### PR TITLE
m4/curl-wolfssl.m4: fix build with older wolfSSL

### PR DESCRIPTION
**Pull request by baruchsiach**
Commit 0159100f4f78 ("lib: use (u)int64_t instead of long long") removed definition of SIZEOF_LONG_LONG for wolfSSL. This breaks autotools build for wolfSSL version 5.7.2 at least:

In file included from .../arm-buildroot-linux-gnueabi/sysroot/usr/include/wolfssl/wolfcrypt/hash.h:29,
                 from .../arm-buildroot-linux-gnueabi/sysroot/usr/include/wolfssl/openssl/md5.h:32,
                 from md5.c:76:
.../arm-buildroot-linux-gnueabi/sysroot/usr/include/wolfssl/wolfcrypt/types.h:1289:10: error: #error "bad math long / long long settings"
 1289 |         #error "bad math long / long long settings"
      |          ^~~~~
.../arm-buildroot-linux-gnueabi/sysroot/usr/include/wolfssl/wolfcrypt/types.h:1291:5: error: empty enum is invalid
 1291 |     };
      |     ^
make[3]: *** [Makefile:2966: libcurl_la-md5.lo] Error 1

Restore SIZEOF_LONG_LONG macro definition to fix the build.

### CODE REVIEW

**Comment by bagder** [comment]
Maybe add a comment that "it is needed for version 5.7.2" ? It seems it is not necessary for >= 5.8.4... (at least, I don't know exactly when this requirement was removed)

**Comment by vszakats** [comment]
@baruchsiach Did you try building the latest master (without this patch)?
Asking because`lib/md5.c` no longer includes `wolfssl/openssl/md5.h`, and
thus the error must have changed.

With CMake it works without this hack back to wolfSSL 5.0.0. (libssh2 also
builds with 5.5.4, using this header, and no trick). It'd nice to understand
what's different in this specific case, before readding.

Ref: https://github.com/wolfSSL/wolfssl/blob/b5a835abed77ee54897015ebecaf3b95eb0d338a/wolfssl/wolfcrypt/types.h#L224-L256

**Comment by baruchsiach** [comment]
> @baruchsiach Did you try building the latest master (without this patch)? Asking because`lib/md5.c` no longer includes `wolfssl/openssl/md5.h`, and thus the error must have changed.

I tried building with commit bf6a34d8eb5 backported on top of 8.19.0. Error path changes a little:

```
In file included from .../arm-buildroot-linux-gnueabihf/sysroot/usr/include/wolfssl/wolfcrypt/md5.h:30,
                 from md5.c:96:
.../arm-buildroot-linux-gnueabihf/sysroot/usr/include/wolfssl/wolfcrypt/types.h:1289:10: error: #error "bad math long / long long settings"
 1289 |         #error "bad math long / long long settings"
      |          ^~~~~
../arm-buildroot-linux-gnueabihf/sysroot/usr/include/wolfssl/wolfcrypt/types.h:1291:5: error: empty enum is invalid
 1291 |     };
      |     ^
make[4]: *** [Makefile:2965: libcurl_la-md5.lo] Error 1
```

Is there any other relevant commit?

This appears to be a bug in wolfSSL autotools code. `config.h` does define `HAVE_LIMITS_H`, but in `types.h` this macro is undefined. The end result is that `SIZEOF_LONG_LONG` is undefined. This breaks later in `types.h` because the combination of `!defined(USE_FAST_MATH) && defined(SIZEOF_LONG) && (SIZEOF_LONG == 4)` is not handled.

**Comment by bkuhls** [comment]
Please try this fix from wolfSSL instead: https://github.com/wolfSSL/wolfssl/pull/10097

**Comment by baruchsiach** [comment]
> Please try this fix from wolfSSL instead: [wolfSSL/wolfssl#10097](https://github.com/wolfSSL/wolfssl/pull/10097)

That is a better fix when you are able to patch and rebuild wolfSSL. For the general case when you have to deal with unpatched wolfSSL versions you still need something like this PR to fix the build.

**Comment by bagder** [comment]
I'm still curious in knowing *when* this is necessary and adding that information together with this change. Since isn't necessary in our CI there is clearly a wolfSSL version or other combination that makes it not needed. If we don't provide this information as a comment for this configure check there's just a big risk that someone will remove it again soon.

**Comment by vszakats** [comment]
I wonder if this should rather be fixed locally by builds specifically experiencing this.
It looks like a wolfSSL issue to me. If curl wants to carry a workaround, we'd really need
to know when and why this is needed. In this case, we may want to add the workaround
for CMake too.

**Comment by baruchsiach** [comment]
wolfssl issue https://github.com/wolfSSL/wolfssl/issues/9936, as well as FreeBSD [report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=294287) indicate that only 32-bit builds are affected. Does curl CI test 32-bit builds?

**Comment by vszakats** [comment]
> wolfssl issue [wolfSSL/wolfssl#9936](https://github.com/wolfSSL/wolfssl/issues/9936), as well as FreeBSD [report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=294287) indicate that only 32-bit builds are affected. Does curl CI test 32-bit builds?

Thanks for the details!

Just a couple of 32-bit jobs to ensure curl itself builds cleanly with common
dependencies.

I'm not a big fan of rolling a wolfSSL fix within the curl build. This particular
trick was a repeat puzzle when dealing with SIZEOF macros. I wonder if
setting CPPFLAGS or applying https://github.com/wolfSSL/wolfssl/pull/10097
would be a better solution in this case for those who use this config.

**Comment by bagder** [comment]
Seems abandoned.

**Comment by jverne** [comment]
For those of us more or less stuck on a specific FIPS version of WolfSSL, is there advice in here for the most recent libcurl I can expect to build on a 32-bit embedded platform?

Otherwise I'll experiment with setting `CPPFLAGS=-D...` on the configure line I suppose.
