### ISSUE TITLE
Linking curl fails with /usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `sk_pop_free_ex'

### ISSUE THREAD

**Issue by MounikaMadhugiripalli** [curl/curl#8261]
this is the error:

/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `sk_pop_free_ex'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_set_mode'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `BIO_reset'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_set_tlsext_host_name'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `sk_value'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_add0_chain_cert'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `OPENSSL_malloc'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_set_msg_callback_arg'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `BIO_read_filename'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `EVP_MD_CTX_destroy'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `BIO_get_mem_ptr'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_clear_chain_certs'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_add_extra_chain_cert'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `OPENSSL_free'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_get_ex_new_index'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_set_session_cache_mode'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_set_max_proto_version'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `SSL_CTX_set_min_proto_version'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `EVP_MD_CTX_create'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `sk_num'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `BIO_set_ssl'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `sk_pop'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `BIO_get_mem_data'

### I did this
cd quiche;cargo build --package quiche --release --features ffi,pkg-config-meta,qlog; mkdir quiche/deps/boringssl/src/lib; ln -vnf $(find target/release -name libcrypto.a -o -name libssl.a) quiche/deps/boringssl/src/lib/; cd ..; 

git clone https://github.com/curl/curl; cd curl; 
autoreconf -fi; ./configure LDFLAGS="-Wl,-rpath,$PWD/../quiche/target/release" --with-openssl=$PWD/../quiche/quiche/deps/boringssl/src --with-quiche=$PWD/../quiche/target/release;
make;

### I expected the following
I expected make to function with no errors

### curl/libcurl version
7.81

[curl -V output]

### operating system
ubuntu 20.04

**Comment by dfandrich** [comment]
This sounds on first glance like you're trying to link curl with a different
version of the OpenSSL library than the one that the header files expect.

**Comment by okainov** [comment]
Same here. Was working perfectly with 7.79.0 and fails with this error when trying to build with 7.81.0

@dfandrich any advice, how can one fix it? I'm not using OpenSSL explicitly, actually it seems I'm explicitly disabling it in my cmake file...

Has something changed here between 7.79.1 and 7.81.0?

```

  CMAKE_ARGS -DBUILD_CURL_EXE=OFF
             -DBUILD_SHARED_LIBS=OFF
             -DBUILD_TESTING=OFF
             # we only do HTTP requests, so disable all the other protocols and
             # any encryption stuff
             -DHTTP_ONLY=ON
             -DCMAKE_USE_OPENSSL=OFF
             -DCURL_CA_PATH=none
             -DCURL_ZLIB=OFF
             -DCMAKE_USE_LIBSSH2=OFF
             -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
             -DCMAKE_C_FLAGS=${CURL_C_FLAGS}
             -DCMAKE_C_LINK_FLAGS=${CURL_LINKER_FLAGS}
             -DCMAKE_POSITION_INDEPENDENT_CODE=ON
             -DCMAKE_DEBUG_POSTFIX=
```

**Comment by MounikaMadhugiripalli** [comment]
@dfandrich  do you know chick version of curl is expected ? My purpose is to get curl to accept http3 .. I dun need a specific version of curl .. I upgraded cuz previous version (7.68 seemed to have other issues that were fixed in later versions )

**Comment by bagder** [comment]
@okainov your problem seems completely different: you use cmake and you don't build with HTTP/3 support.

**Comment by bagder** [comment]
@MounikaMadhugiripalli in your build, are the two libs libcrypto.a libssl.a in `$PWD/../quiche/quiche/deps/boringssl/src/lib`?

**Comment by bagder** [comment]
maybe using `$PWD` isn't the most clever in a build script

**Comment by MounikaMadhugiripalli** [comment]
@dfandrich they are located in quiche/quiche/deps/boringssl/src/lib64

**Comment by MounikaMadhugiripalli** [comment]
@bagder i can hardcode my path

**Comment by MounikaMadhugiripalli** [comment]
@dfandrich Thankyou that seems to be the problem.. I also copied them to lib folder and linker error seems to be fixed ! :) thankyou I was really struggling with this !!

**Comment by MounikaMadhugiripalli** [comment]
@badger Thanku
