### ISSUE TITLE
GCC-14 build fails on MacOSX using vcpkg

### ISSUE THREAD

**Issue by garthgoodson** [curl/curl#13700]
### I did this

Compiled curl using vcpkg on Mac OSX using gcc-14 (14.1) installed from brew.
macOS: 14.3-arm64
CLT: 15.3.0.0.1.1708646388

I got the following error:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:28,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:27,
                 from /src//external/vcpkg/buildtrees/curl/src/curl-8_7_1-d8a6f70132.clean/lib/vtls/sectransp.c:57:
/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFUserNotification.h:126:1: error: 
attributes should be specified before the declarator in a function definition
  126 | CF_INLINE CFOptionFlags CFUserNotificationCheckBoxChecked(CFIndex i) API_AVAILABLE(macos(10.0)) API_UNAVAILABLE(ios, watchos, tvos) {return ((
CFOptionFlags)(1UL << (8 + i)));}
      | ^~~~~~~~~

### I expected the following

vcpkg to compile the package

### curl/libcurl version

curl-8_7_1-d8a6f70132

### operating system

Darwin MacBook-Pro.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:59 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6030 arm64

**Comment by vszakats** [comment]
An Apple system header is failing to compile with gcc. It's been happening since macOS SDK 13, also with gcc 13.2. The solution is to use SDK 12, or Apple clang. Or Apple making their SDK headers gcc-compatible.

**Comment by garthgoodson** [comment]
My system builds with gcc 13.2.

**Comment by vszakats** [comment]
The problem is detected in Apple's headers, not in curl code. It may be a new incompatibility then (and the old ones fixed?).

Can you try building without Secure Transport to see if that changes the results?

**Comment by vszakats** [comment]
Found the root cause:

It's caused by a gcc patch-set applied by Homebrew to gcc, which
enabled the `availability` attribute. This breaks the build because
the way the Apple SDK uses attributes (when available) are incompatible
with how gcc accepts them.

See more here:
https://github.com/curl/curl/pull/14091#issuecomment-2222703468

**Comment by vszakats** [comment]
PR with workaround: #14155
