### ISSUE TITLE
Regression with semicolon in ftp password

### ISSUE THREAD

**Issue by balcaina** [curl/curl#1252]
### I did this

I am using the curl library in my program and I recently upgraded from version 7.21.4 to version 7.50.1 and I noticed a behavior change with semicolon in ftp password for example when using the URL "ftp://user:pass;word@example.com"

### I expected the following

I expected my program to use "user" and "pass;word" for authentication when using the URL "ftp://user:pass;word@example.com" but instead I have "user" and "pass".

With curl 7.21.4, the URL "ftp://user:pass;word@example.com" was giving "user" and "pass;word" for authentication.

### curl/libcurl version

curl -V
curl 7.50.1 (x86_64-pc-linux-gnu) libcurl/7.50.1 OpenSSL/1.0.2h zlib/1.2.5 c-ares/1.7.5
Protocols: file ftp ftps http https smb smbs smtp smtps 
Features: AsynchDNS Largefile NTLM NTLM_WB SSL libz UnixSockets

### operating system

uname -r
3.16.0-4-amd64

**Comment by bagder** [comment]
Agreed. Regression brought by 73aa95592f47d4. The semicolon (and the associated option it was added for) should not be treated like this for HTTP:// URLs.

Semicolons are *sub-delims* according to RFC3986 which allows them to serve as delimiters for scheme-specific things, but there's no such field for HTTP there and thus it should be allowed...

**Comment by bagder** [comment]
thanks for your report!

**Comment by balcaina** [comment]
Thanks for the fix !
