### PR TITLE
Appveyor: add Visual Studio solution build

### PR DESCRIPTION
**Pull request by MarcelRaad**
As expected, it fails to link because of https://github.com/curl/curl/pull/3934#issuecomment-495482666.

### CODE REVIEW

**Comment by bagder** [comment]
Seems `if_nametoindex` causes problems as presumed:

~~~
url.obj : error LNK2019: unresolved external symbol _if_nametoindex@4 referenced in function _zonefrom_url [C:\projects\curl\projects\Windows\VC15\lib\libcurl.vcxproj]

**Comment by captain-caveman2k** [comment]
Once #3958 is in this should be go to go ;-)

**Comment by MarcelRaad** [comment]
Passing now :-) Will merge once I'm back at a computer.
