### ISSUE TITLE
Curl static build failing due to the build searching for DLL of LIBSSH2 , although static build has been mentioned 

### ISSUE THREAD

**Issue by devdatt9129** [curl/curl#12673]
### I did this

cd winbuild
nmake /f Makefile.vc mode=static VC=14 USE_STATIC_CRT=yes WITH_SSL=static SSL_PATH=C:/path/ WITH_SSH2=static SSH2_PATH=C:/path/ ENABLE_WINSSL=no DEBUG=no RTLIBCFG=static MAKE=nmake

### I expected the following

I expected successful build of curl as a static library but i am getting the following errors

```
libssh2.lib(session.obj) : error LNK2019: unresolved external symbol __imp__difftime64 referenced in function difftime
libssh2.lib(misc.obj) : error LNK2001: unresolved external symbol __imp__wassert
libssh2.lib(transport.obj) : error LNK2001: unresolved external symbol __imp__wassert
libssh2.lib(kex.obj) : error LNK2001: unresolved external symbol __imp__wassert
libssh2.lib(channel.obj) : error LNK2001: unresolved external symbol __imp__wassert
libssh2.lib(sftp.obj) : error LNK2001: unresolved external symbol __imp__wassert
libssh2.lib(crypto.obj) : error LNK2001: unresolved external symbol __imp__wassert
libssh2.lib(userauth.obj) : error LNK2019: unresolved external symbol __imp_rewind referenced in function file_read_publickey
..\builds\libcurl-vc14-x64-release-static-ssl-static-ssh2-static-ipv6-sspi\bin\curl.exe : fatal error LNK1120: 3 unresolved externals
```

I have set the RTLIBCFG=static flag as well so the project properties are set to use the static CRT (/MT) not the DLL. Cannot understand why is it showing unresolved external symbols then. 

### curl/libcurl version

curl 8.3.0

### operating system

Windows 8

**Comment by vszakats** [comment]
Mostly just guessing here but it looks like that the `libssh2.lib` _is_ a static one, but one that was built against the dynamic CRT, while building the whole project against the static CRT, hence the errors.

**Comment by devdatt9129** [comment]
by passing RTLIBCFG=static aren't we implying that we want to build with the static CRT. If not ,can you tell me how to build with static CRT not the dynamic?

**Comment by vszakats** [comment]
This option sets this for the curl build, but libssh2 was already built separately at that point. For libssh2, rebuilding it with `cmake [...] -DCMAKE_C_FLAGS=/MT` might do the same.

**Comment by jakitliang** [comment]
Haha, libcurl is dead.

**Comment by vszakats** [comment]
Given the information we got, this looks like a static build mixup across a dependencies, and not an issue with curl itself.
