### ISSUE TITLE
_fseeki64 incorrectly detected as found when cross-compiling for iOS.

### ISSUE THREAD

**Issue by lhunath** [curl/curl#15525]
### I did this

It appears the change introduced by #15164 caused an issue cross-compiling curl for iOS/aarch64.

With the following in `CMakeLists.txt`:
```
check_function_exists("_fseeki64"     HAVE__FSEEKI64)
```
Running the following:
```
cmake -B libcurl-iphoneos -S libcurl -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DCMAKE_TOOLCHAIN_FILE=/Users/hubstaff/Developer/hubstaff/ios/hubstaff-core/toolchains/ios.toolchain.cmake -DCMAKE_INSTALL_PREFIX=/Users/hubstaff/Developer/hubstaff/ios/hubstaff-core/build/__third_party__/curl/distro/ios/ -DBUILD_CURL_EXE=OFF -DBUILD_SHARED_LIBS=OFF -GXcode -DBUILD_EXAMPLES=OFF -DBUILD_LIBCURL_DOCS=OFF -DBUILD_MISC_DOCS=OFF -DENABLE_CURL_MANUAL=OFF -DCURL_USE_SECTRANSP=ON -DUSE_APPLE_IDN=ON -DUSE_NGHTTP2=OFF -DCURL_USE_LIBPSL=OFF
```
Results in:
```
-- Looking for _fseeki64
-- Looking for _fseeki64 - found
```
And a failed build:
```
/Users/hubstaff/Developer/hubstaff/ios/hubstaff-core/build/__third_party__/curl/libcurl/lib/formdata.c:797:10: error: call to undeclared function '_fseeki64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  797 |   return _fseeki64(stream, (__int64)offset, whence);
      |          ^
/Users/hubstaff/Developer/hubstaff/ios/hubstaff-core/build/__third_party__/curl/libcurl/lib/formdata.c:797:29: error: use of undeclared identifier '__int64'
  797 |   return _fseeki64(stream, (__int64)offset, whence);
      |                             ^
/Users/hubstaff/Developer/hubstaff/ios/hubstaff-core/build/__third_party__/curl/libcurl/lib/formdata.c:794:52: warning: unused parameter 'offset' [-Wunused-parameter]
  794 | static int fseeko_wrapper(void *stream, curl_off_t offset, int whence)
      |                                                    ^
1 warning and 2 errors generated.
```

While reverting the `CMakeLists.txt` back to using:
```
check_symbol_exists("_fseeki64"       "${CURL_INCLUDES};stdio.h" HAVE__FSEEKI64)
```
Yields:
```
-- Looking for _fseeki64
-- Looking for _fseeki64 - not found
```
And a successful build.

### I expected the following

For `HAVE__FSEEKI64` to be correctly detected as `0` rather than `1` when the symbol is unavailable during build time.

### curl/libcurl version

curl-8_11_0

### operating system

Cross-compiling for iPhoneOS18.1.sdk from macOS 15.0.1 (24A348).

**Comment by vszakats** [comment]
Thanks for your report.

Would you mind posting the lines from `CMakeFiles/CMakeConfigureLog.yaml` where this detection is made?

Also if you could make a `./configure` build for iOS, it would be helpful to see if it's (mis)detected there.

**Comment by vszakats** [comment]
I figure it may be a more effective approach to just skip the detection 
altoghether. Patch proposal here: #15526.

Unless someone is aware that `_fseeki64()` is offered anywhere else
than Windows.

Also related:
- pririotizing it for Windows: aaacd02466f77d03b8fdc19e91a0a3ec72f4c38a #14678 f365d50013e7804f47d8060eb65dce04fd84426b
- cmake opt-in for Windows: 8e74c0729d0cace00a202fc6c33c1b35703e220a #11950
- opt-in Windows: aa6c94c5bf4f5caa31c0213d9cd7058c29a9b30b #11944
- initial support: 9c7165e96a3a9a2d0b7059c87c699b5ca8cdae93 #11918

**Comment by vszakats** [comment]
In the meantime for anyone bumping into this issue, the workaround is passing `-DHAVE__FSEEKI64=OFF` to the cmake command-line.
