### PR TITLE
darwinssl: fixed regression causing compilation error

### PR DESCRIPTION
**Pull request by markovicpp**
Regression was introduced in 6448f98c1857de521fb2dd3f9d4e5659845b5474

### CODE REVIEW

**Comment by jay** [comment]
Thanks
