### ISSUE TITLE
Can't make on RHEL 7.3

### ISSUE THREAD

**Issue by jkaster** [curl/curl#1519]
What's the proper way to fix this compilation error so I can install the latest libcurl on RHEL 7.3?

### I did this

I've been able to get the latest openssl, build, and install it. `OpenSSL 1.1.1-dev  xx XXX xxxx` is reported by `openssl version`. zlib 1.2.11 is being used. Latest curl is cloned/pulled from `https://github.com/curl/curl.git`. Here's the bash script fragment I'm using:

```CD=$(pwd)
CPPFLAGS="-I$CD/zlib -I$CD/openssl -I$CD/openssl/include" 
LDFLAGS="-L$CD/zlib -L$CD/openssl" 
LIBS="-ldl" 
cd curl
./buildconf
./configure --disable-shared --with-zlib --with-ssl
make
make install
```

Running the batch with sudo, `make` produces this:

```
  CC       libcurl_la-openssl.lo
vtls/openssl.c: In function 'Curl_ossl_seed':
vtls/openssl.c:279:5: error: implicit declaration of function 'RAND_egd' [-
Werror=implicit-function-declaration]
   int ret = RAND_egd(data->set.str[STRING_SSL_EGDSOCKET]?
   ^
cc1: some warnings being treated as errors
make[2]: *** [libcurl_la-openssl.lo] Error 1
make[2]: Leaving directory `/home/john/curl/lib'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/john/curl/lib'
make: *** [all-recursive] Error 1
```

If I use `sudo ./curl/tests/testcurl.pl`, I get:

```
  CC       curl-warnless.o
gmake[2]: *** No rule to make target `../lib/libcurl.la', needed by `curl'.  Stop.
gmake[2]: Leaving directory `/build-30305/src'
gmake[1]: [all] Error 2 (ignored)
gmake[1]: Leaving directory `/build-30305/src'
Making all in include
gmake[1]: Entering directory `/build-30305/include'
Making all in curl
gmake[2]: Entering directory `/build-30305/include/curl'
gmake  all-am
gmake[3]: Entering directory `/build-30305/include/curl'
gmake[3]: Leaving directory `/build-30305/include/curl'
gmake[2]: Leaving directory `/build-30305/include/curl'
gmake[2]: Entering directory `/build-30305/include'
gmake[2]: Nothing to be done for `all-am'.
gmake[2]: Leaving directory `/build-30305/include'
gmake[1]: Leaving directory `/build-30305/include'
gmake[1]: Entering directory `/build-30305'
gmake[1]: Nothing to be done for `all-am'.
gmake[1]: Leaving directory `/build-30305'
testcurl: libcurl was not created (libcurl.la)
testcurl: removing the build-30305 dir
testcurl: removing the buildlog-30305 file
testcurl: ENDING HERE
```
### I expected the following
`make` should work

### curl/libcurl version

This is for the version that's currently installed, which I'm trying to replace:
```curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.21 Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets 
```

### operating system
RHEL 7.3

**Comment by bagder** [comment]
`RAND_egd` doesn't exist in OpenSSL 1.1.1 so the fact that it tries to use that in the code implies configure detected the wrong libcurl version/install.

But your configure line is overly complicated and probably wrong. Don't set CPPFLAGS and LDFLAGS if you don't need to. Point out the correct prefix path with the configure options:

`./configure --disable-shared --with-zlib=$CD --with-ssl=$CD`

If this gets problems, the check your `config.log` and investigate the zlib and openssl detection checks and what might be wrong there.

**Comment by jkaster** [comment]
I'm new to diagnosing the `config.log` so I'm continuing to look at it. It looks like my "successful" update of OpenSSL by downloading and rebuilding it missed some settings.

```configure:22563: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers  -I/home/john/zlib/include -I/home/john/openssl/include -I/home/john/openssl/include/openssl  -L/home/john/zlib/lib -L/home/john/openssl/lib conftest.c -lssl -lcrypto -lz  >&5
configure:22563: $? = 0
configure:22911: result: 1.0.1
configure:22919: checking for OpenSSL headers and library versions matching
configure:22929: result: no
configure:22932: WARNING: OpenSSL headers and library versions do not match.
```
Now I'm trying to figure out why `openssl version` tells me one thing and the build tells me another.

**Comment by kdudka** [comment]
On Tuesday, May 30, 2017 15:19:00 John Kaster wrote:
> 
>
> What's the proper way to fix this compilation error so I can install the
> latest libcurl on RHEL 7.3?

This sounds more like a question than a bug report.

> ### I did this
> 
> I've been able to get the latest openssl, build, and install it. `OpenSSL
> 1.1.1-dev  xx XXX xxxx` is reported by `openssl version`. zlib 1.2.11 is
> being used. Latest curl is cloned/pulled from
> `https://github.com/curl/curl.git`. Here's the bash script fragment I'm
> using:
> 
> ```CD=$(pwd)
> CPPFLAGS="-I$CD/zlib -I$CD/openssl -I$CD/openssl/include"
> LDFLAGS="-L$CD/zlib -L$CD/openssl"
> LIBS="-ldl"
> cd curl
> ./buildconf
> ./configure --disable-shared --with-zlib --with-ssl
> make
> make install
> ```
> 
> Running the batch with sudo, `make` produces this:

Do not run the whole build as a privileged user.  Only 'make install'
requires root privileges, assuming you install it system wide.

> ```
>   CC       libcurl_la-openssl.lo

Try running 'make' with V=1.  It will show you the exact command line
of compiler invocation.  You can check if the compiler flags reflect
your setup.

> vtls/openssl.c: In function 'Curl_ossl_seed':
> vtls/openssl.c:279:5: error: implicit declaration of function 'RAND_egd' [-
> Werror=implicit-function-declaration]
>    int ret = RAND_egd(data->set.str[STRING_SSL_EGDSOCKET]?
>    ^
> cc1: some warnings being treated as errors
> make[2]: *** [libcurl_la-openssl.lo] Error 1
> make[2]: Leaving directory `/home/john/curl/lib'
> make[1]: *** [all] Error 2
> make[1]: Leaving directory `/home/john/curl/lib'
> make: *** [all-recursive] Error 1
> ```
> ### I expected the following
> `make` should work
> 
> ### curl/libcurl version
> 
> This is for the version that's currently installed, which I'm trying to
> replace: ```curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.21
> Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3 Protocols: dict file ftp
> ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp
> smtps telnet tftp Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM
> NTLM_WB SSL libz unix-sockets ```

Your system libcurl uses NSS as the crypto/TLS backend.  Unless you have a 
good reason to use OpenSSL instead, I would suggest to just use the system
NSS libraries.  They get updated regularly and security issues are fixed as 
early as possible, unlike your local OpenSSL build, which will never be 
automatically updated even if a new security issue is discovered.

Kamil

> ### operating system
> RHEL 7.3

**Comment by jkaster** [comment]
Thanks for the response, Kamil. I did check for reports on known issues. I have completely failed to get curl to build on RHEL 7.3, starting from basic steps, all the way to trying to replace OpenSSL. So ... if RHEL 7.3 is supported by curl, I am at a loss how to build for it. I'm trying to do as much static linking of this utility as possible for deployment simplification reasons, and I'm trying to build for more than RHEL. I have it working for other Linux 64 and 32-bit distros, Mac, and Windows. RHEL is just completely blocking me, and no matter what I do I can't get these errors reported in config.log:

```configure:22567: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers           conftest.c -lssl -lcrypto -lssl -lcrypto   -lz  >&5
configure:22567: $? = 0
configure:22915: result: 1.0.1
configure:22923: checking for OpenSSL headers and library versions matching
configure:22933: result: no
configure:22936: WARNING: OpenSSL headers and library versions do not match.
configure:22969: checking for "/dev/urandom"
configure:22983: result: yes
configure:23008: checking for SRP_Calc_client_key in -lcrypto
configure:23030: gcc -o conftest -Werror-implicit-function-declaration -O2 -Wno-system-headers           conftest.c -lcrypto  -lssl -lcrypto -lssl -lcrypto   -lz  >&5
/tmp/ccBYtlbL.o: In function `main':
conftest.c:(.text.startup+0x7): undefined reference to `SRP_Calc_client_key'
collect2: error: ld returned 1 exit status
configure:23030: $? = 1
configure: failed program was:
| /* confdefs.h */
```
Going to a basic build script, I still can't get `make` to complete:
```libtool: compile:  gcc -DHAVE_CONFIG_H -I../include/curl -I../include -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_STATICLIB -DCURL_HIDDEN_SYMBOLS -fvisibility=hidden -Werror-implicit-function-declaration -O2 -Wno-system-headers -MT libcurl_la-openssl.lo -MD -MP -MF .deps/libcurl_la-openssl.Tpo -c vtls/openssl.c  -fPIC -DPIC -o libcurl_la-openssl.o
vtls/openssl.c: In function 'Curl_ossl_seed':
vtls/openssl.c:279:5: error: implicit declaration of function 'RAND_egd' [-Werror=implicit-function-declaration]
     int ret = RAND_egd(data->set.str[STRING_SSL_EGDSOCKET]?
```
Do you know if curl can be built with static libs for OpenSSL on RHEL? When building Curl this way works  on several other distros, including Mac, I tend to think it's a config issue on RHEL. I'm trying to resolve the OpenSSL version mismatch, but even explicitly replacing the symbolic links and getting the right result from `openssl version` isn't resolving the problem.

FTR, this is what I've done to try to resolve the OpenSSL version detection issue:
```cp /usr/local/lib64/lib*.a /usr/lib64/.
cp /usr/local/lib64/lib*.1.1 /usr/lib64/.
ln -sfn libcrypto.so.1.1 libcrypto.so
ln -sfn libssl.so.1.1 libssl.so
sudo ldconfig
```

**Comment by bagder** [comment]
(I will agree with @kdudka there's no sign at all that this is a bug)

> if RHEL 7.3 is supported by curl, I am at a loss how to build for it

curl doesn't really "support" distros, but you can build curl on basically any unix or linux, and RHEL 7.3 is certainly no exception. As long as you have the necessary prerequisites installed, which you seem to have.

> Do you know if curl can be built with static libs for OpenSSL on RHEL?

I'm convinced you can. But building with static openssl libs is not what the configure script is optmized for, and in fact you're sort of expected to sort it out yourself if you intend to take the narrow route. static  is complicated.

The keys to your build problem are all in your config.log, as it should show exactly what include and linker paths it used to detect openssl and then used when it run its test program to verify that it works and what functions that are present etc.

> Going to a basic build script, I still can't get make to complete

... since the `RAND_egd` issue means that configure found a working such function, which in turn means that it didn't find openssl 1.1.0 since that function is gone there. But when make runs, it seems to use that newer library so then it *doesn't* find the RAND_egd function and you get that warning.

> FTR, this is what I've done to try to resolve the OpenSSL version detection issue

Yikes, don't do that! You're ruining your system libcurls and that will probably cause havoc for apps in your system that use libcurl. It is **much** better if you just install your custom build in a custom location and then pick and chose when to use which version.

**Comment by jkaster** [comment]
Thanks for your patience and feedback. I'll go back to the beginning and start over. This all started very simply with being unable to `make` curl on RHEL ... all the mess came after the initial efforts failed.

**Comment by jkaster** [comment]
After starting completely over from scratch, I was able to get `curl` to build on RHEL 7.3 (I didn't install, as you advised). Whether or not I can get static linking to work for my C++ app, it's not curl's fault. Thanks again for your patience and answers. Glad it's my fault and not a bug :)
