### ISSUE TITLE
Cannot build on macOS 10.14 for iOS

### ISSUE THREAD

**Issue by olbrichj** [curl/curl#3189]
When trying to crosscompile for iOS I get this error:
url.c:55:2: error: "We can't compile without socket() support!"

This started after updating on Mojave (10.14) and Xcode 10. The problem exists on multiple machines. It persists after reinstalling the command line tools.

### I did this
checkout curl
./buildconf
export CC="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
export IPHONEOS_DEPLOYMENT_TARGET="9"
export CFLAGS="-arch arm64 -pipe -Os -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=9 -fembed-bitcode -Werror=partial-availability"
        export LDFLAGS="-arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
./configure     --host="arm-apple-darwin" \
                        --with-darwinssl \
                        --enable-static \
                        --disable-shared \
                        --enable-threaded-resolver \
                        --disable-verbose \
                        --enable-ipv6
make

### I expected the following
successful compile

### operating system
macOS 10.4

### config.log
How can I attach the config.log?

One part in the config.log I found interesting:

```
Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=9 -fembed-bitcode -Werror=partial-availability -Qunused-arguments -Werror=partial-availability   conftest.c >&5
conftest.c:86:10: fatal error: 'socket.h' file not found
#include <socket.h>
         ^~~~~~~~~~
1 error generated.
```

As far as I can see it finds sys/socket.h but not socket.h

**Comment by MarcelRaad** [comment]
Hi Jan!

> How can I attach the config.log?

Just click on the link for attaching files at the bottom of the comment form.

**Comment by nickzman** [comment]
Every time I've seen this happen, it's because the command line tools installation got mangled somehow. Try forcing a reinstall of the command line tools by running "xcode-select --install" and then try running configure/make again.

**Comment by olbrichj** [comment]
I've deleted /Library/Developer/CommandLineTools and reinstalled the command line tools. No change.

@MarcelRaad didn't see that one. attached the file.
[config.log](https://github.com/curl/curl/files/2528485/config.log)

**Comment by MarcelRaad** [comment]
I guess the relevant part is this:
```
configure:37684: checking if socket can be linked
configure:37705: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -o conftest -arch arm64 -pipe -Os -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=9 -fembed-bitcode -Werror=partial-availability -Qunused-arguments -Werror=partial-availability   -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk  -framework CoreFoundation -framework Security conftest.c -lz  >&5
configure:37705: $? = 0
configure:37707: result: yes
configure:37722: checking if socket is prototyped
conftest.c:180:12: fatal error: 'sys/types.h' file not found
#  include <sys/types.h>
            ^~~~~~~~~~~~~
1 error generated.
configure:37741: result: no
configure:37802: checking if socket might be used
configure:37817: result: no
```

But:
```
configure:10835: checking for sys/types.h
configure:10835: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -arch arm64 -pipe -Os -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=9 -fembed-bitcode -Werror=partial-availability  conftest.c >&5
configure:10835: $? = 0
configure:10835: result: yes
```

**Comment by olbrichj** [comment]
It's not reproducable on macOS 10.13.6 and Xcode10. So it seems to be a Mojave problem.

**Comment by olbrichj** [comment]
As far as I can see configure sets HAVE_SOCKET which is required for url.c. Furthermore it seems to requires a non_blocking function to be selected in nonblock.c. I've used the macOS define "HAVE_FCNTL_O_NONBLOCK".

Adding:
```
#define HAVE_SOCKET  1
#define HAVE_FCNTL_O_NONBLOCK 1
```
to the curl_config.h seems to work. I just can't figure out, why configure doesn't add these settings correctly. 

Sadly I have no clue about auto tools. Maybe someone can give me a pointer, where the HAVE_SOCKET is being set, and what the requirements are.

**Comment by bagder** [comment]
The problem is what @MarcelRaad pointed out. configure tries to compile and link a test program that uses socket(). In that test program, it uses `#include <sys/types.h>` but that include fails. The command line used to build that test program is in your `config.log` and looks like:

~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -o conftest -arch arm64 -pipe -Os -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=9 -fembed-bitcode -Werror=partial-availability -Qunused-arguments -Werror=partial-availability   -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk  -framework CoreFoundation -framework Security conftest.c -lz  >&5

conftest.c:180:12: fatal error: 'sys/types.h' file not found
#  include <sys/types.h>
           ^~~~~~~~~~~~~
1 error generated.
~~~
You should try that command line on your own test program using that include file and you will most likely get the same error. That error is the problem.

**Comment by ecnepsnai** [comment]
Starting with macOS Mojave headers are no longer stored in `/usr/include`

> The command line tools will search the SDK for system headers by default. However, some software may fail to build correctly against the SDK and require macOS headers to be installed in the base system under /usr/include. If you are the maintainer of such software, we encourage you to update your project to work with the SDK or file a bug report for issues that are preventing you from doing so. 

https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes?language=objc

**Comment by ecnepsnai** [comment]
You can work-around this issue in the meantime by installing:

> /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

Which is included with the command line tools for macOS Mojave. If that file is missing, you can try an `xcode-select --install` before installing that package.

I verified that I was able to compile on macOS Mojave after performing the workaround.

**Comment by nickzman** [comment]
My Mac is running macOS 10.14.1, and despite the lack of a /usr/include directory, I was able to configure and compile the latest code with no problems. So I don't think this is a widespread problem, and I do wonder if maybe your xcode-select directory was pointing to the incorrect place. You can see for yourself by running "xcode-select -p"; by default, it's "/Applications/Xcode.app/Contents/Developer", which is where the App Store places Xcode when you download it from there.

**Comment by olbrichj** [comment]
@bagder I've tried adding #include <sys/types.h> to my testprogram already, which worked fine.

@nickzman At the moment I have at least 8 different machines on Mojave having this problem. Mostly iMacs but also a brand new MacBook pro, which didn't have any prior configuration other than installing command line tools, brew and autotools. I can't check before Monday but afaik they are all on 10.14 and not yet updated. Maybe the update changed something for it to work again.

@ecnepsnai I'll try that as soon as I am back at work (Monday). Thanks :)

**Comment by bagder** [comment]
>  I've tried adding #include <sys/types.h> to my testprogram already, which worked fine. 

You built successfully with the exact same command line that I [showed](https://github.com/curl/curl/issues/3189#issuecomment-434860405) ?

**Comment by olbrichj** [comment]
I think so. Will check on monday (and also as mentioned retry). The result will be posted here :)

**Comment by olbrichj** [comment]
@bagder 
My testfile compiles with your command. Maybe there is something wrong with it?

```
#include <sys/types.h>
int main() {
	return 0;
}
```

Next up, updating to 14.1 and testing if that changes something, before I install the headers provided by the command line tools.

**Comment by olbrichj** [comment]
Okay the update to 14.1 includes a command line tools update. Not sure if this command line tool update or the system update fixes the problem, but now curl compiles (without the above extra header installation)

**Comment by bagder** [comment]
So, does this mean this case is closed now?

**Comment by bagder** [comment]
From my POV this issue has not proven to be a generic "build curl with macos 14.0"-issue since others have failed to reproduce it, so I have not found a strong enough reason to document any work-arounds.

Am I wrong?

**Comment by danielgustafsson** [comment]
> On 7 Nov 2018, at 13:32, Daniel Stenberg <notifications@github.com> wrote:
> 
> From my POV this issue has not proven to be a generic "build curl with macos 14.0"-issue since others have failed to reproduce it, so I have not found a strong enough reason to document any work-arounds.
> 
> Am I wrong?

While I haven’t tried to repro this (I’m stll in 10.13), I would prefer to await more reports before amending the documentation. If we documented similar issues for every OS that curl builds on we will soon have an overwhelming amount of documentation which is hard to maintain.

**Comment by olbrichj** [comment]
So it seems like, if you update directly to 14.1 without command line tools installed, it won't compile without the headers, resulting in the above compile break.
If you have them installed, they will be updated and the headers seem to be installed too, resulting in a working build.

**Comment by manuyavuz-pointr** [comment]
Hi all,

I just reproduced this issue. I updated to macOS Mojave recently, and I might get 10.14.1 directly, but not sure. However, I'm sure that I had command line tools installed when OS was High Sierra (10.13).

Now curl build fails with the same error above.

And I can confirm that @ecnepsnai's solution fixes the issue.

> You can work-around this issue in the meantime by installing:
> 
> > /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
> 
> Which is included with the command line tools for macOS Mojave. If that file is missing, you can try an `xcode-select --install` before installing that package.
> 
> I verified that I was able to compile on macOS Mojave for iOS after performing the workaround.

**Comment by bagder** [comment]
Since this is a build problem with associated fixes that don't involve curl at all, we can safely close this bug report.

**Comment by iousin** [comment]
Hi, 
Just for information, I had Xcode 9.4.1 on High Sierra 10.13, upgraded to mojave 10.14 with XCode 10, curl build stated failing with the same error mentioned in this issue. 
Downgraded xcode to 9.4.1, didn't help, removed commandline tools and installed again still didn't help. After that installed the following package and curl builds now. 
> /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg

Thanks.
