### ISSUE TITLE
undefined reference for zlib symbols when building with static dependencies and BUILD_SHARED_LIBS=OFF

### ISSUE THREAD

**Issue by micahsnyder** [curl/curl#10832]
### I did this

We build libcurl and all our other dependencies as static libraries.  Our build script for libcurl also builds the curl program, which in retrospect we don't need.  Anyhow, it runs this for our static build:
```
cmake .. \
  -D CMAKE_BUILD_TYPE=Release \
  -D CMAKE_POSITION_INDEPENDENT_CODE=ON \
  -D CURL_USE_OPENSSL=ON \
  -D OPENSSL_INCLUDE_DIR="/home/micah/.mussels/install/host-static/include" \
  -D OPENSSL_LIBRARIES="/home/micah/.mussels/install/host-static/lib" \
  -D OPENSSL_CRYPTO_LIBRARY="/home/micah/.mussels/install/host-static/lib/libcrypto.a" \
  -D OPENSSL_SSL_LIBRARY="/home/micah/.mussels/install/host-static/lib/libssl.a" \
  -D ZLIB_INCLUDE_DIR="/home/micah/.mussels/install/host-static/include" \
  -D ZLIB_LIBRARY_RELEASE="/home/micah/.mussels/install/host-static/lib/libz.a" \
  -D LIBSSH2_INCLUDE_DIR="/home/micah/.mussels/install/host-static/include" \
  -D LIBSSH2_LIBRARY="/home/micah/.mussels/install/host-static/lib/libssh2.a" \
  -D USE_NGHTTP2=ON \
  -D NGHTTP2_INCLUDE_DIR="/home/micah/.mussels/install/host-static/include" \
  -D NGHTTP2_LIBRARY="/home/micah/.mussels/install/host-static/lib/libnghttp2.a" \
  -D CMAKE_INSTALL_PREFIX="/home/micah/.mussels/install/host-static" \
  -D BUILD_SHARED_LIBS=OFF \
  -D CMAKE_INSTALL_LIBDIR=lib
```

This worked fine with curl-7.87.0, but failed when we updated to curl-8.0.1 with this:
```
❯ make
[ 76%] Built target libcurl
[ 76%] Linking C executable curl
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `zlib_stateful_compress_block':
c_zlib.c:(.text+0xba): undefined reference to `deflate'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `zlib_stateful_finish':
c_zlib.c:(.text+0xf6): undefined reference to `deflateEnd'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `zlib_stateful_init':
c_zlib.c:(.text+0x230): undefined reference to `deflateInit_'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `bio_zlib_ctrl':
c_zlib.c:(.text+0x394): undefined reference to `deflate'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `bio_zlib_write':
c_zlib.c:(.text+0x73a): undefined reference to `deflate'
/usr/bin/ld: c_zlib.c:(.text+0x85b): undefined reference to `deflateInit_'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `bio_zlib_free':
c_zlib.c:(.text+0xb07): undefined reference to `deflateEnd'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libssh2.a(comp.c.o): in function `comp_method_zlib_dtor':
comp.c:(.text+0xa1): undefined reference to `deflateEnd'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libssh2.a(comp.c.o): in function `comp_method_zlib_comp':
comp.c:(.text+0x272): undefined reference to `deflate'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libssh2.a(comp.c.o): in function `comp_method_zlib_init':
comp.c:(.text+0x355): undefined reference to `deflateInit_'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/curl.dir/build.make:784: src/curl] Error 1
make[1]: *** [CMakeFiles/Makefile2:541: src/CMakeFiles/curl.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Additional info, we're building with a tool called Mussels that I made to automate our dependency builds for linux/mac/windows/freebsd. So this came up in https://github.com/Cisco-Talos/clamav-mussels-cookbook/pull/32 where these are the full instructions used for that "host-static" build that failed: https://github.com/Cisco-Talos/clamav-mussels-cookbook/blob/157d31d952a832403895254220f3847a27fa0c61/recipes/libcurl-7.yaml#L150-L170

### I expected the following

I expected the build to succeed ;-).  Seems like the curl application is no longer being linked with `ZLIB::ZLIB` in 8.0.1 in this particular situation. 

### curl/libcurl version

8.0.1

### operating system

`Linux DESKTOP-N3L21K2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jay** [comment]
zlib check was moved in ebef55a6 so the library order may be different. Try running `make VERBOSE=1` to get more info.

**Comment by vszakats** [comment]
It's possible. Moving ZLIB detection was the reason I waited merging this. CI didn't catch anything, and my local (curl-for-win) tests cannot catch this either because of [passing](https://github.com/curl/curl-for-win/blob/7b9d0ae2bc280537d66ce6e3334e1dd59052d2bf/curl-cmake.sh#L71-L77) `-Wl,--start-group` to the linker, due to pre-existing issues of this kind. This hack is only necessary for `ld`. `lld` (and `link.exe`) are not sensitive to lib order.

Just re-tested it, and without the hack, build fails early while detecting QUIC in quictls. This quictls build doesn't use ZLIB. According to `CMakeFiles/CMakeConfigureLog.yaml` \[1\], it breaks due to missing `winsock` symbols, despite passing `-lws2_32` as a custom flag (or even from within `CMakeLists.txt`, if added around `-lbcrypt` and others) for this detection to succeed. It ends up at the "wrong" position for `ld`.

I couldn't figure how to control lib order with CMake, but it surely would be nice to fix this class of issues.

\[1\]:
```
/usr/local/bin/x86_64-w64-mingw32-gcc  -m64  -fno-ident -D_UCRT  -DHAVE_OPENSSL_SRP -DUSE_TLS_SRP 
  -DHAVE_SSL_SET0_WBIO -DHAS_ALPN -DNGHTTP2_STATICLIB -DNGHTTP3_STATICLIB
  -DNGTCP2_STATICLIB -DUSE_GSASL -I.../gsasl/x64-ucrt/usr/include -DUSE_MANUAL=1 -m64  
  -specs=.../gcc-specs-ucrt -static-libgcc  -lucrt -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused 
  -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wfloat-equal 
  -Wsign-compare -Wundef -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wstrict-aliasing=3 
  -Wcast-align -Wtype-limits -Wold-style-declaration -Wmissing-parameter-type -Wempty-body -Wclobbered 
  -Wignored-qualifiers -Wconversion -Wvla -Wdouble-promotion -Wenum-conversion -Warith-conversion 
  -Wno-long-long -Wno-multichar -Wno-format-nonliteral -Wno-sign-conversion -Wno-system-headers 
  -Wno-pedantic-ms-format  -Wl,--nxcompat -Wl,--dynamicbase -Wl,--high-entropy-va -Wl,-Bstatic 
  -L.../libssh2/x64-ucrt/usr/lib -L.../gsasl/x64-ucrt/usr/lib  -Wl,--pic-executable,-e,mainCRTStartup  
  -lwldap32 -lbcrypt -lbcrypt -lssh2 -lws2_32 -lgsasl  
  -Wl,--whole-archive CMakeFiles/cmTC_95f72.dir/objects.a -Wl,--no-whole-archive 
  -o cmTC_95f72.exe -Wl,--out-implib,libcmTC_95f72.dll.a 
  -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/cmTC_95f72.dir/linkLibs.rsp
/usr/local/Cellar/mingw-w64/10.0.0_5/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: .../quictls/x64-ucrt/usr/lib/libcrypto.a(libcrypto-lib-bio_addr.obj):bio_addr.c:(.text+0x26d): undefined reference to `WspiapiGetNameInfo'
/usr/local/Cellar/mingw-w64/10.0.0_5/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: .../quictls/x64-ucrt/usr/lib/libcrypto.a(libcrypto-lib-bio_addr.obj):bio_addr.c:(.text+0x294): undefined reference to `gai_strerrorA'
/usr/local/Cellar/mingw-w64/10.0.0_5/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: .../quictls/x64-ucrt/usr/lib/libcrypto.a(libcrypto-lib-bio_addr.obj):bio_addr.c:(.text+0x2ca): undefined reference to `__imp_ntohs'
[...]
```

`linkLibs.rsp`:
```
".../quictls/x64-ucrt/usr/lib/libssl.a" ".../quictls/x64-ucrt/usr/lib/libcrypto.a" 
-lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 
```

**Comment by micahsnyder** [comment]
> zlib check was moved in [ebef55a](https://github.com/curl/curl/commit/ebef55a61df0094b9790710a42f63c48e7de3c13) so the library order may be different. Try running `make VERBOSE=1` to get more info.

Here's my make verbose log:
```
host-static/curl-8.0.1/build
❯ make VERBOSE=1
/usr/bin/cmake -S/home/micah/.mussels/cache/work/host-static/curl-8.0.1 -B/home/micah/.mussels/cache/work/host-static/curl-8.0.1/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/micah/.mussels/cache/work/host-static/curl-8.0.1/build/CMakeFiles /home/micah/.mussels/cache/work/host-static/curl-8.0.1/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/micah/.mussels/cache/work/host-static/curl-8.0.1/build'
make -f lib/CMakeFiles/libcurl.dir/build.make lib/CMakeFiles/libcurl.dir/depend
make[2]: Entering directory '/home/micah/.mussels/cache/work/host-static/curl-8.0.1/build'
cd /home/micah/.mussels/cache/work/host-static/curl-8.0.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/micah/.mussels/cache/work/host-static/curl-8.0.1 /home/micah/.mussels/cache/work/host-static/curl-8.0.1/lib /home/micah/.mussels/cache/work/host-static/curl-8.0.1/build /home/micah/.mussels/cache/work/host-static/curl-8.0.1/build/lib /home/micah/.mussels/cache/work/host-static/curl-8.0.1/build/lib/CMakeFiles/libcurl.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/micah/.mussels/cache/work/host-static/curl-8.0.1/build'
make -f lib/CMakeFiles/libcurl.dir/build.make lib/CMakeFiles/libcurl.dir/build
make[2]: Entering directory '/home/micah/.mussels/cache/work/host-static/curl-8.0.1/build'
make[2]: Nothing to be done for 'lib/CMakeFiles/libcurl.dir/build'.
make[2]: Leaving directory '/home/micah/.mussels/cache/work/host-static/curl-8.0.1/build'
[ 76%] Built target libcurl
make -f src/CMakeFiles/curl.dir/build.make src/CMakeFiles/curl.dir/depend
make[2]: Entering directory '/home/micah/.mussels/cache/work/host-static/curl-8.0.1/build'
cd /home/micah/.mussels/cache/work/host-static/curl-8.0.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/micah/.mussels/cache/work/host-static/curl-8.0.1 /home/micah/.mussels/cache/work/host-static/curl-8.0.1/src /home/micah/.mussels/cache/work/host-static/curl-8.0.1/build /home/micah/.mussels/cache/work/host-static/curl-8.0.1/build/src /home/micah/.mussels/cache/work/host-static/curl-8.0.1/build/src/CMakeFiles/curl.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/micah/.mussels/cache/work/host-static/curl-8.0.1/build'
make -f src/CMakeFiles/curl.dir/build.make src/CMakeFiles/curl.dir/build
make[2]: Entering directory '/home/micah/.mussels/cache/work/host-static/curl-8.0.1/build'
[ 76%] Linking C executable curl
cd /home/micah/.mussels/cache/work/host-static/curl-8.0.1/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/curl.dir/link.txt --verbose=1
/usr/bin/cc  -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wfloat-equal -Wsign-compare -Wundef -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wstrict-aliasing=3 -Wcast-align -Wtype-limits -Wold-style-declaration -Wmissing-parameter-type -Wempty-body -Wclobbered -Wignored-qualifiers -Wconversion -Wvla -Wdouble-promotion -Wno-long-long -Wno-multichar -Wno-format-nonliteral -Wno-sign-conversion -Wno-system-headers -O3 -DNDEBUG   CMakeFiles/curl.dir/slist_wc.c.o CMakeFiles/curl.dir/tool_binmode.c.o CMakeFiles/curl.dir/tool_bname.c.o CMakeFiles/curl.dir/tool_cb_dbg.c.o CMakeFiles/curl.dir/tool_cb_hdr.c.o CMakeFiles/curl.dir/tool_cb_prg.c.o CMakeFiles/curl.dir/tool_cb_rea.c.o CMakeFiles/curl.dir/tool_cb_see.c.o CMakeFiles/curl.dir/tool_cb_wrt.c.o CMakeFiles/curl.dir/tool_cfgable.c.o CMakeFiles/curl.dir/tool_dirhie.c.o CMakeFiles/curl.dir/tool_doswin.c.o CMakeFiles/curl.dir/tool_easysrc.c.o CMakeFiles/curl.dir/tool_filetime.c.o CMakeFiles/curl.dir/tool_findfile.c.o CMakeFiles/curl.dir/tool_formparse.c.o CMakeFiles/curl.dir/tool_getparam.c.o CMakeFiles/curl.dir/tool_getpass.c.o CMakeFiles/curl.dir/tool_help.c.o CMakeFiles/curl.dir/tool_helpers.c.o CMakeFiles/curl.dir/tool_hugehelp.c.o CMakeFiles/curl.dir/tool_libinfo.c.o CMakeFiles/curl.dir/tool_listhelp.c.o CMakeFiles/curl.dir/tool_main.c.o CMakeFiles/curl.dir/tool_msgs.c.o CMakeFiles/curl.dir/tool_operate.c.o CMakeFiles/curl.dir/tool_operhlp.c.o CMakeFiles/curl.dir/tool_paramhlp.c.o CMakeFiles/curl.dir/tool_parsecfg.c.o CMakeFiles/curl.dir/tool_progress.c.o CMakeFiles/curl.dir/tool_stderr.c.o CMakeFiles/curl.dir/tool_strdup.c.o CMakeFiles/curl.dir/tool_setopt.c.o CMakeFiles/curl.dir/tool_sleep.c.o CMakeFiles/curl.dir/tool_urlglob.c.o CMakeFiles/curl.dir/tool_util.c.o CMakeFiles/curl.dir/tool_vms.c.o CMakeFiles/curl.dir/tool_writeout.c.o CMakeFiles/curl.dir/tool_writeout_json.c.o CMakeFiles/curl.dir/tool_xattr.c.o CMakeFiles/curl.dir/__/lib/strtoofft.c.o CMakeFiles/curl.dir/__/lib/timediff.c.o CMakeFiles/curl.dir/__/lib/nonblock.c.o CMakeFiles/curl.dir/__/lib/warnless.c.o CMakeFiles/curl.dir/__/lib/curl_multibyte.c.o CMakeFiles/curl.dir/__/lib/version_win32.c.o CMakeFiles/curl.dir/__/lib/dynbuf.c.o  -o curl  ../lib/libcurl.a -lpthread /home/micah/.mussels/install/host-static/lib/libz.a /home/micah/.mussels/install/host-static/lib/libssl.a /home/micah/.mussels/install/host-static/lib/libcrypto.a /home/micah/.mussels/install/host-static/lib/libnghttp2.a /home/micah/.mussels/install/host-static/lib/libssh2.a -lpthread -ldl
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `zlib_stateful_compress_block':
c_zlib.c:(.text+0xba): undefined reference to `deflate'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `zlib_stateful_finish':
c_zlib.c:(.text+0xf6): undefined reference to `deflateEnd'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `zlib_stateful_init':
c_zlib.c:(.text+0x230): undefined reference to `deflateInit_'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `bio_zlib_ctrl':
c_zlib.c:(.text+0x394): undefined reference to `deflate'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `bio_zlib_write':
c_zlib.c:(.text+0x73a): undefined reference to `deflate'
/usr/bin/ld: c_zlib.c:(.text+0x85b): undefined reference to `deflateInit_'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libcrypto.a(c_zlib.o): in function `bio_zlib_free':
c_zlib.c:(.text+0xb07): undefined reference to `deflateEnd'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libssh2.a(comp.c.o): in function `comp_method_zlib_dtor':
comp.c:(.text+0xa1): undefined reference to `deflateEnd'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libssh2.a(comp.c.o): in function `comp_method_zlib_comp':
comp.c:(.text+0x272): undefined reference to `deflate'
/usr/bin/ld: /home/micah/.mussels/install/host-static/lib/libssh2.a(comp.c.o): in function `comp_method_zlib_init':
comp.c:(.text+0x355): undefined reference to `deflateInit_'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/curl.dir/build.make:784: src/curl] Error 1
make[2]: Leaving directory '/home/micah/.mussels/cache/work/host-static/curl-8.0.1/build'
make[1]: *** [CMakeFiles/Makefile2:541: src/CMakeFiles/curl.dir/all] Error 2
make[1]: Leaving directory '/home/micah/.mussels/cache/work/host-static/curl-8.0.1/build'
make: *** [Makefile:130: all] Error 2
```

**Comment by vszakats** [comment]
With moving ZLIB detection after TLS detection, this might be fixed (can't test it), but then there is different problem, where ZLIB lib cannot be added for HTTP/3 detection in a quictls/OpenSSL built with ZLIB support.

Perhaps a this crude patch can fix both? (though this might potentially introduce other issuess):
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0ddfce9af..8b75f01cd 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -492,9 +492,9 @@ if(CURL_USE_OPENSSL)
   # version of CMake.  This allows our dependents to get our dependencies
   # transitively.
   if(NOT CMAKE_VERSION VERSION_LESS 3.4)
-    list(APPEND CURL_LIBS OpenSSL::SSL OpenSSL::Crypto)
+    list(APPEND OpenSSL::SSL OpenSSL::Crypto CURL_LIBS)
   else()
-    list(APPEND CURL_LIBS ${OPENSSL_LIBRARIES})
+    list(APPEND ${OPENSSL_LIBRARIES} CURL_LIBS)
     include_directories(${OPENSSL_INCLUDE_DIR})
   endif()
```

**Comment by vszakats** [comment]
Does this patch fix it?: #10857

**Comment by micahsnyder** [comment]
> Does this patch fix it?: #10857

Sorry I didn't get a chance to test this on my side in time. Been a bit hectic this week for me.
