### PR TITLE
openssl: fix building with v3 `no-deprecated` + add CI test

### PR DESCRIPTION
**Pull request by vszakats**
- build quictls with `no-deprecated` in CI to have test coverage for
  this OpenSSL 3 configuration.

- don't call `OpenSSL_add_all_algorithms()`, `OpenSSL_add_all_digests()`.
  The caller code is meant for OpenSSL 3, while these two functions were
  only necessary before OpenSSL 1.1.0. They are missing from OpenSSL 3
  if built with option `no-deprecated`, causing build errors:
  ```
  vtls/openssl.c:4097:3: error: call to undeclared function 'OpenSSL_add_all_algorithms'; ISO C99 and later do not   support implicit function declarations [-Wimplicit-function-declaration]
  vtls/openssl.c:4098:3: error: call to undeclared function 'OpenSSL_add_all_digests'; ISO C99 and later do not   support implicit function declarations [-Wimplicit-function-declaration]
  ```
  Ref: https://ci.appveyor.com/project/curlorg/curl-for-win/builds/48587418?fullLog=true#L7667

  Regression from b6e6d4ff8f253c8b8055bab9d4d6a10f9be109f3 #12030
  Bug: https://github.com/curl/curl/issues/12380#issuecomment-1822944669

- vquic/curl_ngtcp2: fix using `SSL_get_peer_certificate` with
  `no-deprecated` quictls 3 builds.
  Do it by moving an existing solution for this from `vtls/openssl.c`
  to `vtls/openssl.h` and adjusting caller code.
  ```
  vquic/curl_ngtcp2.c:1950:19: error: implicit declaration of function 'SSL_get_peer_certificate'; did you mean   'SSL_get1_peer_certificate'? [-Wimplicit-function-declaration]
  ```
  Ref: https://github.com/curl/curl/actions/runs/6960723097/job/18940818625#step:24:1178

- curl_ntlm_core: fix `-Wunused-parameter`, `-Wunused-variable` and
  `-Wunused-function` when trying to build curl with NTLM enabled but
  without the necessary TLS backend (with DES) support.

Closes #12384

---

- curl_ntlm_core: allow NTLM with `no-deprecated` OpenSSL 3 builds.
  Though OpenSSL 3 deprecated the DES functions needed for the NTLM
  feature, its `no-deprecated` build option doesn't actually disable
  these DES functions. It means we can use them for NTLM even if
  `OPENSSL_NO_DEPRECATED_3_0` is set. Adjust our logic to allow it.
  This failed tests due to some types missing. Dropping this.
  https://github.com/curl/curl/actions/runs/6961417865/job/18942957524?pr=12384#step:24:132

### CODE REVIEW

**Comment by ajbozarth** [comment]
Thanks for the catch, I missed that those were deprecated when we added the version checks

**Comment by vszakats** [comment]
@ajbozarth: These calls seem redundant, but can you confirm their removal didn't break this feature?

**Review by ajbozarth — COMMENTED** [review]
I've checkout and run the code and it's still fully functional

LGTM (can't make this an approve cause of perms)

**Comment by vszakats** [comment]
Thank you @ajbozarth!
