### ISSUE TITLE
curl 8.3 build failing with OPENSSL 3 due to absence of DES functions

### ISSUE THREAD

**Issue by devdatt9129** [curl/curl#12380]
### I did this

I tried to configure and build curl 8.3 with openssl 3, but i am getting the following error
```
curl_ntlm_core.c:113:4: error: #error "Can't compile NTLM support without a crypto library with DES."
make: *** [libcurl_la-curl_ntlm_core.lo] Error 1
```

### curl/libcurl version

curl 8.3.0

### operating system

RHEL 6

**Comment by bagder** [comment]
It seems you have an OpenSSL build with DES support disabled(?), which is not what OpenSSL 3 does by default. Since NTLM support in curl needs DES, it fails to build.

I don't think we can make curl's configure adapt to every possible OpenSSL build combination. If you want to build curl to not use DES, I think you need to disable NTLM from your build.

**Comment by devdatt9129** [comment]
I built my openssl using this command, i havent specfied no-des anywhere
perl Configure --prefix=/usr/local/lib64 --openssldir=/usr/local/lib64 enable-fips no-shared -m64 -Wa,--noexecstack linux-x86_64 threads no-idea no-mdc2 no-dsa no-rc5 no-ssl3 enable-asm enable-camellia enable-seed enable-rfc3779 enable-cms --api=3.0.0 no-deprecated  

does this have anything to do with the error

**Comment by bagder** [comment]
I suspect maybe `no-deprecated` does it?

**Comment by devdatt9129** [comment]
Okay ill try removing it once
Also, will disabling ntlm have any effect in runtime on my solution?

**Comment by bagder** [comment]
>  Also, will disabling ntlm have any effect in runtime on my solution?

If you need to use NTLM sure, otherwise no.

**Comment by vszakats** [comment]
I've been making `no-deprecated` tests since yesterday and with curl-for-win settings `lib/curl_ntlm_core.c` [compiles fine](https://ci.appveyor.com/project/curlorg/curl-for-win/builds/48587418?fullLog=true#L7297). This source has protections to auto-disable with no DES or 3.0 deprecated functions. It seems this isn't enough for all build configs, but I wonder why.

On the other hand my build bumps into a different error:
```
../../lib/vtls/openssl.c:4097:3: error: call to undeclared function 'OpenSSL_add_all_algorithms'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  OpenSSL_add_all_algorithms();
  ^
../../lib/vtls/openssl.c:4098:3: error: call to undeclared function 'OpenSSL_add_all_digests'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  OpenSSL_add_all_digests();
  ^
2 errors generated.
```
https://ci.appveyor.com/project/curlorg/curl-for-win/builds/48587418?fullLog=true#L7667

This is a recent regression from b6e6d4ff8f253c8b8055bab9d4d6a10f9be109f3 #12030.

**Comment by vszakats** [comment]
Looking into this it looks like OpenSSL 3 _did_ deprecate DES functions,
but it doesn't disable them in `no-deprecated` builds. If confirmed, it
should probably work with NTLM unless specifically using `no-des` to 
build OpenSSL, but I haven't yet tested it.

/cc @MarcelRaad 

Windows curl-for-win builds above were not affected because NTLM
falls back to Windows crypto in such case.

**Comment by vszakats** [comment]
curl build behaviour is correct and even though OpenSSL 3 `no-deprecated` builds with _some_ DES stuff, it also disables some others that are necessary for NTLM.

**Comment by vszakats** [comment]
By enhancement I mean curl could offer the necessary weak DES API. I'm not sure how prevalent NTLM is in the wild, but it's no longer recommended by Microsoft since 2010, so the secure solution to fix this is to disable NTLM, because it relies on insecure crypto.

Anyhow if someone is interested in fixing this by adding the DES API, this is technically solvable whitin curl.

**Comment by jay** [comment]
Microsoft is deprecating NTLM(https://www.reddit.com/r/sysadmin/comments/181fmim/we_microsoft_are_deprecating_ntlm_and_want_to/)
