### PR TITLE
Update curl_ngtcp2.c and https://github.com/curl/curl/issues/11292

### PR DESCRIPTION
**Pull request by Karthikdasari0423**
it didnt remove all errors,but removed some errors

please fix below error also

Making all in lib
make[1]: Entering directory '/src/curl/lib'
make  all-am
make[2]: Entering directory '/src/curl/lib'
  CC       vquic/libcurl_la-curl_ngtcp2.lo
vquic/curl_ngtcp2.c: In function ‘quic_settings’:
vquic/curl_ngtcp2.c:353:6: error: ‘ngtcp2_settings’ has no member named ‘qlog_write’
  353 |     s->qlog_write = qlog_callback;
      |      ^~
vquic/curl_ngtcp2.c: In function ‘cb_h3_stop_sending’:
vquic/curl_ngtcp2.c:1233:8: error: too many arguments to function ‘ngtcp2_conn_shutdown_stream_read’
 1233 |   rv = ngtcp2_conn_shutdown_stream_read(ctx->qconn, 0, stream_id,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from vquic/curl_ngtcp2.c:28:
/var/local/ngtcp2/include/ngtcp2/ngtcp2.h:4374:19: note: declared here
 4374 | NGTCP2_EXTERN int ngtcp2_conn_shutdown_stream_read(ngtcp2_conn *conn,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vquic/curl_ngtcp2.c: In function ‘cb_h3_reset_stream’:
vquic/curl_ngtcp2.c:1252:8: error: too many arguments to function ‘ngtcp2_conn_shutdown_stream_write’
 1252 |   rv = ngtcp2_conn_shutdown_stream_write(ctx->qconn, 0, stream_id,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from vquic/curl_ngtcp2.c:28:
/var/local/ngtcp2/include/ngtcp2/ngtcp2.h:4353:19: note: declared here
 4353 | NGTCP2_EXTERN int ngtcp2_conn_shutdown_stream_write(ngtcp2_conn *conn,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vquic/curl_ngtcp2.c: At top level:
vquic/curl_ngtcp2.c:1277:3: warning: excess elements in struct initializer
 1277 |   NULL /* recv_settings */
      |   ^~~~
vquic/curl_ngtcp2.c:1277:3: note: (near initialization for ‘ngh3_callbacks’)

### CODE REVIEW

**Comment by bagder** [comment]
The current curl code works with ngtcp2  0.16.0 and nghttp3 0.12.0, and that is what our CI jobs verify. What are you fixing for here?

**Comment by Karthikdasari0423** [comment]
sorry @bagder 
my bad
will close it
