### ISSUE TITLE
Failing to build libcurl.a with latest Openssl 3.1.0 due to presence of deprecated functions

### ISSUE THREAD

**Issue by devdatt9129** [curl/curl#12078]
### I did this

building a service with the latest openssl 3.0 (libssl.a and libcrypto.a) with the appropriate flags passed. 

```
/curl/libcurl.a(libcurl_la-sha256.o): In function `my_sha256_init':
sha256.c:(.text+0x35): undefined reference to `EVP_MD_CTX_create'
sha256.c:(.text+0x6c): undefined reference to `EVP_MD_CTX_destroy'
lib/x64/curl/libcurl.a(libcurl_la-sha256.o): In function `my_sha256_final':
sha256.c:(.text+0x16): undefined reference to `EVP_MD_CTX_destroy'
/curl/libcurl.a(libcurl_la-openssl.o): In function `ossl_sha256sum':
openssl.c:(.text+0x1ba): undefined reference to `EVP_MD_CTX_create'
openssl.c:(.text+0x1e3): undefined reference to `EVP_MD_CTX_destroy'
openssl.c:(.text+0x22a): undefined reference to `EVP_MD_CTX_destroy'
/curl/libcurl.a(libcurl_la-openssl.o): In function `ossl_engines_list':
openssl.c:(.text+0x247): undefined reference to `ENGINE_get_first'
openssl.c:(.text+0x267): undefined reference to `ENGINE_get_next'
openssl.c:(.text+0x277): undefined reference to `ENGINE_get_id'
/curl/libcurl.a(libcurl_la-openssl.o): In function `ossl_set_engine_default':
openssl.c:(.text+0x2c6): undefined reference to `ENGINE_set_default'
openssl.c:(.text+0x2e8): undefined reference to `ENGINE_get_id'
openssl.c:(.text+0x310): undefined reference to `ENGINE_get_id'
/curl/libcurl.a(libcurl_la-openssl.o): In function `ossl_close_all':
openssl.c:(.text+0x351): undefined reference to `ENGINE_finish'
openssl.c:(.text+0x35d): undefined reference to `ENGINE_free'
/curl/libcurl.a(libcurl_la-openssl.o): In function `ossl_verifyhost':
openssl.c:(.text+0x1007): undefined reference to `sk_num'
openssl.c:(.text+0x1036): undefined reference to `sk_value'
openssl.c:(.text+0x1092): undefined reference to `ASN1_STRING_data'
openssl.c:(.text+0x1430): undefined reference to `ASN1_STRING_data'
/curl/libcurl.a(libcurl_la-openssl.o): In function `ossl_version':
openssl.c:(.text+0x1547): undefined reference to `SSLeay'
/curl/libcurl.a(libcurl_la-openssl.o): In function `ossl_cleanup':
openssl.c:(.text+0x1635): undefined reference to `EVP_cleanup'
openssl.c:(.text+0x163a): undefined reference to `ENGINE_cleanup'
openssl.c:(.text+0x163f): undefined reference to `ERR_free_strings'
openssl.c:(.text+0x1646): undefined reference to `ERR_remove_thread_state'
openssl.c:(.text+0x164b): undefined reference to `CONF_modules_free'
/curl/libcurl.a(libcurl_la-openssl.o): In function `ossl_init':
openssl.c:(.text+0x166a): undefined reference to `ENGINE_load_builtin_engines'
openssl.c:(.text+0x167d): undefined reference to `SSL_load_error_strings'
openssl.c:(.text+0x1682): undefined reference to `SSL_library_init'
openssl.c:(.text+0x168f): undefined reference to `OPENSSL_add_all_algorithms_noconf'
/curl/libcurl.a(libcurl_la-openssl.o): In function `Curl_ssl_setup_x509_store':
openssl.c:(.text+0x18a1): undefined reference to `sk_value'
openssl.c:(.text+0x18f7): undefined reference to `sk_num'
openssl.c:(.text+0x190d): undefined reference to `sk_pop_free'
openssl.c:(.text+0x1a43): undefined reference to `sk_pop_free'
/curl/libcurl.a(libcurl_la-openssl.o): In function `Curl_ossl_certchain':
openssl.c:(.text+0x1da0): undefined reference to `sk_num'
openssl.c:(.text+0x1e39): undefined reference to `sk_value'
openssl.c:(.text+0x20b6): undefined reference to `sk_num'
openssl.c:(.text+0x2113): undefined reference to `sk_num'
openssl.c:(.text+0x2123): undefined reference to `sk_value'
/curl/libcurl.a(libcurl_la-openssl.o): In function `servercert':
openssl.c:(.text+0x27ca): undefined reference to `SSL_get_peer_certificate'
openssl.c:(.text+0x2ed0): undefined reference to `sk_num'
openssl.c:(.text+0x2ee7): undefined reference to `sk_num'
openssl.c:(.text+0x2efd): undefined reference to `sk_num'
openssl.c:(.text+0x2f0e): undefined reference to `sk_value'
openssl.c:(.text+0x2f48): undefined reference to `sk_num'
openssl.c:(.text+0x2f5c): undefined reference to `sk_value'
openssl.c:(.text+0x3166): undefined reference to `SSL_get_peer_certificate'
openssl.c:(.text+0x319f): undefined reference to `sk_value'
openssl.c:(.text+0x31c1): undefined reference to `sk_num'
/curl/libcurl.a(libcurl_la-openssl.o): In function `ossl_set_engine':
openssl.c:(.text+0x3a20): undefined reference to `ENGINE_by_id'
openssl.c:(.text+0x3a3d): undefined reference to `ENGINE_finish'
openssl.c:(.text+0x3a49): undefined reference to `ENGINE_free'
openssl.c:(.text+0x3a5c): undefined reference to `ENGINE_init'
openssl.c:(.text+0x3a94): undefined reference to `ENGINE_free'
/curl/libcurl.a(libcurl_la-openssl.o): In function `cert_stuff':
openssl.c:(.text+0x3d5b): undefined reference to `ENGINE_ctrl'
openssl.c:(.text+0x3d89): undefined reference to `ENGINE_ctrl_cmd'
openssl.c:(.text+0x3fdb): undefined reference to `sk_pop_free'
openssl.c:(.text+0x418a): undefined reference to `ENGINE_load_private_key'
openssl.c:(.text+0x4581): undefined reference to `sk_num'
openssl.c:(.text+0x4596): undefined reference to `sk_pop'
openssl.c:(.text+0x4689): undefined reference to `sk_pop_free'
/curl/libcurl.a(libcurl_la-openssl.o): In function `ossl_connect_step1':
openssl.c:(.text+0x481c): undefined reference to `SSLv23_client_method'
/curl/libcurl.a(libcurl_la-openssl.o): In function `ossl_close_all':
openssl.c:(.text+0x370): undefined reference to `ERR_remove_thread_state'
collect2: ld returned 1 exit status
```

### I expected the following

No undefined referenced errors, successful build with Openssl 3.0

### curl/libcurl version

curl 8.3.0

### operating system

RHEL7

**Comment by jay** [comment]
Some of those are deprecated functions but one that stands out is EVP_MD_CTX_destroy because in OpenSSL 3.x that's a macro for EVP_MD_CTX_free, which means that if the right headers were in use you'd see undefined reference to EVP_MD_CTX_free. Run `make V=1` and see if it's pulling OpenSSL headers from where you expect, maybe it found older headers

**Comment by vszakats** [comment]
We also disable calls to `ENGINE_*` when using an OpenSSL built with `no-engine`. `no-engine` should automatically be set when building OpenSSL with `no-deprectated`. It's curious that they are referenced anyway. `make V=1` could help clearing that too.

**Comment by bagder** [comment]
@devdatt9129 You mention 3.1 and 3.0 intermittently. Which one is it?

I can build curl find with OpenSSL 3.0.x, 3.1.x and 3.2.x (their current git master) just fine. I think @jay is spot on and your build setup is somehow broken.

If it is not broken, then please show us how you build your OpenSSL for this to happen.

**Comment by bagder** [comment]
No response, I don't think this is a curl problem.
