### PR TITLE
GHA/windows: add WolfSSL to MSVC MultiSSL job

### PR DESCRIPTION
**Pull request by talregev**
Add WolfSSL to MSVC MultiSSL job

### CODE REVIEW

**Comment by talregev** [comment]
I added wolfssl to multissl job. Waiting for update vcpkg, that will update wolfssl version, then it can install alongside with openssl.

**Comment by vszakats** [comment]
Nice.

Though I'm still on the same opinion wrt to GnuTLS. It's build is fragile and its TLS support doesn't work, so I don't think we need it in CI.

**Comment by talregev** [comment]
The port of shiftmedia-libgnutls (GnuTLS) is stable. It had 2 bugs that was fix quickly, and now for long time it working.

When I added GnuTLS to vcpkg ci, we found many compilation bug, include in test, in multissl (that was refactor) and also in cmake that allow to improve also the GnuTLS in linux and other os. This is very good regression test. 

I am adding GnuTLS in the MultiSSL job, that mean that TLS support functionality is not tested here.

For TLS support, I notify the developer, even that I show him small example with curl cli to see the bug,
He still looking for small example only with GnuTLS. I don't have this knowledge to give him. This is handle in separate PR that I open that currently on draft.

**Comment by talregev** [comment]
I think compile the GnuTLS without the tls functionality help us solve bugs, include cmake, compilation and test.
I see you insist, and I respect your opinion. I added only the WolfSSL.
I am still waiting for vcpkg to update, then it will compile without any compilation errors.

**Comment by talregev** [comment]
@vszakats When compile with -DCMAKE_UNITY_BUILD=ON it create compilation error. Can you take a look?
I will revert the commit with `-DCMAKE_UNITY_BUILD=OFF`

**Comment by talregev** [comment]
Errors:

```
C:\vcpkg\installed\x64-windows\include\wolfssl\openssl\compat_types.h(56,32): error C2371: 'EVP_MD': redefinition; different basic types [D:\a\curl\curl\bld\lib\libcurl_object.vcxproj]
  (compiling source file 'CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c')
      C:\vcpkg\installed\x64-windows\include\openssl\types.h(112,26):
      see declaration of 'EVP_MD'
  
C:\vcpkg\installed\x64-windows\include\wolfssl\openssl\compat_types.h(57,32): error C2371: 'EVP_MD_CTX': redefinition; different basic types [D:\a\curl\curl\bld\lib\libcurl_object.vcxproj]
  (compiling source file 'CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c')
      C:\vcpkg\installed\x64-windows\include\openssl\types.h(113,[30](https://github.com/curl/curl/actions/runs/11869652589/job/33080215455?pr=15438#step:9:31)):
      see declaration of 'EVP_MD_CTX'
  
C:\vcpkg\installed\x64-windows\include\wolfssl\openssl\compat_types.h(58,[32](https://github.com/curl/curl/actions/runs/11869652589/job/33080215455?pr=15438#step:9:33)): error C2371: 'EVP_CIPHER': redefinition; different basic types [D:\a\curl\curl\bld\lib\libcurl_object.vcxproj]
  (compiling source file 'CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c')
      C:\vcpkg\installed\x64-windows\include\openssl\types.h(110,30):
      see declaration of 'EVP_CIPHER'
```

```

**Comment by vszakats** [comment]
Hm, but I guess these headers are supposed to be able to coexist within the same project? Why aren't they?
Wasn't this the point of fixing wolfSSL? If it's still defining OpenSSL symbols via its `compat_types.h` it seems coexisting is not yet possible. (Or only at the linker level?)

I suppose one what to fix this is to consistently prioritize wolfSSL headers/implementation over OpenSSL when they are used together, outside the vtls modules. It's just a blind guess because the warnings don't give a hint where to look. Also it's supposed to be how it's done already, but maybe some spots were missed?

Which wolfSSL version is this and how to build it for coexistence?

**Comment by talregev** [comment]
It compile with wolfssl 5.7.4.
Can we separate the MultiSSL job and compile it with `-DCMAKE_UNITY_BUILD=OFF`?

**Comment by vszakats** [comment]
> It compile with wolfssl 5.7.4. Can we separate the MultiSSL job and compile it with `-DCMAKE_UNITY_BUILD=OFF`? Or Compile only the schannel MultiSSL U with `-DCMAKE_UNITY_BUILD=OFF`.

Unity so far turned out to never be the root cause, but an indicator of other problems. Assuming this is the same, I'd prefer fixing the problem. A build exception would just keep haunting us I think.

**Comment by talregev** [comment]
@vszakats 
I reveted the `-DCMAKE_UNITY_BUILD=OFF`

**Comment by vszakats** [comment]
@talregev I could replicate the issues using vcpkg's wolfSSL options.

The problem is that wolfSSL hasn't release its "coexist" feature yet. When testing with wolfSSL master, most of the issues are fixed (needs `-DOPENSSL_COEXIST` to work), except these two:
```
In file included from curl/lib/vtls/wolfssl.c:72:
In file included from wolfssl.git/_pkg/include/wolfssl/openssl/ssl.h:37:
wolfssl.git/_pkg/include/wolfssl/ssl.h:224:39: error: typedef redefinition with different types ('struct WOLFSSL_ASN1_OTHERNAME' vs 'struct otherName_st')
typedef struct WOLFSSL_ASN1_OTHERNAME OTHERNAME;
                                      ^
/usr/local/opt/openssl@3/include/openssl/x509v3.h:160:3: note: previous definition is here
} OTHERNAME;
  ^
In file included from curl/lib/vtls/wolfssl.c:72:
In file included from wolfssl.git/_pkg/include/wolfssl/openssl/ssl.h:42:
In file included from wolfssl.git/_pkg/include/wolfssl/openssl/evp.h:43:
wolfssl.git/_pkg/include/wolfssl/openssl/md5.h:61:25: error: typedef redefinition with different types ('WOLFSSL_MD5_CTX' (aka 'struct WOLFSSL_MD5_CTX') vs 'struct MD5state_st')
typedef WOLFSSL_MD5_CTX MD5_CTX;
                        ^
/usr/local/opt/openssl@3/include/openssl/md5.h:46:3: note: previous definition is here
} MD5_CTX;
  ^
2 errors generated.
```

In the meantime here's a patch for curl issues I've found so far: #15596

**Comment by bagder** [comment]
> except these two:

But they are due to curl's unity build are they not? I've been able to build curl just fine with wolfSSL + OpenSSL in a non-unity build.

**Comment by vszakats** [comment]
> > except these two:
> 
> But they are due to curl's unity build are they not? I've been able to build curl just fine with wolfSSL + OpenSSL in a non-unity build.

They are revealed by unity builds, but it's nevertheless a wolfSSL issue.
The "coexist" feature addressed all similar issues in the recent master,
which tells the goal was to avoid all compile-time symbol collisions.
Allowing to use OpenSSL and wolfSSL headers from the same .c source
file.

`OTHERNAME` and `MD5_CTX` were missed for some reason, and are
still colliding.

(Unless these two are special, but I cannot readily see why would they.)

**Comment by vszakats** [comment]
I've updated #15596 and now unity builds work as well, but it requires https://github.com/wolfSSL/wolfssl/commit/ff680994ba1295dbf8354ef3863928e7422b94f7 or later.

It contains a workaround for the two remaining collisions.

**Comment by talregev** [comment]
Can you also release wolfssl with the coexist feature? Then I will update it in vcpkg side.

It mean that I need to compile wolfssl with `-DOPENSSL_COEXIST`? (Can it also be default on wolfssl side?)

Thank you for your time and quick fix and hard work 💪🏻

**Comment by vszakats** [comment]
`-DOPENSSL_COEXIST` is macro to be set before including wolfSSL public headers.

In wolfSSL CMake there is also a `WOLFSSL_OPENSSL_COEXIST` (no effect in my build), a `WOLFSSL_OPENSSLCOEXIST` (breaks my build) and a TODO item for OpenSSL coexist. There is also an `--enable-opensslcoexist` for `./configure`. They are not synced, e.g. the latter also sets the macro, but not CMake. Hard to say where this will land.

Since wolfSSL latest stable release could already coexist at link-time, using a macro alone can work.

There is also a `NO_OLD_MD5_NAME` macro but it doesn't fix the pending issue because it's not applied to `openssl/md5.h`. This is a problem because `openssl/*` headers are still referenced from `wolfssl/*` headers.
But `OTHERNAME` is referenced from a native wolfSSL header, despite being a compatibility symbol.

(I'm not affiliated with wolfSSL, can't do releases.)

**Comment by vszakats** [comment]
> > -DOPENSSL_COEXIST is a macro to be set before including wolfSSL public headers.
> 
> This is done from curl side? or wolfssl side? If I will update wolfssl in vcpkg, I should know what to do.

It's on curl side. You can see it in the linked PR:
https://github.com/curl/curl/pull/15596/files#diff-d5391cab46f1c676396eaccc46ad04b7cff0302897908ac5478697225599f016R739

A release would be nice, but why to hurry? wolfSSL is obviously working on this.
I'm also hoping to have the opened issue addressed, so in curl we drop this workaround:
https://github.com/curl/curl/pull/15596/files#diff-95b5a6b3c748c28e68f06da950e20527969b2d64391c6e21c731b4823827b65cR35-R42

**Comment by talregev** [comment]
> > > -DOPENSSL_COEXIST is a macro to be set before including wolfSSL public headers.
> > 
> > 
> > This is done from curl side? or wolfssl side? If I will update wolfssl in vcpkg, I should know what to do.
> 
> It's on curl side. You can see it in the linked PR: https://github.com/curl/curl/pull/15596/files#diff-d5391cab46f1c676396eaccc46ad04b7cff0302897908ac5478697225599f016R739
> 
> A release would be nice, but why hurry? wolfSSL is obviously working on this. I'm also hoping to have the opened issue addressed, so in curl we can drop this workaround: https://github.com/curl/curl/pull/15596/files#diff-95b5a6b3c748c28e68f06da950e20527969b2d64391c6e21c731b4823827b65cR35-R42

Release is needed for update wolfssl in vcpkg side. vcpkg will not accept update from master.
We can wait for wolfssl fix, and maybe after that I hope they will release.
We can leave this PR open until everything will be updated. (wolfssl and vcpkg).

**Comment by vszakats** [comment]
> > A release would be nice, but why hurry? wolfSSL is obviously working on this. I'm also hoping to have the opened issue addressed, so in curl we can drop this workaround: https://github.com/curl/curl/pull/15596/files#diff-95b5a6b3c748c28e68f06da950e20527969b2d64391c6e21c731b4823827b65cR35-R42
> 
> Release is needed for update wolfssl in vcpkg side. vcpkg will not accept update from master. We can wait for wolfssl fix, and maybe after that I hope they will release. We can leave this PR open until everything will be updated. (wolfssl and vcpkg).

Absolutely!

Mildly related: I opened a PR to enable ECH for wolfSSL in vcpkg: https://github.com/microsoft/vcpkg/pull/42199 It'd allow to enable it for vcpkg wolfSSL curl jobs (possibly also in MultiSSL if #15596 lands). My vcpkg PR fails, no idea why.

**Comment by talregev** [comment]
> Mildly related: I opened a PR to enable ECH for wolfSSL in vcpkg: [microsoft/vcpkg#42199](https://github.com/microsoft/vcpkg/pull/42199) It'd allow to enable it for vcpkg wolfSSL curl jobs (possibly also in MultiSSL if #15596 lands). My vcpkg PR fails, no idea why.

In vcpkg, after you do commit, you should also do:
You should add in the vcpkg.json on wolfssl the `port-version: 1,`
then commit the change. After all changes are committed, you should do:
`./vcpkg x-add-version --all` and commit the results. It register the new version (new port version) of wolfssl.

**Comment by bagder** [comment]
> A release would be nice, but why hurry? wolfSSL is obviously working on this.

They are and they do releases frequently, I don't think we need to push extra. It's not like there's a line of users waiting and yelling at us for this feature.

**Comment by vszakats** [comment]
> `port-version: 1`

Thanks! Done. As for `./vcpkg x-add-version --all` I don't have vcpkg installed (also no resources to install it locally at this time.)

**Comment by talregev** [comment]
> > `port-version: 1`
> 
> Thanks! Done. As for `./vcpkg x-add-version --all` I don't have vcpkg installed (also no resources to install it locally at this time.)

It portable.
just run: ` ./bootstrap-vcpkg.sh` It will download the executable from the internet.

**Comment by vszakats** [comment]
> > > `port-version: 1`
> > 
> > 
> > Thanks! Done. As for `./vcpkg x-add-version --all` I don't have vcpkg installed (also no resources to install it locally at this time.)
> 
> It portable. just run: ` ./bootstrap-vcpkg.sh` It will download the executable from the internet.

I understand that. But it's not possible. I'd need to assess and understand this script and vcpkg, figure out how much space it needs, and most like start making room on my full disk.

**Comment by talregev** [comment]
> > > > `port-version: 1`
> > > 
> > > 
> > > Thanks! Done. As for `./vcpkg x-add-version --all` I don't have vcpkg installed (also no resources to install it locally at this time.)
> > 
> > 
> > It portable. just run: ` ./bootstrap-vcpkg.sh` It will download the executable from the internet.
> 
> I understand that. But it's not possible. I'd need to assess and understand this script and vcpkg, figure out how much space it needs, and most like start making room on my full disk.
> 
> edit: Closed that vcpkg PR, it seems to much to handle, there is also the legalese. Feel free to resubmit if you think it's useful. (Though curl ECH tests with other wolfSSL jobs since yesterday.)

I can make it for you.

**Comment by vszakats** [comment]
> > I understand that. But it's not possible. I'd need to assess and understand this script and vcpkg, figure out how much space it needs, and most like start making room on my full disk.
> > edit: Closed that vcpkg PR, it seems to much to handle, there is also the legalese. Feel free to resubmit if you think it's useful. (Though curl ECH tests with other wolfSSL jobs since yesterday.)
> 
> I can make it for you.

That's be very nice, thank you!

**Comment by talregev** [comment]
https://github.com/microsoft/vcpkg/pull/42202

**Comment by talregev** [comment]
@vszakats 
`      -DWOLFSSL_HPKE=yes`
Is it needed for ECH feature? 
android neon is not compile.
I will have time to investigate it later.

**Comment by vszakats** [comment]
> @vszakats ` -DWOLFSSL_HPKE=yes` Is it needed for ECH feature? android neon is not compile. I will have time to investigate it later.

Yes, the build fails without it:
```
CMake Error at CMakeLists.txt:2073 (message):
  ECH supported only with HPKE (WOLFSSL_HPKE)
```

**Comment by vszakats** [comment]
Took a look at Homebrew and they recently went with the "include everything" strategy, by using `--enable-all`. That includes ECH. Following Debian that's also building like this.

https://github.com/Homebrew/homebrew-core/commit/97d1ed6e6db63071853f0d0c5b3b02cb22983be9
https://github.com/Homebrew/homebrew-core/pull/191561
https://github.com/Homebrew/homebrew-core/blob/c21471b88254ec2747eb48fb75fe998de9315a0d/Formula/w/wolfssl.rb

**Comment by talregev** [comment]
@vszakats The PR is ready.

**Review by vszakats — APPROVED** [review]

**Comment by vszakats** [comment]
Nice, thank you @talregev! It is merged.

**Comment by talregev** [comment]
@vszakats Thank you 🎉
