### PR TITLE
hostip: guard PF_INET6 use

### PR DESCRIPTION
**Pull request by vszakats**
Some platforms (e.g. Amiga OS) do not have `PF_INET6`. Adjust the code for these.

```
hostip.c: In function 'fetch_addr':
hostip.c:308:12: error: 'PF_INET6' undeclared (first use in this function)
       pf = PF_INET6;
            ^~~~~~~~
```

Regression from 1902e8fc511078fb5e26fc2b907b4cce77e1240d

Closes #xxxx

### CODE REVIEW

**Comment by vszakats** [comment]
The initial patch fixes the compiler error, but the initial commit is most likely not the correct fix. Other variations may be using `ENABLE_IPV6` instead, or excluding a larger block of code in this case. This came while cross-compiling for Amiga OS.

**Review by bagder — APPROVED** [review]
