### ISSUE TITLE
OpenVMS DCL based build not working

### ISSUE THREAD

**Issue by fran-hermida** [curl/curl#4888]
### I did this

Run packages/vms/BUILD_VMS.COM

### I expected the following

curl/libcurl to be built

### curl/libcurl version

curl 7.68.0

### operating system

OpenVMS V8.3

### Comments

Results from BUILD_VMS.COM:

> $ @BUILD_VMS.COM
 %CREATE-I-EXISTS, USER$DISK:[xxxx.CURL.CURL-7_68_0.PACKAGES.VMS.IA64] already exists
%CURL-I-BLDHPLDAP, building with HP LDAP support
%CURL-I-BLDHPKERBEROS, building with HP KERBEROS support
CC opts: /define = (HAVE_CONFIG_H=1,_USE_STD_STAT,_LARGEFILE) /nolist/names=(shortened, as_is)/repository='exedir'/float=ieee/ieee_mode=denorm_results/debug/optimize  /object = USER$DISK:[xxxx.CURL.CURL-7_68_0.PACKAGES.VMS.
IA64]/nested_include_directory=none
%CURL-I-BLDHPSSL, building with HP SSL support
   OBJDIR = USER$DISK:[xxxx.CURL.CURL-7_68_0.PACKAGES.VMS.IA64]
   EXEDIR = USER$DISK:[xxxx.CURL.CURL-7_68_0.PACKAGES.VMS.IA64]
Generating curl custom config_vms.h
%CREATE-E-OPENOUT, error opening USER$DISK:[CURL.LIB]CONFIG_VMS.H; as output
-RMS-E-DNF, directory not found
-SYSTEM-W-NOSUCHFILE, no such file

Script generate_config_vms_h_curl.com is trying to create the file sys$disk:[curl.lib]config_vms.h, but it fails since we don't have this directory in our system.

```
$! Start the configuration file.
$! Need to do a create and then an append to make the file have the
$! typical file attributes of a VMS text file.
$create sys$disk:[curl.lib]config_vms.h
```

I understand build procedure should not rely on the existence of any folder in the system.

**Comment by bagder** [comment]
This script has remained untouched for years so this surprises me. @wb8tyw wrote most if it.

There aren't that many vms hackers in the curl project that I know of, so I'm fearing you might be a little bit on your own here... :disappointed:

**Comment by fran-hermida** [comment]
Thank you, that's what I supposed. I can modify the script (I'm fact, I did). But I am not confident enough to change @wb8tyw  build system in OpenVMS

**Comment by wb8tyw** [comment]
The script is expecting that you setup a concealed logical to point to a directory with either a curl tarball unpacked or the curl repository checked out where the base directory is "[curl]".

I always use concealed logical names, and search lists for doing builds, and that is documented in one of the readme or equivalent files in the VMS directory.

So if you have curl in user$disk:[myuser.curl] you would set up a concealed rooted logical name
define/job/trans=concealed prj_root user$disk:[myuser.]. 

Then prj_root:[curl.lib] will exist and you can set default to prj_root:[curl] and the build should work.

Before building the current cURL on OpenVMS, I would start with the kits at https://sourceforge.net/projects/vms-ports/files/axp0830/ .

These will build on the older OpenVMS 8.3 if you follow the directions in the release notes.
The full source is present in these kits.

The release notes should detail how to reproduce my build environment.

The current problem with building cURL on OpenVMS was that HPE has a bad OpenSSL 1.4 image that is missing a transfer vector for a routine that cURL needs, and while that routine can be added to the build as a separate file, a license conflict prevents it being present in the cURL git repository.

And then when the HPE kits for OpenSSL based on 1.0.x came out, while they made the kits available for hobbyists, they did not make the ECOs that the kits required available until last year.
As far as I know, those kits require OpenVMS 8.4, the last HPE release.

There is a Polar Home OpenSSL port for VMS, but it is not available as a shared image.

VMS Software Inc, the current owner of OpenVMS, is supplying a pre-built version of Curl somewhere on their web site.  It may or may not conflict with the packages that I have been building, and I do not know if the libcurl in it is backwards compatible with what I was kitting.
https://www.vmssoftware.com/

**Comment by wb8tyw** [comment]
I do plan to eventually get back to building cURL on VMS, but have a list of things that I need to get done first, so if someone wants to help with the stuff needed for cURL on VMS, they can e-mail me.
All the e-mail addresses in the VMS source for me should still work.

**Comment by fran-hermida** [comment]
> The script is expecting that you setup a concealed logical to point to a directory with either a curl tarball unpacked or the curl repository checked out where the base directory is "[curl]".
> 
> I always use concealed logical names, and search lists for doing builds, and that is documented in one of the readme or equivalent files in the VMS directory.
> 
> So if you have curl in user$disk:[myuser.curl] you would set up a concealed rooted logical name
> define/job/trans=concealed prj_root user$disk:[myuser.].
> 
> Then prj_root:[curl.lib] will exist and you can set default to prj_root:[curl] and the build should work.
> 

Thank you, following your steps, I got the build script to work. There are compilation errors, but  at least the script works. I will close the issue.

```
$ define /trans=concealed CURL$DISK DKA0:[TBC_USER.CSI_PLANOS.PACO.CURL.CURL-7_68_0.]
$ set def CURL$DISK:[CURL]
$ @[.packages.vms]build_vms.com
%CREATE-I-EXISTS, CURL$DISK:[CURL.PACKAGES.VMS.IA64] already exists
%CURL-I-BLDHPLDAP, building with HP LDAP support
%CURL-I-BLDHPKERBEROS, building with HP KERBEROS support
CC opts: /define = (HAVE_CONFIG_H=1,_USE_STD_STAT,_LARGEFILE) /nolist/names=(shortened, as_is)/repository='exedir'/float=ieee/ieee_mode=denorm_results/debug/optimize  /object = CURL$DISK:[CURL.PACKAGES.VMS.IA64]/nested_include_directo
ry=none
%CURL-I-BLDHPSSL, building with HP SSL support
   OBJDIR = CURL$DISK:[CURL.PACKAGES.VMS.IA64]
   EXEDIR = CURL$DISK:[CURL.PACKAGES.VMS.IA64]
CC (opts) CURL$DISK:[CURL.LIB]ALTSVC.C;1

#  include <mbedtls/md4.h>
...^
%CC-F-NOINCLFILEF, Cannot find file <mbedtls/md4.h> specified in #include directive.
at line number 683 in file CURL$DISK:[CURL.LIB]CURL_SETUP.H;1
```



> Before building the current cURL on OpenVMS, I would start with the kits at https://sourceforge.net/projects/vms-ports/files/axp0830/ .
> 
> These will build on the older OpenVMS 8.3 if you follow the directions in the release notes.
> The full source is present in these kits.
> 
> The release notes should detail how to reproduce my build environment.
> 

I've tried but I cannot extract the source code properly. 
Specifically file [curl.lib]curl_config^.h.in;1
Probably because I work on a ODS-2 volume


> The current problem with building cURL on OpenVMS was that HPE has a bad OpenSSL 1.4 image that is missing a transfer vector for a routine that cURL needs, and while that routine can be added to the build as a separate file, a license conflict prevents it being present in the cURL git repository.
> 
> And then when the HPE kits for OpenSSL based on 1.0.x came out, while they made the kits available for hobbyists, they did not make the ECOs that the kits required available until last year.
> As far as I know, those kits require OpenVMS 8.4, the last HPE release.
> 
> There is a Polar Home OpenSSL port for VMS, but it is not available as a shared image.
> 

I don't need SSL support at the moment, so I will try to build last cURL versión.

> VMS Software Inc, the current owner of OpenVMS, is supplying a pre-built version of Curl somewhere on their web site. It may or may not conflict with the packages that I have been building, and I do not know if the libcurl in it is backwards compatible with what I was kitting.
> https://www.vmssoftware.com/

I am also working with that version, however it targets V8.4
