### ISSUE TITLE
Linking static libcurl 8.17.0 on Windows

### ISSUE THREAD

**Issue by JackCarterSmith** [curl/curl#19516]
### I did this

Build a simple test program in C with the following command using MinGW 14.3.0-r3:
`gcc -DCURL_STATICLIB -o curl_test_get.exe curl_test_get.c -I "E:\JCS\CODING-Resources\curl-8.16.0_1-win64-mingw\include" -L "E:\JCS\CODING-Resources\curl-8.16.0_1-win64-mingw\lib" -Wl,-Bstatic -lcurl -lpsl -lbrotlidec -lbrotlicommon -lnghttp2 -lnghttp3 -lngtcp2 -lngtcp2_crypto_libressl -lssh2 -lssl -lcrypto -lz -lzstd -Wl,-Bdynamic -lws2_32 -lbcrypt -lWldap32 -liphlpapi -lnormaliz -lsecur32 -lcrypt32`

### I expected the following

Getting a statically linked .exe

### What I found

Trying to link on static libpsl.a fail with this result;
```
D:/COMPILERS/mingw64_14.3.0/bin/../lib/gcc/x86_64-w64-mingw32/14.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\JCS\CODING-Resources\curl-8.17.0_1-win64-mingw\lib\libpsl.a(psl.o):psl.c:(.text$psl_builtin_outdated[psl_builtin_outdated]+0x31): undefined reference to `stat64'
D:/COMPILERS/mingw64_14.3.0/bin/../lib/gcc/x86_64-w64-mingw32/14.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\JCS\CODING-Resources\curl-8.17.0_1-win64-mingw\lib\libpsl.a(psl.o):psl.c:(.text$psl_latest[psl_latest]+0x6d): undefined reference to `stat64'
D:/COMPILERS/mingw64_14.3.0/bin/../lib/gcc/x86_64-w64-mingw32/14.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: E:\JCS\CODING-Resources\curl-8.17.0_1-win64-mingw\lib\libpsl.a(psl.o):psl.c:(.text$psl_latest[psl_latest]+0xc7): undefined reference to `stat64'
```

This work with the 8.16.0 version of libcurl with the same build command.

### curl/libcurl version

libcurl 8.17.0

### operating system

Windows 10

**Comment by vszakats** [comment]
This toolchain looks like mingw-w64 with gcc 14.3.0. Do you also know
which mingw-w64 version it is?

I'm not fully understanding what happened in mingw-w64 13, but after
upgrading from 12 (via Debian stable bump), I had to patch the build to
link to stat64 again (by defining `_FILE_OFFSET_BITS=64` globally),
instead of an instrinsic not seen earlier: `stat64i32`. But, it seems this
`stat64` is not an import, but something local, for libpsl.a and libcrypto.a.
For libcurl.a, it's the expected `__imp__stat64`.

Maybe someone in the know in mingw-w64 can advise how to fix it?

References:
https://github.com/curl/curl-for-win/commit/21cdc44b1a06e75e2d18fd6795f0700a8448ad0f
https://github.com/curl/curl-for-win/commit/add9e2504184780818290c465d9fe906b2cdd92b
https://curl.se/mail/lib-2025-10/0007.html

In the meantime I suggest trying with a toolchain offering mingw-w64
13, or (probably) newer.

**Comment by JackCarterSmith** [comment]
It appears that this is version 12 of mingw-w64 indeed with GCC 14.3.0 from winlibs.

I should give it a try with GCC 15.2 which uses mingw-w64 13...
Maybe rebuilding only libpsl static lib with GCC 14/mingw-w64 12 can be an another backup solution.

I'm not sure: `stat64` is from `sys/stat.h`?

**Comment by vszakats** [comment]
It's from `sys/stat.h`, yes. It seems that POSIX `stat` is
redirected to an intrinsic in 13, in all configurations. (meaning
my fix attempt did not fix this after all.)

12 did it differently. I suspect a lot of history and nuances, but
in practice it broke lib interoperability between 12 and  13 for code
calling `stat` on Windows.

libcurl is not affected because it calls `_stati64` or `_stat` (or
their Unicode variants), and these go directly to the CRT.

If there is a way out of this via a mingw macro, I could not spot it. 
Changing mingw-64 may be late at this point. This leaves reporting
the issue to libpsl and LibreSSL to use the native, Windowsy
stat functions. Patching in curl-for-win doesn't seem practical
for a number of reasons.

In libpsl, the `stat` call is actually unused code when the PSL
database is embedded via `-DENABLE_BUILTIN`, in curl-for-win.
This makes it an option to mitigate by excluding the code from
this build configuration. And hope the other isn't pulled in from
libcrypo.a.

I might have missed other options though.

**Comment by vszakats** [comment]
I've cut 8.17.0_2, which would hopefully fix this.

Binaries at the usual place: https://curl.se/windows/
or here: https://ci.appveyor.com/project/curlorg/curl-for-win/builds/53074989/artifacts

Relevant fix commit:
https://github.com/curl/curl-for-win/commit/ac25fe442126199a63bdd61b9de02bf0838da622

Let us know how it works.

While investigating, I also found what I consider a security issue in libpsl,
when using its `ENABLE_BUILTIN` feature:
https://github.com/curl/curl-for-win/commit/27fe69e7256a57b5e90d2a371516b188e3d04f55
The feature is intentional, though how it works is unsafe IMO, and at best
unexpected, and accidental.

**Comment by JackCarterSmith** [comment]
I tried again the same command with the 8.17.0_2 version of libcurl and mingw GCC 14.3.0-r3 (mingw 12) and it works!

Thanks for the quick look/answer and the details, they'll be very useful.
I'll leave an issue report on libpsl about the `stat` support with mingw-w64. I agree that it is better to correct at "source project" if possible.

Sorry for the question, which may be off-topic: apart from using the curl-config command (I can't find it in the mingw package for Windows), how can I find out the list of dependencies -l for building with libcurl statically?
Currently, I have composed it by deduction/extraction from the DLL, just for testing, but it would be better to have something more precise.

**Comment by vszakats** [comment]
Thanks for your feedback, good to know it fixed! and for reporting to libpsl.

With curl-for-win the easiest way is to link all `.a` libs distributed in the
package. This leaves figuring out system libs, and I have no good
suggestion for that. Including `curl-config` may help despite it being
non-Windowsy, but it would require fixing it to exclude absolute libpaths
specific to the build machine, leading to more questions, to figure out
the necessary logic for cmake/autotools. (or perhaps configure the build
differently to work this around, which'd also be a non-trivial change.)

**Comment by dfandrich** [comment]
> Sorry for the question, which may be off-topic: apart from using the
> curl-config command (I can't find it in the mingw package for Windows), how can
> I find out the list of dependencies -l for building with libcurl statically?

They're also in the libcurl.pc file (Libs.private), if that's supplied in the package.

**Comment by vszakats** [comment]
`libcurl.pc` is not included. It has the same issue with `-L` absolute
paths baked in from the build machine. Also, it wasn't looking usable in 
this scenario (of a package with unspecified location on disk), unless
perhaps `.pc` files supported a relative `prefix=`.

**Comment by JackCarterSmith** [comment]
I was asking the question to know if there is any "official" method to get the libs list for building on Windows env. So if not, I'll do without it. 

> libcurl is not affected because it calls `_stati64` or `_stat` (or
> their Unicode variants), and these go directly to the CRT.

Did you have an exemple in libcurl source I can use to "update" the same way libpsl `stat()` call?

**Comment by vszakats** [comment]
> Did you have an exemple in libcurl source I can use to "update" the same way libpsl `stat()` call?

Yes, curl calls it from this place:
https://github.com/curl/curl/blob/ea2203c1aafb5f103b376a2b6a30965cb4d48163/lib/curlx/fopen.c#L313-L317

The matching struct is defined here:
https://github.com/curl/curl/blob/ea2203c1aafb5f103b376a2b6a30965cb4d48163/lib/curl_setup.h#L488-L495
