### ISSUE TITLE
build fails with OpenLDAP 2.5.4

### ISSUE THREAD

**Issue by bagder** [curl/curl#7004]
Hi all,

OpenLDAP has released 2.5.4 version and curl compiling fails... Any chance to get it adopted soon?
Regards.

_Originally posted by @3eka in https://github.com/curl/curl/discussions/7003_

**Comment by 3eka** [comment]
This is error:

```
  CC       libcurl_la-openldap.lo
openldap.c:83:17: error: conflicting types for 'ldap_connect'
   83 | static CURLcode ldap_connect(struct Curl_easy *data, bool *done);
      |                 ^~~~~~~~~~~~
In file included from openldap.c:39:
/pz/SFW/include/ldap.h:1554:1: note: previous declaration of 'ldap_connect' was here
 1554 | ldap_connect( LDAP *ld );
      | ^~~~~~~~~~~~
gmake[2]: *** [Makefile:2515: libcurl_la-openldap.lo] Error 1
```

PREFIX is where new OpenLDAP is installed (as well as OpenSSL)
` PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig     CPPFLAGS="-I${PREFIX}/include -D_POSIX_PTHREAD_SEMANTICS -D_XOPEN_SOURCE=600 -D_FILE_OFFSET_BITS=64 -D__EXTENSIONS__" CFLAGS="-m64 -march=native -std=c89 -std=c99"     LDFLAGS="-L${PREFIX}/lib -R${PREFIX}/lib" LIBS="-lstdc++"     ./configure --prefix=${PREFIX}     --enable-optimize     --enable-http     --enable-ftp     --enable-file     --enable-proxy     --enable-telnet     --enable-tftp     --enable-manual     --enable-libcurl-option     --enable-ipv6     --enable-threaded-resolver     --enable-crypto-auth     --enable-cookies     --with-libssh2     --with-gssapi=${PREFIX}     --with-ssl=${PREFIX}     --with-ca-fallback  --enable-ldap --enable-ldaps     --with-ca-bundle=/etc/openssl/ca-bundle.crt --with-ca-path=/etc/openssl/certs
`
OS is OpenIndiana (Illumos based), GCC 9 suite used. Same configure works and curl compiles fine with OpenLDAP 2.4.xx.

Regards.

**Comment by bagder** [comment]
Yeah, turns out we use `ldap_` prefixes on private functions in that source file and OpenLDAP has introduced a function that uses the exact same name as we use for a private function. The fix is to avoid that prefix for private functions.

**Comment by 3eka** [comment]
FYI: 
it compiles now (tested against git clone).
Many thanks
