### ISSUE TITLE
Unable to compile curl 7.84 for MAC(ARM64)

### ISSUE THREAD

**Issue by AshishDurgapal** [curl/curl#9908]
We are getting given below error while compiling curl with openssl 3.0.5

Undefined symbols for architecture arm64:
  "_CFRelease", referenced from:
      _Curl_resolv in libcurl.a(libcurl_la-hostip.o)
  "_SCDynamicStoreCopyProxies", referenced from:
      _Curl_resolv in libcurl.a(libcurl_la-hostip.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

CURL version : 7.84/7.86
Note*: Everything works fine with Curl 7.76

Machine (uname -a ) : **Darwin RMS-MAC11 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64**

Configure command which I am using : **./configure --host=arm-apple-macos11 --target=arm64-apple-macos11 CFLAGS="-arch arm64 -fPIC" CC="clang -arch arm64" --without-zlib  --with-ssl=/var/root/Ashish/openssl-3.0.5/ --disable-ldap --disable-ldaps LDFLAGS="-framework SystemConfiguration -framework CoreFoundation -framework** Security"

**Comment by bagder** [comment]
Sounds similar to #9806

**Comment by licxzyh** [comment]
I have the same problem, did you solve it

**Comment by AshishDurgapal** [comment]
I tried by adding systemconfiguration and corefoundation flag but still not working.

./configure --host=arm-apple-macos11 --target=arm64-apple-macos11 CFLAGS="-arch arm64 -fPIC" CC="/usr/bin/gcc" --without-zlib  --disable-ldap --disable-ldaps LDFLAGS="-arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk  -framework SystemConfiguration -framework CoreFoundation -framework Security" CPPFLAGS="-I.. -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk" --with-ssl=/var/root/Ashish/openssl-3.0.5/

Note*: Also tried with CC="clang" instead of gcc .

**Comment by uhei** [comment]
My observation:

Running `./configure --host=arm-apple-macos11 ...` results in the linker error.
Running `./configure --host=arm-apple-darwin ...` however compiles and linkes without any errors.

@AshishDurgapal Can you give it a try with `arm-apple-darwin`?

**Comment by aaspnas** [comment]
Building from source with newest openssl, without any additional configuration flags works for me on my M! Mac with latest OS. 

Can confirm behaviour reported by @uhei 

Does --host=arm-apple-macos11 need to work?

**Comment by jsoref** [comment]
I was using this (on macOS 12.6.1 / m1 = arm64) to test:
```sh
test() {
autoreconf -fi
./configure --host=arm-apple-macos11 --target=arm64-apple-darwin 'CFLAGS=-arch arm64 -fPIC' 'CC=clang -arch arm64' --without-zlib --with-ssl=/opt/homebrew/Cellar/openssl@3/3.0.7/ --disable-ldap --disable-ldaps 'LDFLAGS=-framework SystemConfiguration -framework CoreFoundation -framework Security' host_alias=arm-apple-macos11 target_alias=arm64-apple-darwin --with-brotli=/opt/homebrew/Cellar/brotli/1.0.9
make -s clean
make -s -j $(nproc )
}
```

```sh
$ git checkout 31f631a142d855f069242f3e0c643beec25d1b51
$ test
...
Undefined symbols for architecture arm64:
  "_SCDynamicStoreCopyProxies", referenced from:
      _Curl_resolv in libcurl.a(libcurl_la-hostip.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When I add `--enable-ares` to my flags, I'm able to build curl-7_84_0 w/o failures.

**Comment by licxzyh** [comment]
I has solved this problem
add this code

**Comment by licxzyh** [comment]
I has solved this problem
add this code:
   
 find_library(CoreFoundation_Library CoreFoundation)
 find_library(SystemConfiguration_Library SystemConfiguration)
    target_link_libraries(${libName} ${CoreFoundation_Library})
    target_link_libraries(${libName} ${SystemConfiguration_Library})

**Comment by ne1for23** [comment]
My observations:

By disecting the uname output, I see the OP is using macOS Big Sur (11.2.x) on an Intel Mac to produce an ARM64 binary.  The issue title should reflect this to aid those unfamiliar with [looking up](https://www.theiphonewiki.com/wiki/Kernel#macOS.2FOS_X) this MacOS information.

IMO, this environment should be updated prior to spending any serious troubleshooting time.  The latest version of macOS Big Sur is 11.7.1 and it contains important [security updates](https://support.apple.com/en-us/HT213493).
Doing relevant updates also includes updating to the latest compatible version of Xcode and launching it once via the GUI, allowing any elevated permission updates to be installed.  The latest version of Xcode is 14.1 and requires MacOS 12.5, so you may need to [download Xcode 13.2.1 manually](https://developer.apple.com/download/all/?q=xcode) from Apple's developer site as its the [last version supported by macOS Big Sur](https://developer.apple.com/support/xcode/).

Once fully up-to-date and if you continue to have issues, you may also need to manually install/re-install command line tools (especially if you've restored your data from a Time Machine backup this install).  Given the point in time, my memory says that running _xcode-select --install_ should trigger the Command Line Tools install/update.

A bit more nitpicking:

_--with-ssl=/var/root/Ashish/openssl-3.0.5/_, this path strikes me as a possible problem and makes me wonder what user context you are compiling with.  Also, 3.0.5 seems old to me.  In my Apple Silicon environment (M1 Max) using MacPorts to compile (which may introduce Mac specific patches), I end up with a newer version of OpenSSL, 3.0.7.

> curl -V
> curl 7.86.0 (aarch64-apple-darwin22.1.0) libcurl/7.86.0 **OpenSSL/3.0.7** zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.4 libpsl/0.21.1 (+libidn2/2.3.4) nghttp2/1.51.0
> Release-Date: 2022-10-26
> Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
> Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL threadsafe TLS-SRP UnixSockets zstd

Closing thoughts:

When is a version of MacOS/Mac OS X too old to support with the latest version of curl, if there is even such a limitation at this time?

uhei's answer is promising, but much of this thread seems to be M1 hardware based testers that probably have more updated environments.  Setting up the actual environment is possible for me, however, I'm lucky I had the time to write up my thoughts after [a plea on Mastodon](https://mastodon.social/@bagder/109381115519743313).  🤓

Good luck!

**Comment by AshishDurgapal** [comment]
After changing my hostname, now I am able to build the curl lib for 7.84 and 7.86 but now I am getting linking error.

Undefined symbols for architecture arm64:
  "_SCDynamicStoreCopyProxies", referenced from:
      _Curl_resolv in libcurl.a(libcurl_la-hostip.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ryandesign** [comment]
> arm64-apple-macos11

That's still not a valid host triple. The third component of the triple on macOS would be "darwin" (plus an optional Darwin version number) not "macos".

**Comment by AshishDurgapal** [comment]
If we replace the macOS with darwin then we are getting more linking errors.
Undefined symbols for architecture arm64:
  "_EVP_PKEY_id", referenced from:
      _Curl_ossl_certchain in libcurl.a(libcurl_la-openssl.o)
      _cert_stuff in libcurl.a(libcurl_la-openssl.o)
  "_SCDynamicStoreCopyProxies", referenced from:
      _Curl_resolv in libcurl.a(libcurl_la-hostip.o)
  "_SSL_get_peer_certificate", referenced from:
      _ossl_connect_common in libcurl.a(libcurl_la-openssl.o)
ld: symbol(s) not found for architecture arm64

**Comment by jsoref** [comment]
why not try using https://formulae.brew.sh/formula/c-ares ?

**Comment by ne1for23** [comment]
Revisiting this topic I see not much has moved in the past two months.

More observations without setting up your exact environment:

The path in one of your example configure commands said /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/**MacOSX11.1.sdk** and it has me questioning if you have Xcode 12.2 or greater installed.  This is the first version to [add Apple Silicon support](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary):

> Xcode 12.2 and later is a requirement for building universal binaries.

([Xcode 12.2 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_2-release-notes))

So I kind of expect the Apple Silicon symbols to be missing because of the SDK you're targeting.

We earlier learned the environment is macOS 11.2 on an Intel Mac, so the latest Xcode you can run without upgrading the macOS version is [Xcode 12.5.1](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5_1-release-notes).  [Xcode 13 requires](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes) macOS 11.3 or later.

So lets ignore the missing symbols for Apple Silicon created by targeting a SDK that didn't include Apple Silicon support.

I know that the versions I compile on Intel and now Apple Silicon with MacPorts applies patches to the release source, inconsistently making their way back into the upstream source for various reasons.  They put these patches in the ports tree to apply after downloading the original source.  [Here](https://github.com/macports/macports-ports/tree/master/net/curl) is what it looks like for curl.  An interesting note is included in the [Portfile](https://github.com/macports/macports-ports/blob/master/net/curl/Portfile) that applies [a one line patch](https://github.com/macports/macports-ports/blob/master/net/curl/files/configure.patch) to **configure**.  **link_all_deplibs** is set to no.  The Portfile comment as to why reads:

> Prevent curl-config from telling curl's dependents that they have to link with all of curl's dependencies as well.

And one file note about the [curl port in MacPorts](https://ports.macports.org/port/curl/details/).  If you're not familiar with MacPorts, compilation options for optional components are done by variants that do what is necessary to setup the environment.  It's unclear if you're trying to get a compatible version of curl with defaults or if you have specific configure option needs.

For the compiled in options seen in my version on Apple Silicon in my previous post, all pass macPorts automated linking check performed after installing all needed ports after a port install command.

Good luck.  I don't see myself putting much more into this.  The environment, as is, comes across as unsupported at an Apple level and I've heard nothing about the previously suggested software updates or calls to correct something I got wrong that I had to derive because of the level of detail provided thus far.

**Comment by bagder** [comment]
No more comments for months and there is good feedback in here to push the issue forward.

**Comment by ryandesign** [comment]
My initial comment was based on a cursory reading of the bug report but here are some more details after further investigation. TL;DR: Not a bug; user error.

> We are getting given below error while compiling curl with openssl 3.0.5

The use of openssl is not required to reproduce the issue; it can be seen when using `--without-ssl` as well.

> Undefined symbols for architecture arm64:
> "_CFRelease", referenced from:
> _Curl_resolv in libcurl.a(libcurl_la-hostip.o)
> "_SCDynamicStoreCopyProxies", referenced from:
> _Curl_resolv in libcurl.a(libcurl_la-hostip.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

These are symbols provided by macOS frameworks. `SCDynamicStoreCopyProxies` is a SystemConfiguration symbol. `CFRelease` is a CoreFoundation symbol. Linking with those frameworks is the solution. The build system does this for you unless you subvert it as you have.

> CURL version : 7.84/7.86
> Note*: Everything works fine with Curl 7.76

The use of `SCDynamicStoreCopyProxies` was introduced in 31f631a142d855f069242f3e0c643beec25d1b51 which landed in 7.77 and the use of `CFRelease` was introduced in 62be0960858f18798f5f2bf662cbfd9ae3948eb4 which landed in 7.78.

> Machine (uname -a ) : **Darwin RMS-MAC11 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64**
> 
> Configure command which I am using :
> **./configure --host=arm-apple-macos11 --target=arm64-apple-macos11 CFLAGS="-arch arm64 -fPIC" CC="clang -arch arm64" --without-zlib --with-ssl=/var/root/Ashish/openssl-3.0.5/ --disable-ldap --disable-ldaps LDFLAGS="-framework SystemConfiguration -framework CoreFoundation -framework** Security"

"macos" is not a valid autotools OS name. This is the source of all your problems. The correct OS name to specify to a configure script if you mean macOS is "darwin", as in `--host=arm64-apple-darwin`.

The configure script adds the necessary `-framework` flags only when the OS name is "darwin":

https://github.com/curl/curl/blob/a9f8fe28481fef7c28d85b4a12a3a35521408eaf/m4/curl-sysconfig.m4#L27-L53

Your attempt to add the `-framework` flags into LDFLAGS manually was unsuccessful because curl's build system uses libtool, and libtool's behavior varies based on the OS. When the OS is "darwin", libtool knows to pass `-framework` flags on to the linker; on other OS names, it does not do that.

By the way, specifying the OS version number in `--host` is pointless on macOS. If you want to build for a specific macOS version that is not the one you are building on, set the `MACOSX_DEPLOYMENT_TARGET` environment variable, e.g. `export MACOSX_DEPLOYMENT_TARGET=11.0`.

Specifying `-fPIC` in CFLAGS is unnecessary on macOS because all code compiled for macOS is always position-independent.

Specifying `--target` to ./configure is pointless unless you are compiling a cross-compiler, which curl is not. For example, if you were cross-compiling GCC, you might specify `--build` to tell it what system you're building on (usually unnecessary since config.guess will already know), `--host` to tell it what machine the resulting GCC will run on, and `--target` to specify what machine the resulting GCC will create executables for.

Specifying `-arch` flags as part of the CC variable is unusual. Normally you should specify it in CFLAGS (and other equivalent variables for other languages, such as CXXFLAGS if the program contains any C++ code, which curl doesn't) and LDFLAGS, e.g. `CC=cc CFLAGS="-arch arm64" LDFLAGS="-arch arm64" ./configure ...`.

-----

> Note*: Also tried with CC="clang" instead of gcc .

On macOS, ever since Xcode 5, there is no GCC. The `gcc` "program" is a wrapper that calls `clang`.

-----

> Does --host=arm-apple-macos11 need to work?

No, it is a user error.

-----

> ```
> make -s -j $(nproc )
> ```

There is no such thing as `nproc` on macOS. The equivalent on macOS is `sysctl -n hw.activecpu`.

> When I add `--enable-ares` to my flags, I'm able to build curl-7_84_0 w/o failures.

Yes, the code that calls `SCDynamicStoreCopyProxies` and `CFRelease` is only compiled in if c-ares is not enabled:

https://github.com/curl/curl/blob/a9f8fe28481fef7c28d85b4a12a3a35521408eaf/lib/curl_setup.h#L258-L264

-----

> OP is using macOS Big Sur (11.2.x) on an Intel Mac to produce an ARM64 binary. 

Yes but cross-compilation turns out to be irrelevant to the issue. The same problem can be seen when compiling for the native architecture if one specifies the invalid `--host=x86_64-apple-macos` to the configure script. Of course there would be no need to specify `--host` if you weren't cross-compiling.

> this environment should be updated prior to spending any serious troubleshooting time

Updating the OS to receive security updates is fine but irrelevant to the issue.

> When is a version of MacOS/Mac OS X too old to support with the latest version of curl, if there is even such a limitation at this time?

curl is highly portable. MacPorts supports Mac OS X 10.4 and later and as far as I know curl builds fine there. I've even compiled curl for System 7.

-----

> If we replace the macOS with darwin then still we are getting the same linking error

No, switching `macos` to `darwin` in the `--host` parameter fixes the problem.

-----

> why not try using [Homebrew]?

Using a package manager like Homebrew or MacPorts is fine but it is also valid to try to understand how to compile something from source oneself. Certainly at least the people who maintain the software in those package managers need this understanding.

-----

> So I kind of expect the Apple Silicon symbols to be missing because of the SDK you're targeting.

There's no problem with the user's SDK. macOS 11 is the first version for Apple Silicon systems. Correspondingly, the macOS 11 SDK is the first version that supports compiling for Apple Silicon. Xcode 12.2 is the first version that contains the macOS 11 SDK. This is the first sentence of the Xcode 12.2 release notes you linked to:

> Xcode 12.2 includes SDKs for [...] macOS Big Sur 11.

> MacPorts applies patches to the release source, inconsistently making their way back into the upstream source for various reasons. [...] An interesting note is included in the [Portfile](https://github.com/macports/macports-ports/blob/master/net/curl/Portfile) that applies [a one line patch](https://github.com/macports/macports-ports/blob/master/net/curl/files/configure.patch) to **configure**.

Context about why MacPorts applies that patch is [here](https://github.com/macports/macports-ports/pull/3388).

-----

So I think the badmouthing of Apple and macOS is out of place on the linked Mastodon thread. The only problem here was invalid input supplied to the configure script with [predictable results](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out).
