### ISSUE TITLE
Link errors building 7.76.0 with wolfssl and wolfssh on windows

### ISSUE THREAD

**Issue by kdadmin** [curl/curl#6874]
Link errors building 7.76.0 with wolfssl and wolfssh on windows
using Visual Studio 2010 on 2003 server.

curl-7.76.0
wolfssl-4.7.0
wolfssh-1.4.6

Building configuration: DLL Debug - DLL wolfSSL, Win32.

1>  "..\..\..\..\build\Win32\VC10\DLL Debug - DLL wolfSSL\lib\sectransp.obj"
1>  "..\..\..\..\build\Win32\VC10\DLL Debug - DLL wolfSSL\lib\vtls.obj"
1>  "..\..\..\..\build\Win32\VC10\DLL Debug - DLL wolfSSL\lib\wolfssl.obj" (TaskId:26)
1>     Creating library D:\Programming(D)\Workspaces\VS_2010 Workspaces\curl-7.76.0\curl-7.76.0\build\Win32\VC10\DLL Debug - DLL wolfSSL\libcurld.lib and object D:\Programming(D)\Workspaces\VS_2010 Workspaces\curl-7.76.0\curl-7.76.0\build\Win32\VC10\DLL Debug - DLL wolfSSL\libcurld.exp (TaskId:26)
1>curl_ntlm_core.obj : error LNK2019: unresolved external symbol __imp__wolfSSL_DES_ecb_encrypt referenced in function _Curl_ntlm_core_lm_resp
1>curl_ntlm_core.obj : error LNK2019: unresolved external symbol __imp__wolfSSL_DES_set_key referenced in function _setup_des_key
1>curl_ntlm_core.obj : error LNK2019: unresolved external symbol __imp__wolfSSL_DES_set_odd_parity referenced in function _setup_des_key
1>..\..\..\..\build\Win32\VC10\DLL Debug - DLL wolfSSL\libcurld.dll : fatal error LNK1120: 3 unresolved externals
1>  The command exited with code 1120. (TaskId:26)
1>Done executing task "Link" -- FAILED. (TaskId:26)
1>Done building target "Link" in project "libcurl.vcxproj" -- FAILED.: (TargetId:65)

Made changes to curl-7.76.0 sources to get it to build as follows:

1) In curl_ntlm_core.c and h there are # includes like:
    #  include <openssl/some file> 
   Changed to:
    #  include <wolfssl/openssl/some file>
   as the only openssl folder is inside wolfssl - no openssl folder
   in curl-7.76.0.

Notice the link errors are with functions in curl_ntlm_core.c.

2) For fatal error C1189: #error :  "bad math long / long long settings"
    In config-win32.h removed the /* */ around:
     #define SIZEOF_LONG_LONG 8

Note wolfssl and wolfssh build fine on their own.
Followed instructions in wolfssh-1.4.6\ide\winvs README_VS.txt about
copying user_settings.h to wolfssl-4.7.0.

Had worse problems with tiny-curl-7.72.0 from the wolf website.

Full build log is attached.

**Comment by gvanem** [comment]
Berhaps you WolfSSL was built with `-DNO_DES3`?

But check with `dumpbin /exports WolfSSL.dll | grep wolfSSL_DES_ecb_encrypt`

**Comment by bagder** [comment]
Building curl with wolfSSL is no different on Windows than other platforms and we run such builds in the CI. You need to provide us with more details to understand what you're experiencing. For example, how did you build your wolfSSL?

**Comment by kdadmin** [comment]
Thanks for the responses.

Running:
 dumpbin /exports WolfSSL.dll | grep wolfSSL_DES_ecb_encrypt
on the wolfssl\DLL Release wolfssl.dll returns:
 grep' is not recognized as an internal or external command

wolfssl-4.7.0 was built using the wolfssl64.sln provided by wolf.
I followed the instructions in wolfssh-1.4.6\ide\winvs readme.md 
about copying user_settings.h to wolfssl-4.7.0.

wolfssh-1.4.6 was built using the wolfssh.sln in the wolfssh\ide\winvs folder.

Both wolf projects build fine with VS2010, all tests pass.

The wolf user_settings.h defs are below, and used by both wolf projects.
WOLFCRYPT_ONLY is commented out per the wolf instructions.

//#define WOLFCRYPT_ONLY
#define WOLFSSL_KEY_GEN
#define HAVE_ECC
#define HAVE_AESGCM
#define HAVE_HASHDRBG
#define WOLFSSL_AES_COUNTER
#define WOLFSSL_SHA384
#define WOLFSSL_SHA512
#define NO_PSK
#define NO_HC128
#define NO_RC4
#define NO_RABBIT
#define NO_DSA
#define NO_MD4
#define WC_RSA_BLINDING
#define WOLFSSL_PUBLIC_MP
#define SINGLE_THREADED
#define WC_NO_HARDEN
#define WOLFSSH_TERM

curl-7.76 tries to build wolfssl on its own - and fails with the three link errors.
I could provide the output from my own successfull builds for curl to build with
but I find no provision for that. The curl build does its own thing - I would change
it if I could figure out how. 

Note building in the VS2010 command window using:

  nmake /f Makefile.vc mode=dll vc=10 debug=no ENABLE_IDN=no WITH_WOLFSSL=../../wolfssl ENABLE_WINSSL=no

succeeds, but using the generated libcurl.dll and libcurl.lib in a test app
and calling curl_version() returns "version = libcurl/7.76.0 Schannel",
so it is not building with wolf. The lib and dll are output to the:
  "libcurl-vc10-x86-release-dll-ipv6-sspi-schannel" folder.

**Comment by bagder** [comment]
The DES function (used for NTLM) you lack is provided by the OpenSSL API layer in wolfSSL so you need to have that enabled in the wolfSSL build.

Let's focus on one problem per issue. If you want to work on other build problems we can deal with them separately.

**Comment by gvanem** [comment]
> grep' is not recognized as an internal or external command

Use `findstr` instead. Part of every Windows since forever.

> Both wolf projects build fine with VS2010, all tests pass.

Tests that include `wolfSSL_DES_ecb_encrypt()` too? 
E.g. for the `unit.exe` program, do you see `  wolfSSL_DES_ecb_encrypt()` printed? 
Ref. `tests/api.c`  and function `test_wolfSSL_DES_ecb_encrypt()`.

**Comment by gvanem** [comment]
> The DES function (used for NTLM) you lack is provided by the OpenSSL API layer in wolfSSL 

Except when `USE_OPENSSL` + `USE_WOLFSSL` are used, the OpenSSL versions wins.

**Comment by bagder** [comment]
> Except when USE_OPENSSL + USE_WOLFSSL are used, the OpenSSL versions wins.

If we use a function name and two libraries provide them, one of the libraries has to "win". But doesn't that also depend on link order?

But I assume very few people actually build with *both* OpenSSL and wolfSSL so I don't think this is a big problem.

**Comment by gvanem** [comment]
>  But doesn't that also depend on link order?

I have not tried with the non-prefixed (`wolfSSL_`) names (If it's legal to build WolfSSL with). So I'm not sure what could happen.
If the symbols were not prefixed, I assume the link order doesn't matter to MSVC's `link`. It's a 2 pass linker doing a better job that `ld`. 

So not a big deal; both WolfSSL and OpenSSL does the same good job it seems.

**Comment by kdadmin** [comment]
>>>Use findstr instead. Part of every Windows since forever.
Running dumpbin /exports WolfSSL.dll | findstr wolfSSL_DES_ecb_encrypt
 returns nothing.

If add I add #define OPENSSL_EXTRA & #define WOLFSSL_DES_ECB to the
user_settings.h used by both wolfssl and wolfssh, it returns:
 729  2D8 00028FC0 wolfSSL_DES_ecb_encrypt = _wolfSSL_DES_ecb_encrypt

>>>Tests that include wolfSSL_DES_ecb_encrypt() too?
There is no unit.exe produced by this wolfssl-4.7.0 that I can find. 
There's a testsuite configuration, in which all 4 build fine. Can't find wolfSSL_DES_ecb_encrypt in any output for wolfssl, only in a few source files - tests/api.c`and function `test_wolfSSL_DES_ecb_encrypt() as you mention.

>>>The DES function (used for NTLM) you lack is provided by the OpenSSL API layer in wolfSSL so you need to have that enabled in the wolfSSL build.

I added #define OPENSSL_EXTRA & #define WOLFSSL_DES_ECB to the user_settings.h in both wolfssl and wolfssh - all built fine.
Rebuilding curl produced the same errors.

**Comment by kdadmin** [comment]
Sorry - the comment above is a mess of formatting and I can't figure out how to edit it.

**Comment by bagder** [comment]
If the symbol is actually present in the library, why does the link say it isn't? I don't see how that is a curl issue.

**Comment by jay** [comment]
OP were you able to resolve this?

**Comment by kdadmin** [comment]
No - I gave up on Wolf and used openssl.

**Comment by bagder** [comment]
Closing as the reporter has given up, we lack details and cannot reproduce.
