### ISSUE TITLE
Static libcurl fails to link with crypt32

### ISSUE THREAD

**Issue by MAN-AT-ARMS** [curl/curl#1518]
Non-configure, static build with gcc fails to link with crypt32 when using WinSSL/SSPI.

Linking against libcurl starting with v7.50.0 produces errors: undefined reference to `__imp__CertFreeCertificateContext'

Passing LDFLAGS='-static' does not help.

Issue began in 6cabd78 with changes to schannel

**Comment by bagder** [comment]
Similar to #1482, which unfortunately "solved itself".

**Comment by jay** [comment]
Yes, as mentioned there I cannot reproduce this. Try the latest version. If that doesn't work please give us steps to reproduce with the latest version libcurl.

**Comment by MAN-AT-ARMS** [comment]
After building from git, it works. Hmm. Will try again from release tarball which is what I used originally.

**Comment by MAN-AT-ARMS** [comment]
Disregard the last message...It still actually isn't linking even in build from git. I was still linking against the older libcurl version that worked.

CC=x86_64-w64-mingw32-gcc WINDRES=x86_64-w64-mingw32-windres AR=x86_64-w64-mingw32-ar AS=x86_64-w64-mingw32-as RANLIB=x86_64-w64-mingw32-ranlib LD=x86_64-w64-mingw32-ld ./configure --host=x86_64-w64-mingw32 --disable-shared --enable-static --disable-ares --enable-http --enable-ftp --disable-ldap --disable-ldaps --disable-rts --disable-rtsp --disable-dict --disable-file --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --enable-ipv6 --with-winssl --disable-cookies --disable-verbose --disable-manual --disable-libcurl-option

**Comment by MAN-AT-ARMS** [comment]
More info from when linking:
undefined reference to `idn2_check_version'
undefined reference to `idn2_free'
undefined reference to `idn2_lookup_ul'
undefined reference to `__imp_CertFreeCertificateContext'

If setting LDFLAGS='-static' the undefined references to idn2 go away.

**Comment by jay** [comment]
Just to be clear what version won't build in git? Did you try the latest release version? It builds successfully for me using curl-7.54.0 release source and your configure command.
~~~
curl 7.54.0 (x86_64-w64-mingw32) libcurl/7.54.0 WinSSL
Protocols: ftp ftps http https 
Features: IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL 
~~~
In my case libidn2 is never enabled because x86_64-w64-mingw32-pkg-config can't find it (it's not a package in Ubuntu and I've never cross compiled it). Is it possible you have some old build files that are affecting things? Since you are building from the repo run ./buildconf first to rebuild the configure script each time you git checkout a different version.

**Comment by MAN-AT-ARMS** [comment]
libcurl.a does build successfully...You just cant link against it due to the undefined references. Apparently because crypt32 isn't being linked/built into it during the build. (The IDN2 stuff isn't linked/built into it either unless you pass the -static argument via LDFLAGS.) However passing the -static argument does not resolve the issue with crypt32.

All builds since the commit referenced above have the issue. (Which appeared first in release 7.50.0 and continues all the way up until now)

**Comment by jay** [comment]
Sorry this is still unclear. Are you saying curl won't link or you have some other program and are linking against libcurl and that won't link? If you are linking against a static libcurl then you will have to also link against Windows dependencies such as crypt32 that are not static. What is in your libcurl.pc?
~~~
Name: libcurl
URL: https://curl.haxx.se/
Description: Library to transfer files with ftp, http, etc.
Version: 7.54.0
Libs: -L${libdir} -lcurl
Libs.private: -lcrypt32 -lws2_32
Cflags: -I${includedir} -DCURL_STATICLIB
~~~
PKG_CONFIG_PATH=$PWD pkg-config --libs --cflags --static libcurl
-DCURL_STATICLIB -I/usr/local/include  -L/usr/local/lib -lcurl -lcrypt32 -lws2_32

**Comment by MAN-AT-ARMS** [comment]
Yes. I was referring to another application linking against libcurl.a.

Adding the -lcrypt32 argument in the application Makefile does indeed correct the issue. (I didn't think it would be needed for a static build, maybe I'm wrong in that assumption) So I guess we can consider that issue resolved.

Not sure if you want to keep the Issue open in the mean time due to the need for passing the -static option to LDFLAGS for the IDN2 stuff.

Thanks

**Comment by bagder** [comment]
A static build means that *libcurl* is made static. It also means that you need to explicitly add all the (other) dependent libs yourself when linking your application.

> Not sure if you want to keep the Issue open in the mean time due to the need for passing the -static option to LDFLAGS for the IDN2 stuff.

No, I don't think that is the correct conclusion so this issue will be closed now. If there are additional (separate) problems they can be filed as new issues.

**Comment by esfomeado** [comment]
./configure --disable-shared --enable-optimize --enable-threaded-resolver --disable-libcurl-option --disable-ares --disable-rt --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-manual --disable-ipv6 --disable-sspi --disable-crypto-auth --disable-ntlm-wb --disable-tls-srp --disable-unix-sockets --without-zlib --without-winssl --without-ssl --without-libssh2 --without-nghttp2 --disable-cookies --without-ca-bundle --without-librtmp --disable-verbose --disable-versioned-symbols --enable-hidden-symbols

curl 7.55.1 (x86_64-w64-mingw32) libcurl/7.55.1 libidn2/2.0.3
Release-Date: 2017-08-14
Protocols: http
Features: AsynchDNS IDN Largefile

When trying to build my application i get:
undefined reference to `idn2_check_version'

Although works fine with curl 7.54.

**Comment by bagder** [comment]
@esfomeado your problem does not look like the **closed** one you're commenting to. Please file a new bug or email the mailing list.
