### PR TITLE
travis: use go stable, (second try)

### PR DESCRIPTION
**Pull request by jay**
Mac builds have been failing since 52db0b8 was added to use go stable in all builds. Based on the failures it looks like gimme is not available in Mac images? I've written support to find out but also I'd like to see if it's possible to limit getting go latest stable to just the boringssl builds.

Ref: https://github.com/curl/curl/pull/4361

### CODE REVIEW

**Comment by jay** [comment]
Is something else affecting the two boringssl builds? i don't see why this
~~~
url.c: In function ‘Curl_connect’:
url.c:1883:13: error: offset outside bounds of constant string [-Werror]
     hostname++;
~~~
https://github.com/curl/curl/blob/4a778f75c526e638b2fe1e2f627eb6649638b570/lib/url.c#L1872-L1888

confused by (char *)"" maybe. i wonder if it would be confused even if const char *hostname. bad practice anyway so how about char empty[]=""; then later there if (!hostname) hostname = empty;

**Comment by bagder** [comment]
Try it. And the check for '[' could use an `else` too...

**Comment by jay** [comment]
> That seems to have done it!

Yeah but we're still lying to the compiler, bad practice...

In other news support says gimme is not preinstalled on mac VMs so they would need `if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gimme; fi` but I think it's easier to just limit it to the two boringssl builds as above.

**Comment by bagder** [comment]
sure, that works for me!

**Comment by bagder** [comment]
> I think it's easier to just limit it to the two boringssl builds as above.

For now, yes. I think it would be valuable to add those builds to osx too though so it could be worth testing out that solution. But let's do that in a separate PR.
