### ISSUE TITLE
Failed to build on windows latest mingw with cmake

### ISSUE THREAD

**Issue by mygithubcomments2017** [curl/curl#2361]
### I did this
`>` Got latest mingw via: http://www.mingw.org/wiki/Getting_Started, mingw-get-setup.exe ,, installed version is: `gcc.exe (MinGW.org GCC-6.3.0-1) 6.3.0`, put `c:\mingw\bin` into my PATH.
`>` Got latest cmake from: cmake.org (v 3.10.2)
`>` Got curl 7.58.0.
`>` Ran `c:\programs\CMake\bin\cmake.exe -G "MinGW Makefiles"` & then ran: `mingw32-make.exe`
`>>` then at `8% building` I got: `curl_addrinfo.c:156:15: error: 'ERROR_NOT_ENOUGH_MEMORY' undeclared (first use in this function)`
`>>>` So I just replaced EAI_MEMORY to ENOMEM in all places.
`>>>>` When retrying building libcurl, got another error: `CMakeFiles\libcurl.dir/objects.a(timeval.c.obj):timeval.c:(.text+0xb5): undefined reference to 'GetTickCount64'`

### operating system
Windows 7 SP1

**Comment by bagder** [comment]
> I got: curl_addrinfo.c:156:15: error: 'ERROR_NOT_ENOUGH_MEMORY' undeclared (first use in this function)

Wait a second! There's no `ERROR_NOT_ENOUGH_MEMORY` symbol used in curl_addrinfo.c. Neither on line 156 or any other line.  Where does that come from?

I can only find a single reference to such a symbol in libcurl and that's in curl_threads.c for WinCE-specific code and it checks the return code from `GetLastError();`...

> I just replaced EAI_MEMORY to ENOMEM in all places.

That's not a correct fix. They're different values for different purposes. The [netdb.h](http://pubs.opengroup.org/onlinepubs/009696899/basedefs/netdb.h.html) header typically defines `EAI_MEMORY`. How your brand new mingw install doesn't have this is beyond me. But this problem is probably somehow a consequence of the previous one.

> undefined reference to 'GetTickCount64'

Our code uses that function when built for [a Windows version after Windows Vista](https://github.com/curl/curl/blob/master/lib/timeval.c#L35-L44). Does mingw somehow break that assumption?

**Comment by mygithubcomments2017** [comment]
> Wait a second! There's no ERROR_NOT_ENOUGH_MEMORY symbol used in curl_addrinfo.c. Neither on line 156 or any other line. Where does that come from?<br>

`>` Full cmake error message:
```
[  0%] Building C object lib/CMakeFiles/libcurl.dir/curl_addrinfo.c.obj
In file included from F:/src/_temp_curl_7_58_try_1/curl-7.58.0/include/curl/system.h:391:0,
                 from F:/src/_temp_curl_7_58_try_1/curl-7.58.0/include/curl/curl.h:38,
                 from F:\src\_temp_curl_7_58_try_1\curl-7.58.0\lib\curl_setup.h:142,
                 from F:\src\_temp_curl_7_58_try_1\curl-7.58.0\lib\curl_addrinfo.c:23:
F:\src\_temp_curl_7_58_try_1\curl-7.58.0\lib\curl_addrinfo.c: In function 'Curl_getaddrinfo_ex':
F:\src\_temp_curl_7_58_try_1\curl-7.58.0\lib\curl_addrinfo.c:156:15: error: 'ERROR_NOT_ENOUGH_MEMORY' undeclared (first use in this function)
       error = EAI_MEMORY;
               ^
F:\src\_temp_curl_7_58_try_1\curl-7.58.0\lib\curl_addrinfo.c:156:15: note: each undeclared identifier is reported only once for each function it appears in
lib\CMakeFiles\libcurl.dir\build.make:1587: recipe for target 'lib/CMakeFiles/libcurl.dir/curl_addrinfo.c.obj' failed
```
> Our code uses that function when built for a Windows version after Windows Vista. Does mingw somehow break that assumption? <br>

`>` It's a possibility (i also asked on ##mingw on freenode, no response, (I suspected that too ...))

**Comment by PetePriority** [comment]
If it helps, the problem does not occur in curl-7.50.1

**Comment by bagder** [comment]
@PetePriority and you too get the problem with 7.58.0 using the same setup that can build 7.50.1 fine?

**Comment by PetePriority** [comment]
@bagder y Yes, I have the same problem in 7.58.0 and 7.59.0, but 7.50.1 works fine.

**Comment by PetePriority** [comment]
@bagder The breaking changes appear to have been introduced in 7.55.0. 7.54.1 is the most recent release that builds fine.

**Comment by bagder** [comment]
`lib/curl_addrinfo.c` is however identical in both those versions... :-( Any chance you can [bisect](https://github.com/curl/curl/wiki/how-to-git-bisect) this to find the exact commit that broke the build? It might at least shed more light to the issue...

**Comment by PetePriority** [comment]
(Thanks for introducing me to git bisect. That's a nice feature!)
First bad commit is: 9ee6cb1b77c7a9a17c5ce380cec72066e13b1ebf 
```
9ee6cb1b77c7a9a17c5ce380cec72066e13b1ebf is the first bad commit
commit 9ee6cb1b77c7a9a17c5ce380cec72066e13b1ebf
Author: Daniel Stenberg <daniel@haxx.se>
Date:   Wed Jul 5 10:21:58 2017 +0200

    cmake: if inet_pton is used, bump _WIN32_WINNT

    ... and make sure inet_pton is always checked for when *not* using Windows,
    which is a regression from 4fc6ebe18.

    Idea-by: Sergei Nikulov

:100644 100644 727ca81537694f08afac732ff0fac1c3502fc8f2 5d8b9f10f6e1b264cba9fed3122cf8989db0f44b M  CMakeLists.txt
```
The build failed with a different error though:
```
[ 77%] Linking C shared library libcurl.dll
CMakeFiles\libcurl.dir/objects.a(timeval.c.obj):timeval.c:(.text+0x7): undefined reference to `GetTickCount64'
CMakeFiles\libcurl.dir/objects.a(asyn-thread.c.obj):asyn-thread.c:(.text+0x90d): undefined reference to `InitializeCriticalSectionEx'
collect2.exe: error: ld returned 1 exit status
lib\CMakeFiles\libcurl.dir\build.make:3444: recipe for target 'lib/libcurl.dll' failed
mingw32-make[2]: *** [lib/libcurl.dll] Error 1
CMakeFiles\Makefile2:322: recipe for target 'lib/CMakeFiles/libcurl.dir/all' failed
mingw32-make[1]: *** [lib/CMakeFiles/libcurl.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```
I'll run another bisect to see where the other error appears.

**Setup:**
Installed MinGW (mingw-developer-toolkit, mingw32-base, mingw32-gcc-g++, msys-base)
Installed MinGW Perl (https://sourceforge.net/projects/perl-mingw/)
```
git bisect start
git bisect good curl-7_54_1
git bisect bad curl_7_55_0
```

**Building:** (in cmd.exe)
```run-cmake.bat
rd /s /q build
mkdir build
cd build
cmake -G "MinGW Makefiles" .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF 
mingw32-make -j8 
cd ..
```

**Comment by PetePriority** [comment]
`'ERROR_NOT_ENOUGH_MEMORY' undeclared (first use in this function)` first appears in b22ec396405d05f9c47f78b56214b8381979e575
```
b22ec396405d05f9c47f78b56214b8381979e575 is the first bad commit
commit b22ec396405d05f9c47f78b56214b8381979e575
Author: Marcel Raad <Marcel.Raad@teamviewer.com>
Date:   Wed Jul 12 07:55:18 2017 +0200

    system.h: include winsock2.h before windows.h

    ... to avoid compiler warnings if the user doesn't want
    WIN32_LEAN_AND_MEAN.

:040000 040000 7749e8d64ece22036eddc4e798f2c1ff47cee032 2d692ea61876a42adb400dabd97aa760acd8f91e M  include
```

**Comment by MarcelRaad** [comment]
I can reproduce these using the MSYS CMake generators using the original MinGW.

`ws2tcpip.h` has
```
#define EAI_MEMORY	WSA_NOT_ENOUGH_MEMORY
```

`winsock2.h` (which implicitly pulls in parts of `winsock.h`) has
```
#define WSA_NOT_ENOUGH_MEMORY		(ERROR_NOT_ENOUGH_MEMORY)
```

`winerror.h` (implicitly included by `windows.h` and `winsock.h`) has
```
#ifndef __WINSOCK_H_SOURCED__
/* Part of this header is available for selective inclusion by <winsock.h>;
 * mark it as fully processed, only when NOT so included; otherwise, occlude
 * those parts which are not relevant for <winsock.h>
 */
...
#define ERROR_NOT_ENOUGH_MEMORY 					    8L
...
/* This ends the first group of error codes which are to be occluded
 * when selectively included by <winsock.h>
 */
#endif	/* !__WINSOCK_H_SOURCED__ */
```

That's obviously a bug in w32api as including `winsock2.h` can only ever work with a prior `windows.h` (or `winerror.h`) include. The purpose of inluding `winsock2.h` before `windows.h` is to make sure that windows.h doesn't implicitly pull in WinSock v1 (which it does in other Windows SDKs, whereas w32api happens to pull in WinSock v2 instead). So we could probably work around this by including `winerror.h` first.

> I also get this warning in build b22ec39 and following:
> [  4%] Building C object lib/CMakeFiles/libcurl.dir/http.c.obj
> C:\temp\curl\lib\timeval.c: In function 'Curl_now':
> C:\temp\curl\lib\timeval.c:41:28: warning: implicit declaration of function 'GetTickCount64' [-Wimplicit-function-declaration]
>    ULONGLONG milliseconds = GetTickCount64();
>                             ^~~~~~~~~~~~~~
> C:\temp\curl\lib\timeval.c:41:3: warning: nested extern declaration of 'GetTickCount64' [-Wnested-externs]
>    ULONGLONG milliseconds = GetTickCount64();
>   ^~~~~~~~~

But these should already be in https://github.com/curl/curl/commit/9ee6cb1b77c7a9a17c5ce380cec72066e13b1ebf, right? Looks like the original MinGW's w32api really doesn't have GetTickCount64, regardless of the target Windows version. You can work around these with `-DENABLE_INET_PTON=OFF`.

Out of curiosity, is there any reason you're using the original MinGW rather than the more complete MinGW-w64?

**Comment by bagder** [comment]
Another possible approach to a fix is to do an ugly [ifdef for mingw](https://sourceforge.net/p/predef/wiki/Compilers/#mingw-and-mingw-w64) ...

**Comment by PetePriority** [comment]
> Out of curiosity, is there any reason you're using the original MinGW rather than the more complete MinGW-w64?
Not knowing any better. I'm fairly new to compiling on Windows and was assuming that MinGW is still maintained. Using cmake as above and MinGW64-w64 (x86_64-7.2.0-posix-seh-rt_v5-rev1 and i686-7.2.0-posix-dwarf-rt_v5-rev1) works on curl-7_59_0 and master.

**Comment by MarcelRaad** [comment]
> I'm fairly new to compiling on Windows and was assuming that MinGW is still maintained.

It is still maintained and updated occasionally. But support for Vista+ is pretty bad. Maybe we should target Windows XP by default for classic MinGW, or change `ENABLE_INET_PTON`'s default to `OFF`.

**Comment by snikulov** [comment]
@PetePriority Can we close this issue? Is workaround suggested by @MarcelRaad helps you?

> cmake .. -DENABLE_INET_PTON=OFF

**Comment by PetePriority** [comment]
> @PetePriority Can we close this issue? Is workaround suggested by @MarcelRaad helps you?
The build still fails with `ENABLE_INET_PTON=OFF`. 

I've resolved the issue by switching to mingw-w64. So I think we can close this issue.

**Comment by snikulov** [comment]
@PetePriority Thanks!
