### PR TITLE
macOS: Fixed crash on 10.8 caused by missing connectx() function

### PR DESCRIPTION
**Pull request by markovicpp**
The connectx() function call appeared in Darwin 15.0.0
That covers OS X 10.11, iOS 9 and tvOS 9.

Because connectx is not declared with weak_import attribute it’s not possible
to build libcurl on OS X 10.11 and later and target systems which don’t have
_connectx symbol declared in libsystem_kernel.dylib (i.e. OS 10.8 and earlier).

Solution is to use connectx only on platforms that officially support it
i.e. by defining CFLAGS="-mmacosx-version-min=10.11" in configure step.

Note: It is possible to conditionally use connectx() in libcurl targeting
range of systems based on availability determined during runtime using dlsym().

[Bug: https://github.com/curl/curl/issues/1330]

### CODE REVIEW

**Comment by markovicpp** [comment]
This PR has advanced alternative https://github.com/curl/curl/pull/1339

**Comment by markovicpp** [comment]
I guess to be consistent with curl build process the check for connectx availability should be moved to configure step (if possible). Is that correct assumption?

**Comment by jay** [comment]
curl has multiple build systems. I think when it's built against darwin cmake is the only other one.

**Comment by markovicpp** [comment]
Is the cmake one maintained? It does not seem to be up-to-date.

**Comment by jzakrzewski** [comment]
CMake is "a little behind" but it has progressed significantly in the last year or so.

**Comment by markovicpp** [comment]
What is the preferred way of dealing with multiple build systems then?
Having duplicated configuration tests or doing preprocessor checks in headers during compile time?

**Comment by markovicpp** [comment]
Any decision on this? I can submit missing cmake checks if that’s the preferred way.

**Comment by jay** [comment]
Fixups squashed and rebased on master. Anyone familiar with mac /xcode please review.

**Comment by bagder** [comment]
Builds and works fine on my mac test box.

**Comment by jay** [comment]
@nickzman can you take a look

**Comment by nickzman** [comment]
Hmm. I already fixed this problem back in August in commit 870d849d48. However, my fix requires Xcode 9.0.

This change looks like it'll fix the problem for people that are still using Xcode 7 or 8, which (1) did not support __builtin_available(), and (2) shipped with headers that did not properly mark connectx() as a latter-day addition. The catch is, it'll avoid building with connectx() entirely if the builder targets an older OS, whereas my fix will use connectx() on macOS 10.11 & later while falling back on connect() on older OSes.

I won't throw a fit if this is merged, but I do like my solution better. I don't see much of a future for Xcode 7 or 8; not when Apple has free OS updates across all of their hardware.

**Comment by jay** [comment]
@nickzman what would you recommend for those older xcode versions, that we disable it? Are a lot of people using those versions? I would like to prevent a crash for them but what you say about falling back on connect sounds better.

**Comment by nickzman** [comment]
macOS and Xcode updates have been free for several years now, so there aren't a whole lot of people still using versions of macOS prior to 10.10 or so (with the exception of 10.6 Snow Leopard, which is Apple's XP). I don't think anyone's had a problem with the current strategy of just not using connectx() if the user is using an older toolchain to build the library, since not many people use older toolchains.

**Comment by markovicpp** [comment]
@nickzman I agree with you that the future belongs to newer toolchains and systems but at the same time curl shouldn't crash on older systems. Also not everyone has luxury of using the latest Xcode version and it's not about price of software but price of upgrade. A lot of corporate clients are stuck with older versions for various compatibility reasons.

Currently curl 7.56.1 build with Xcode 8 will fail to work with --tcp-fastopen on OS X 10.9 - 10.10 giving result:
> curl: (7) Couldn't connect to server

And will crash on systems prior that:
>dyld: lazy symbol binding failed: Symbol not found: _connectx
  Referenced from: curl-7.56.1/lib/libcurl.4.dylib
  Expected in: /usr/lib/libSystem.B.dylib

>dyld: Symbol not found: _connectx
  Referenced from: curl-7.56.1/lib/libcurl.4.dylib
  Expected in: /usr/lib/libSystem.B.dylib

>Trace/BPT trap: 5

In the light of this, I'd at least suggest to extend your fix, to disable connectx completely when building with Xcode pre-9.0. Also the fix does not work with cmake, right?

**Comment by nickzman** [comment]
Extending the fix sounds good to me. And does anyone use CMake to build curl on macOS? I've only ever used Autoconf to build curl.
