### ISSUE TITLE
[Regression] 8.19.0 fails to build with gcc-4.2 due to pragmas inside functions

### ISSUE THREAD

**Issue by barracuda156** [curl/curl#20924]
### I did this

Building `curl` with Xcode gcc fails due to pragmas inside functions:
```
:info:build libtool: compile:  /usr/bin/gcc-4.2 -std=gnu99 -DHAVE_CONFIG_H -I../include -I../lib -I../lib -I. -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /opt/bootstrap/include -isystem /opt/bootstrap/include -isystem /opt/bootstrap/libexec/openssl3/include -fvisibility=hidden -pipe -Os -mmacosx-version-min=10.6 -arch x86_64 -Werror-implicit-function-declaration -Wno-system-headers -Wno-shadow -Wno-unreachable-code -Wno-overlength-strings -Wno-missing-field-initializers -MT libcurl_la-mime.lo -MD -MP -MF .deps/libcurl_la-mime.Tpo -c mime.c  -fno-common -DPIC -o .libs/libcurl_la-mime.o
:info:build mv -f .deps/libcurl_la-md5.Tpo .deps/libcurl_la-md5.Plo
:info:build libtool: compile:  /usr/bin/gcc-4.2 -std=gnu99 -DHAVE_CONFIG_H -I../include -I../lib -I../lib -I. -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -isystem /opt/bootstrap/include -isystem /opt/bootstrap/include -isystem /opt/bootstrap/libexec/openssl3/include -fvisibility=hidden -pipe -Os -mmacosx-version-min=10.6 -arch x86_64 -Werror-implicit-function-declaration -Wno-system-headers -Wno-shadow -Wno-unreachable-code -Wno-overlength-strings -Wno-missing-field-initializers -MT libcurl_la-mprintf.lo -MD -MP -MF .deps/libcurl_la-mprintf.Tpo -c mprintf.c  -fno-common -DPIC -o .libs/libcurl_la-mprintf.o
:info:build /bin/sh ../libtool  --tag=CC   --mode=compile /usr/bin/gcc-4.2 -std=gnu99 -DHAVE_CONFIG_H   -I../include -I../lib -I../lib -I.  -DBUILDING_LIBCURL  -DCURL_HIDDEN_SYMBOLS -isystem /opt/bootstrap/include -isystem /opt/bootstrap/include -isystem /opt/bootstrap/libexec/openssl3/include -fvisibility=hidden -pipe -Os -mmacosx-version-min=10.6 -arch x86_64 -Werror-implicit-function-declaration -Wno-system-headers -Wno-shadow -Wno-unreachable-code -Wno-overlength-strings -Wno-missing-field-initializers  -MT libcurl_la-multi_ev.lo -MD -MP -MF .deps/libcurl_la-multi_ev.Tpo -c -o libcurl_la-multi_ev.lo `test -f 'multi_ev.c' || echo './'`multi_ev.c
:info:build mprintf.c: In function 'out_double':
:info:build mprintf.c:676: error: #pragma GCC diagnostic not allowed inside functions
:info:build mprintf.c:677: error: #pragma GCC diagnostic not allowed inside functions
:info:build mprintf.c:691: error: #pragma GCC diagnostic not allowed inside functions
:info:build make[2]: *** [libcurl_la-mprintf.lo] Error 1
:info:build make[2]: *** Waiting for unfinished jobs....

/usr/bin/gcc-4.2 -std=gnu99 -DHAVE_CONFIG_H   -I../include -I../lib -I../lib -I.   -DUSE_MANUAL  -isystem /opt/bootstrap/include -isystem /opt/bootstrap/include -isystem /opt/bootstrap/libexec/openssl3/include  -pipe -Os -mmacosx-version-min=10.6 -arch x86_64 -Werror-implicit-function-declaration -Wno-system-headers -Wno-shadow -Wno-unreachable-code -Wno-overlength-strings -Wno-missing-field-initializers  -MT curl-tool_cb_prg.o -MD -MP -MF .deps/curl-tool_cb_prg.Tpo -c -o curl-tool_cb_prg.o `test -f 'tool_cb_prg.c' || echo './'`tool_cb_prg.c
tool_cb_prg.c: In function ‘tool_progress_cb’:
tool_cb_prg.c:204: error: #pragma GCC diagnostic not allowed inside functions
tool_cb_prg.c:205: error: #pragma GCC diagnostic not allowed inside functions
tool_cb_prg.c:209: error: #pragma GCC diagnostic not allowed inside functions
make[1]: *** [curl-tool_cb_prg.o] Error 1
make[1]: *** Waiting for unfinished jobs....

```

### I expected the following

This is not a worth reason to break the build, IMO. Requiring modern compiler gonna increase bootstrap time by an order of magnitude. Can this either be dropped or made conditional?

### curl/libcurl version

8.19.0

### operating system

macOS 10.6.8

**Comment by barracuda156** [comment]
Looks like broken by https://github.com/curl/curl/commit/f07a98ae113b832a8748ba66e1554a7f14c6897e

FYI @vszakats

**Comment by bagder** [comment]
> Requiring modern compiler gonna increase bootstrap time

A question is if or why we should care.

Why use an 18 years old compiler to build modern software?

**Comment by bagder** [comment]
See also #20892

**Comment by barracuda156** [comment]
> A question is if or why we should care.

@bagder Because portability is good. It is important to keep dependencies for fundamental ports minimal. Also, if the project was written in C++23, the question would not arise; here, however, we have pragmas added without the correct condition, which introduced unnecessary breakage (in fact elsewhere in `curl` codebase condition on gcc version is used).

> Why use an 18 years old compiler to build modern software?

`curl` is a dependency for `cmake`, `cmake` is needed to build `llvm`, for example (details will depend, but the point is that minimizing bootstrap chain is always good). It is impossible to use only gcc-4.2, of course; but we need a way to get to modern gcc/clang from it (I also recall some of *BSDs used gcc 4.x until somewhat recently).

**Comment by vszakats** [comment]
> > A question is if or why we should care.
> 
> [@bagder](https://github.com/bagder) Because portability is good. It is important to keep dependencies for fundamental ports minimal. Also, if the project was written in C++23, the question would not arise; here, however, we have pragmas added without the correct condition, which introduced unnecessary breakage (in fact elsewhere in `curl` codebase condition on gcc version is used).

The choice of a C language standard and specific compiler/toolchain
features are two distinct ones. I don't see the "dichotomy" as argued in
the sibling report a few days ago.

curl tests received the workaround for a platform (WinCE) curl no longer
supports. Before f07a98ae113b832a8748ba66e1554a7f14c6897e there were already pragma push/pop uses in
Apple LDAP and Kerberos/GSS codepaths for a good while, and Secure
Channel earlier (all enabled by default). Also in brotli codepath since
2023. Tests also weren't building for many versions with ancient gcc,
and triggered no reports. This suggests tests may be rarely if ever
built and run on these platforms. Current codebase also fails with
system ZLIB enabled (the default):
```
lib/content_encoding.c:205:12: error: 'inflateReset2' is only available on macOS 10.7 or newer [-Werror,-Wunguarded-availability]
  205 |         if(inflateReset2(z, -MAX_WBITS) == Z_OK) {
      |            ^~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/zlib.h:978:21: note: 'inflateReset2' has been marked as being introduced in macOS 10.7 here, but the deployment target is macOS 10.6.8
  978 | ZEXTERN int ZEXPORT inflateReset2 OF((z_streamp strm,
      |                     ^
lib/content_encoding.c:205:12: note: enclose 'inflateReset2' in a __builtin_available check to silence this warning
  205 |         if(inflateReset2(z, -MAX_WBITS) == Z_OK) {
      |            ^~~~~~~~~~~~~
  206 |           z->next_in = orig_in;
  207 |           z->avail_in = nread;
  208 |           zp->zlib_init = ZLIB_INFLATING;
  209 |           zp->trailerlen = 4; /* Tolerate up to 4 unknown trailer bytes. */
  210 |           done = FALSE;
  211 |           break;
  212 |         }
```

with zlib disabled (or configuring a supported, non-system, zlib
version) it's possible to build curl for macOS 10.6.8 x86_64 as
in OP, using a modern toolchain.

I agree portability is good, but it also needs a steady effort, and
efforts are not unlimited.

> `curl` is a dependency for `cmake`, `cmake` is needed to build `llvm`, for example (details will depend, but the point is that minimizing bootstrap chain is always good). It is impossible to use only gcc-4.2, of course; but we need a way to get to modern gcc/clang from it (I also recall some of *BSDs used gcc 4.x until somewhat recently).

CMake requires C++ 11 since v3.10. Does g++ v4.2.1 support it?

According to https://llvm.org/docs/GettingStarted.html#software,
recent LLVM requires CMake 3.20, gcc 7.4, Clang 5.0 (Apple: 10.0),
VS2019. All newer than what curl supports.

**Comment by barracuda156** [comment]
> CMake requires C++ 11 since v3.10. Does g++ v4.2.1 support it?

@vszakats You are right, it was not a good example. (CMake 3.9.6 can be built with Xcode gcc, but it can be built without curl, since only used for bootstrap.)
I do have a specific case where it becomes a big trouble though: system curl on older macOS (not sure about exact threshold, and it may change anyway, but roughly < 10.9) is too old to be usable, so MacPorts, for example, cannot fetch tarballs from GitHub (or any https). To make MacPorts usable normally, we need modern curl. And then it makes a difference if I can bootstrap a tree with curl in an hour or two – or in 24 hours or days of compilation (okay, I do not compile gcc on a PowerBook myself, but I know others who did).

> it's possible to build curl for macOS 10.6.8 x86_64 as in OP, using a modern toolchain

```
The following ports are dependencies of curl @8.19.0_0+http2+idn+psl+ssl+zstd:
  xz
    gettext
      ncurses
      gettext-tools-libs
        libiconv
          gperf
        libtextstyle
        gettext-runtime
  pkgconfig
  zlib
  nghttp2
    legacy-support
  libidn2
    libunistring
      autoconf
        xz-bootstrap
        m4-bootstrap
      automake
      libtool
        m4
  libpsl
    python310
      bzip2
      expat
      libedit
      libffi
        dejagnu
          expect
            tcl
      openssl
        openssl3
      sqlite3
      python_select-310
        python_select
      python3_select-310
        python3_select
  curl-ca-bundle
    unzip
    perl5
      perl5.34
        db48
        gdbm
          readline
  zstd
    lz4
```
All these are trivial to compile, less than an hour on a G5. If we get modern gcc (or clang) into the picture, it is plus 4-5 hrs at least.

> there were already pragma push/pop uses in Apple LDAP and Kerberos/GSS codepaths for a good while, and Secure Channel earlier (all enabled by default).

Secure Transport was disabled due to being unsupported in the SDK, so I guess those code paths were never triggered. Likewise, darwinssl variant was not used, since MacPorts builds curl with OpenSSL by default (on all systems). Admittedly, I did not scan the codebase, but everything worked fine prior to this.

**Comment by barracuda156** [comment]
@vszakats Thank you!
