### ISSUE TITLE
HTTP3 compilation

### ISSUE THREAD

**Issue by JMC-PK** [curl/curl#5791]
Attempted to compile in HTTP3 support into curl 7.71.1 & the compilation failed.

make gave me the following error. 
vquic/ngtcp2.c: In function ‘ng_flush_egress’:
vquic/ngtcp2.c:1837:29: error: ‘NGTCP2_ERR_WRITE_STREAM_MORE’ undeclared (first use in this function); did you mean ‘NGTCP2_ERR_WRITE_MORE’?
           else if(outlen == NGTCP2_ERR_WRITE_STREAM_MORE) {
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                             NGTCP2_ERR_WRITE_MORE

Note I went to the line listed and replaced NGTCP2_ERR_WRITE_STREAM_MORE with NGTCP2_ERR_WRITE_MORE and it compiled. I'm sure that isn't desired though, but I'm not sure where that needed to be declared, or even if this is a CURL issue or an NGTCP2 issue.

Compiled 
OpenSSL_1_1_1g-quic-draft-29 
nghttp2 (master)
nghttp3 (master)
ngtcp2 (master)

Failing
curl 7.71.1

flags
OPENSSL_PATH=/opt/openssl-quic
CPPFLAGS="-I${OPENSSL_PATH}/ -I${OPENSSL_PATH}/include" LDFLAGS="-L${OPENSSL_PATH}/lib" LIBS="-ldl -lpthread" ./configure --with-nghttp2=/opt/nghttp2 --with-nghttp3=/opt/nghttp3 --with-ngtcp2=/opt/ngtcp2 --enable-alt-svc --with-ssl --enable-versioned-symbols

[curl -V output]
unable to compile.

### operating system
Linux web01 5.6.14-x86_64-linode135 #1 SMP PREEMPT Fri May 22 14:57:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bagder** [comment]
HTTP/3 support is experimental and the HTTP/3 and QUIC libraries curl use are all alpha versions and experimental too. We keep trying to make curl's current code work with the current versions of the h3 libraries. If you want HTTP/3 with curl, you're best off getting the very latest of all components. Or you need to downgrade individual components until you find a match.

Right now, curl's git master builds fine with the latest ngtcp2.

**Comment by JMC-PK** [comment]
Makes total sense! Thanks for the quick follow up!

**Comment by ericcurtin** [comment]
@JMC-PK did you figure out the solution to this issue? I want to build like follows also:

"./configure --with-nghttp3=../nghttp3 --with-ngtcp2=../ngtcp2"

First issue I get is:

configure: error: --with-ngtcp2 was specified but could not find ngtcp2 pkg-config file.

I have nghttp3 ngtcp2 and openssl-quic built

If there was an simple example #!/bin/bash script to help build curl with http3 (including nghttp3, ngtcp2 and openssl-quic) that would be really helpful!

At the moment I'm using a random binary pulled from ymuski/curl-http3 docker image. I'd rather use the latest curl binary from this repo though built with ngtcp2 and nghttp3. I've encountered bugs for example when this curl binary basically gets stuck in http3 mode.

**Comment by ericcurtin** [comment]
Wait my bad it exists:

https://github.com/curl/curl/blob/master/docs/HTTP3.md

Build with openssl steps :)

**Comment by bagder** [comment]
@ericcurtin Several people have successfully built curl-http3 using those, but if you run into any issue there let us know.

Also note that if you build from ngtcp2/nghttp3 master you also need to use curl's master branch.

**Comment by ericcurtin** [comment]
Cool +1 Thanks very much Daniel, I'll post how I built here in case others encounter then

**Comment by ericcurtin** [comment]
@bagder I built exactly like so, works great I use OpenSSL_1_1_1g-quic-draft-29 alternatively because why not?

https://github.com/ericcurtin/staging/blob/master/build-curl-quic.sh

```
#!/bin/bash

set -e

somewhere1="$PWD/../thesis/bin/openssl-quic"
somewhere2="$PWD/../thesis/bin/nghttp3"
somewhere3="$PWD/../thesis/bin/ngtcp2"

rm -rf $somewhere1
rm -rf $somewhere2
rm -rf $somewhere3
mkdir -p $somewhere1
mkdir -p $somewhere2
mkdir -p $somewhere3

nproc=$(nproc)

# Build openssl-quic

cd ..
if [ ! -d "$somewhere1" ]; then
  git clone -b OpenSSL_1_1_1g-quic-draft-29 https://github.com/tatsuhiro-t/openssl $somewhere1
fi

cd openssl-quic
git clean -fdx
git fetch
git reset --hard origin/OpenSSL_1_1_1g-quic-draft-29
./config enable-tls1_3 --prefix=$somewhere1
make -j$nproc
make install_sw

# Build nghttp3

cd ..
if [ ! -d "$somewhere2" ]; then
  git clone https://github.com/ngtcp2/nghttp3
fi

cd nghttp3
git clean -fdx
git fetch
git reset --hard origin/master
autoreconf -i
./configure --prefix=$somewhere2 --enable-lib-only
make -j$nproc
make install

# Build ngtcp2

cd ..
if [ ! -d "$somewhere3" ]; then
  git clone https://github.com/ngtcp2/ngtcp2
fi


cd ngtcp2
git clean -fdx
git fetch
git reset --hard origin/master
autoreconf -i
./configure PKG_CONFIG_PATH=$somewhere1/lib/pkgconfig:$somewhere2/lib/pkgconfig LDFLAGS="-Wl,-rpath,$somewhere1/lib" --prefix=$somewhere3
make -j$nproc
make install

# Build curl

cd ..
if [ ! -d "curl" ]; then
  git clone https://github.com/curl/curl
fi

cd curl
git clean -fdx
git fetch
git reset --hard origin/master
./buildconf
LDFLAGS="-Wl,-rpath,$somewhere1/lib" ./configure --with-ssl=$somewhere1 --with-nghttp3=$somewhere2 --with-ngtcp2=$somewhere3 --enable-alt-svc
make -j$nproc
```
