### PR TITLE
curl: use dynbuf for config file buffer management

### PR DESCRIPTION
**Pull request by bagder**
By making the dynbuf functions available as `curlx_` verisons, the config file parser in the tool code can use that for its buffer management and for saver reallocs etc.

Once landed, we can move more curl functions over to dynbuf,

(Alternative take to #5941 )

### CODE REVIEW

**Comment by bagder** [comment]
It turned out a little too messy. I think I need to take a step back and rethink this.

**Comment by jay** [comment]
Sharing memory allocation functions between the tool and library is tricky. In Windows the tool and library can each be using a separate CRT if libcurl is a DLL and therefore have separate memory handling. Also it would probably be slower to call into the DLL for each dynbuf memory call.

**Comment by bagder** [comment]
Yes, but this isn't meant to share allocation functions. It is meant to share the dynbuf.c code and the allocations done by the tool should be done like normal tool-side allocations. Still a bit tricky to get right in the build systems but I *think* I'm almost there now...

**Comment by jay** [comment]
If the code is built separately for the tool and library and there's naming conflicts and the tool and library can't both use the same function name (I seem to remember that's happened before) then you could change the function name depending on BUILDING_LIBCURL like

#ifdef BUILDING_LIBCURL
#define DYN_FNAME(x) libcurl_ ## x
#else
#define DYN_FNAME(x) x
#endif

void DYN_FNAME(dyn_nappend) (...

**Comment by bagder** [comment]
Ah right, it will be problem in static builds...

**Comment by bagder** [comment]
I opted to plain redefined function names for the tool. I think it looks and feels better.

**Comment by bagder** [comment]
Can anyone figure out why the [visual studio project build fails](https://ci.appveyor.com/project/curlorg/curl/builds/35130023/job/hospcnq14336vdwe#L439)?
~~~
tool_parsecfg.obj : error LNK2019: unresolved external symbol curlx_dyn_init referenced in function parseconfig
tool_parsecfg.obj : error LNK2019: unresolved external symbol curlx_dyn_free referenced in function parseconfig
tool_parsecfg.obj : error LNK2019: unresolved external symbol curlx_dyn_add referenced in function my_get_line
tool_parsecfg.obj : error LNK2019: unresolved external symbol curlx_dyn_reset referenced in function parseconfig
tool_parsecfg.obj : error LNK2019: unresolved external symbol curlx_dyn_ptr referenced in function parseconfig
~~~
Those are supposed to be the symbols dynbuf.c creates when built outside of the lib...

**Comment by bagder** [comment]
This looks fine now and I'll land this (unless someone objects) within a day or two.

File: src/tool_parsecfg.c [hunk 1]
```diff
@@ -335,39 +343,21 @@ static const char *unslashquote(const char *line, char *param)
...
-      line = ptr;
-      strcpy(&line[linelen], buf);
-    }
-    nl = strchr(line, '\n');
+      return FALSE;
+    nl = strchr(buf, '\n');
+    if(curlx_dyn_add(db, buf))
+      /* failure */
+      return FALSE;
   } while(!nl);
```
Comment (jay) [inline src/tool_parsecfg.c:360]:
```suggestion
  } while(!feof(fp) && !strchr(buf, '\n'));
```
Otherwise the last line is ignored if it doesn't end in newline (fgets fails and so getline returns false). And should dyn buf be reset on FALSE condition?

File: src/tool_parsecfg.c [hunk 2]
```diff
@@ -335,39 +343,21 @@ static const char *unslashquote(const char *line, char *param)
...
  */
-static char *my_get_line(FILE *fp)
+static bool my_get_line(FILE *fp, struct curlx_dynbuf *db)
 {
   char buf[4096];
   char *nl = NULL;
-  char *line = NULL;
 
   do {
     if(NULL == fgets(buf, sizeof(buf), fp))
```
Comment (jay) [inline src/tool_parsecfg.c:354]: if(feof(fp))
break;

**Review by jay — CHANGES_REQUESTED** [review]

File: src/tool_parsecfg.c (hunk 1 above)
Comment (bagder) [reply src/tool_parsecfg.c:360]: Oh very good point!

File: src/tool_parsecfg.c [hunk 3]
```diff
@@ -335,39 +343,17 @@ static const char *unslashquote(const char *line, char *param)
...
-      }
-      line = ptr;
-      strcpy(&line[linelen], buf);
-    }
-    nl = strchr(line, '\n');
-  } while(!nl);
+    if(!fgets(buf, sizeof(buf), fp) ||
+       curlx_dyn_add(db, buf))
+      /* failure */
+      return FALSE;
```
Comment (jay) [inline src/tool_parsecfg.c:355]: fgets will return 0 if there are no more characters to be read, so that should not be treated as an error. You could break on feof like I suggested yesterday, which would then cause the function to return true indicating a line has been written, however it occurs to me it's possible fgets has only been called that single time therefore it's possible nothing was added to the buffer.

Comment (bagder) [reply src/tool_parsecfg.c:355]: Yes a zero length file will still return success with nothing written to it, but I think that's fine and expected.

**Comment by bagder** [comment]
Yet another force-push

File: src/tool_parsecfg.c (hunk 3 above)
Comment (jay) [reply src/tool_parsecfg.c:361]: To be clear what I meant is a fgets a single time in the call to my_get_line but fgets could have been called before and is going to return true after the last line if you break. Say you have a file with one character
my_get_line(fp, db) ---> returns true and two bytes have been written, the byte from the file and 0
my_get_line(fp, db) ---> returns true (due to break) and nothing has been written

Comment (bagder) [reply src/tool_parsecfg.c:361]: I don't understand. Are you saying the current incarnation of the function has a problem or not?

File: src/tool_parsecfg.c [hunk 4]
```diff
@@ -335,39 +343,23 @@ static const char *unslashquote(const char *line, char *param)
...
-      if(!ptr) {
-        Curl_safefree(line);
-        return NULL;
-      }
-      line = ptr;
-      strcpy(&line[linelen], buf);
+    /* fgets() returns s on success, and NULL on error or when end of file
+       occurs while no characters have been read. */
+    if(!fgets(buf, sizeof(buf), fp)) {
+      if(feof(fp))
```
Comment (jay) [inline src/tool_parsecfg.c:355]: Here's a way I think we can do it, this way it only returns true on eof if some data was read. This is a slight change in behavior because it won't return true for an empty file anymore.
~~~diff
diff --git a/src/tool_parsecfg.c b/src/tool_parsecfg.c
index 46b4df9..ba22859 100644
--- a/src/tool_parsecfg.c
+++ b/src/tool_parsecfg.c
@@ -348,11 +348,12 @@ static const char *unslashquote(const char *line, char *param)
 static bool my_get_line(FILE *fp, struct curlx_dynbuf *db)
 {
   char buf[4096];
+  size_t oldlen = curlx_dyn_len(db);
   do {
     /* fgets() returns s on success, and NULL on error or when end of file
        occurs while no characters have been read. */
     if(!fgets(buf, sizeof(buf), fp)) {
-      if(feof(fp))
+      if(feof(fp) && oldlen != curlx_dyn_len(db))
         break;
       return FALSE;
     }
~~~
I can't figure out how to span multiple lines using the suggestion feature

**Review by jay — CHANGES_REQUESTED** [review]

File: src/tool_parsecfg.c (hunk 4 above)
Comment (bagder) [reply src/tool_parsecfg.c:355]: Reading an empty file should not cause am error. What case does this addition help with?

Comment (jay) [reply src/tool_parsecfg.c:355]: If we return true on eof when no data has been read then it's just going to loop forever because parsecfg won't know that there are no more lines. Try running it now. We have to be able to signal to parsecfg that the end of the file has been reached and no more lines are available (return false). I disagree with your position on an empty file, as far as I'm concerned it has 0 lines.

before:
printf "foo\n" > curlcfg # two lines
printf "foo" > curlcfg # one line
printf "" > curlcfg # one line

after:
printf "foo\n" > curlcfg # one line
printf "foo" > curlcfg # one line
printf "" > curlcfg # no lines

Comment (bagder) [reply src/tool_parsecfg.c:355]: Ah right. The function returns if the loop should continue or not, so we're back to the simpler:
~~~c
{
  char buf[4096];
  do {
    /* fgets() returns s on success, and NULL on error or when end of file
       occurs while no characters have been read. */
    if(!fgets(buf, sizeof(buf), fp) ||
       curlx_dyn_add(db, buf))
      /* failure */
      return FALSE;
  } while(!strchr(buf, '\n'));

  return TRUE; /* suceess */
}

Comment (bagder) [reply src/tool_parsecfg.c:355]: This matches what the function in current master does.

**Comment by bagder** [comment]
Okay, pushed a new version that makes curl actually return an error back out if it runs into an out of memory.

File: src/tool_parsecfg.c [hunk 5]
```diff
@@ -335,39 +346,22 @@ static const char *unslashquote(const char *line, char *param)
...
-    if(NULL == fgets(buf, sizeof(buf), fp))
-      break;
-    if(!line) {
-      line = strdup(buf);
-      if(!line)
-        return NULL;
+    /* fgets() returns s on success, and NULL on error or when end of file
+       occurs while no characters have been read. */
+    if(!fgets(buf, sizeof(buf), fp))
+      return FALSE; /* stop reading */
```
Comment (jay) [inline src/tool_parsecfg.c:359]: We have to return true if there was data written to the buffer before eof and return false if there was no data written to the buffer before eof, that is why we need the check I suggested. The function in master has similar behavior, it returns NULL if there's no line or a pointer to the line if there's a line, even if feof.

If you want to handle error on data failed to write to the buffer then ideally I think we'd reset the buffer to its previous state and return false. Having a separate `error` just complicates things IMO. (I'm not sure I follow the logic but I just skimmed it so maybe it is right.) Currently there's no way to clip with dyn buffer but I will write a dyn function to do it like std:;string erase, which I think may be useful anyway.

**Review by jay — CHANGES_REQUESTED** [review]

File: src/tool_parsecfg.c (hunk 5 above)
Comment (bagder) [reply src/tool_parsecfg.c:359]: > We have to return true if there was data written to the buffer before eof

No, not if `*_dyn_add()` fails as then it'll be partial.

> The function in master has similar behavior, it returns NULL if there's no line or a pointer to the line if there's a line, even if feof.

This version returns all data until EOF, unless fgets() returns an error prematurely (I'm not sure what kind of condition that could be) or dyn_add fails.

The original version didn't bail out on memory error, otherwise it is a similar behavior.

> If you want to handle error on data failed to write to the buffer then ideally I think we'd reset the buffer to its previous state and return false.

I disagree. If dyn_add fails, it clears the entire buffer, we return error and won't parse any more.

> Having a separate error just complicates things IMO

It makes a memory problem fail the parsing instead of just truncating the parsing.

Comment (jay) [reply src/tool_parsecfg.c:359]: I'm saying this:

printf "a" > file
char buf[2];
fgets(buf, sizeof(buf), fp) <-- returns buf and no eof
loop because no \n
fgets(buf, sizeof(buf), fp) <-- returns NULL and eof

We should not return false in this case, the line is "a". Concerning error if we have only a piece of a line already added and an error occurs before adding the next piece then I would remove what was added since it's incomplete. If you are only having a single line in the buffer at any time then that is not necessary you could just reset it. I've submitted #5958 which will allow truncating a dyn buffer which I think is a good idea to have anyway, in case we need it at some point.

**Comment by bagder** [comment]
> If you are only having a single line in the buffer at any time then that is not necessary you could just reset it.

This logic is doing exactly one line at a time...

**Comment by Jan-E** [comment]
The fix for this seems to break the standard commandline that the PHP devs use: https://github.com/winlibs/cURL/issues/16
