### ISSUE TITLE
build without threaded-resolver but with DoH causes link error

### ISSUE THREAD

**Issue by bagder** [curl/curl#17121]
### I did this

~~~
./configure --disable-threaded-resolver --with-openssl
make -sj
...
  CCLD     curl
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `Curl_async_destroy'
/usr/bin/ld: ../lib/.libs/libcurl.so: undefined reference to `Curl_async_shutdown'
collect2: error: ld returned 1 exit status

~~~

Probably a regression from 56e40ae6a532850b5037ccfb528ed44f09f3d484

### I expected the following

It should be correctly.

### curl/libcurl version

git master 23bed347b38922

### operating system

Linux, but not related
