### PR TITLE
curl-compilers.m4: fix unknown-warning-option on Apple clang

### PR DESCRIPTION
**Pull request by MarcelRaad**
Since 5598b0bd63f690c151074494ce47ef872f004ab4, clang -v is used to
detect the clang version. The version number was expected to come after
the word "version". For Apple clang, this doesn't work as it has its
own versioning scheme.
The version number is now first searched after the string
"based on LLVM". This works for Apple clang before version 7, and also
for e.g. Ubuntu's clang up to version 3.7. If it's not found and the
version string contains "Apple LLVM version", clang version 3.7 is
assumed, which is the version that comes with Xcode 7. Otherwise, the
version number is still expected after the word "version", which works
for very old Apple clang versions.

Note: temporarily changing Apple clang on travis back to debug mode to
get that warning again.

Tested on Ubuntu clang 3.5, 3.7 and 3.8, the first two of which have the "based on LLVM" string in addition to the correct version number. There are no configure warnings and no build warnings.

Ref: https://trac.macports.org/wiki/XcodeVersionInfo
Fixes https://github.com/curl/curl/issues/1606

### CODE REVIEW

**Comment by MarcelRaad** [comment]
Hmm, -Wcomma is still added. I'll have to check again tomorrow.

**Comment by MarcelRaad** [comment]
Works now, it was late yesterday.

The Travis failure is because I temporarily turned on -werror and...
```
tool_sleep.c:54:24: error: implicit conversion loses integer precision: 'long' to '__darwin_suseconds_t' (aka 'int') [-Werror,-Wshorten-64-to-32]
timeout.tv_usec = ms * 1000L;
```

**Comment by MarcelRaad** [comment]
Thanks! The travis failure is now because test 500 fails, probably because of 64ed44a815e4ee158ea1c0a57a714f0d501ad109?
