### ISSUE TITLE
cross-compilation aborts from commit 576e507c78bdd2ec88da442a5354f9dd661b9a8a onward

### ISSUE THREAD

**Issue by hydra3333** [curl/curl#9438]
Hello.

Commit 576e507c78bdd2ec88da442a5354f9dd661b9a8a breaks cross-compilation under Mingw64 in Ubuntu with target Win10x64.
Cross-compiling with the previous commit 70d010d285315e5f1cad6bdb4953e167b069b692 works fine.
Bisected to those 2 commits and then re-tried back and forth to confirm.
Both rely on gnutls 3.7.7.

Logs attached.

Extract from config.log:
```
configure:26439: checking for gnutls_x509_crt_get_dn2 in -lgnutls
configure:26462: x86_64-w64-mingw32-gcc -o conftest.exe -O3 -fstack-protector-all -D_FORTIFY_SOURCE=2 -Werror-implicit-function-declaration -Wno-system-headers -O3 -fstack-protector-all -D_FORTIFY_SOURCE=2 -I/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/include -I/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/include   -O3  -fstack-protector-all  -D_FORTIFY_SOURCE=2   -L/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib -L/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib conftest.c -lgnutls  -lgnutls -lnettle -lhogweed -lgmp -lcrypt32 -lws2_32 -lintl -liconv -lssp -lwldap32 -lz -lws2_32  >&5
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x70): undefined reference to `NCryptFreeObject'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x145): undefined reference to `NCryptSignHash'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x191): undefined reference to `NCryptSignHash'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x467): undefined reference to `NCryptDecrypt'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x4b8): undefined reference to `NCryptDecrypt'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x170a): undefined reference to `NCryptFreeObject'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x1719): undefined reference to `NCryptFreeObject'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x1735): undefined reference to `NCryptOpenStorageProvider'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x188a): undefined reference to `NCryptOpenKey'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x18c6): undefined reference to `NCryptGetProperty'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x1a05): undefined reference to `NCryptFreeObject'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x2858): undefined reference to `NCryptDeleteKey'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x2862): undefined reference to `NCryptFreeObject'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x28c0): undefined reference to `NCryptDeleteKey'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(keys-win.o):keys-win.c:(.text+0x28ca): undefined reference to `NCryptFreeObject'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(sysrng-bcrypt.o):sysrng-bcrypt.:(.text+0x29): undefined reference to `BCryptGenRandom'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(sysrng-bcrypt.o):sysrng-bcrypt.:(.text+0xab): undefined reference to `BCryptOpenAlgorithmProvider'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libgnutls.a(sysrng-bcrypt.o):sysrng-bcrypt.:(.text+0x13d): undefined reference to `BCryptCloseAlgorithmProvider'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libhogweed.a(pkcs1-sec-decrypt.o): in function `_nettle_pkcs1_sec_decrypt':
/home/u/Desktop/_working/workdir/x86_64/nettle-3.8.1/pkcs1-sec-decrypt.c:82: undefined reference to `nettle_cnd_memcpy'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libhogweed.a(pkcs1-sec-decrypt.o): in function `_nettle_pkcs1_sec_decrypt_variable':
/home/u/Desktop/_working/workdir/x86_64/nettle-3.8.1/pkcs1-sec-decrypt.c:135: undefined reference to `nettle_cnd_memcpy'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/x86_64/nettle-3.8.1/pkcs1-sec-decrypt.c:143: undefined reference to `nettle_cnd_memcpy'
/home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld: /home/u/Desktop/_working/workdir/toolchain/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/libhogweed.a(ed448-shake256.o):ed448-shake256:(.rdata+0x28): undefined reference to `nettle_sha3_256_shake'
collect2: error: ld returned 1 exit status
configure:26462: $? = 1
configure: failed program was:

```
### operating system

Linux ubuntu-20 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[2_config.log](https://github.com/curl/curl/files/9495016/2_config.log)
[1_visible_log.txt](https://github.com/curl/curl/files/9495017/1_visible_log.txt)

**Comment by bagder** [comment]
It looks as if the failure to detect GnuTLS is now considered an error, while previously it was just ignored and your build was done without TLS support. You can get that build back by using `--without-ssl` instead of `--with-gnutls`.

Or you fix the gnutls detection to get proper TLS support in the build.

I don't think this change introduced this problem, it just made it apparent.

**Comment by bagder** [comment]
Any further comments or do we conclude that I was right?
