### ISSUE TITLE
GHA/curl-for-win: failing since commit d1fc1c4a854 due to lib/http.c compiler warning

### ISSUE THREAD

**Issue by vszakats** [curl/curl#16412]
### I did this

Seen with GCC 13.0.0 on Windows, unity mode:
```
In file included from /home/runner/work/curl/curl/curl/_x86-win-ucrt-bld/lib/CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c:190:
/home/runner/work/curl/curl/curl/lib/http.c: In function 'Curl_http_input_auth':
/home/runner/work/curl/curl/curl/lib/http.c:1053:11: error: potential null pointer dereference [-Werror=null-dereference]
 1053 |     while(*auth && *auth != ',') /* read up to the next comma */
      |           ^~~~~
```
Ref: https://github.com/curl/curl/actions/runs/13445342926/job/37569288864#step:3:5784

It's probably one of those annoying ones, but it wasn't there before this patch.

### I expected the following

CI passing

### curl/libcurl version

d1fc1c4a854d5cc809cc4ae59a9511900228023a

### operating system

(any?)

**Comment by bagder** [comment]
Unfortunately I can't repro this locally and no CI job seems to do it either so I'm not entirely sure what tweak it needs. Trying #16416 blindly.

**Comment by vszakats** [comment]
> Unfortunately I can't repro this locally and no CI job seems to do it either so I'm not entirely sure what tweak it needs. Trying #16416 blindly.

I'm seeing it a CI job (linked from OP)...I don't understand.
