### PR TITLE
md4: build correctly with openssl without MD4

### LINKED ISSUE #3921: curl 7.65.0 build fails with linker error: undefined reference to `Curl_md4it'
../lib/.libs/libcurl.a(libcurl_la-curl_ntlm_core.o): In function `Curl_ntlm_core_mk_nt_hash':
    curl-7.65.0/lib/curl_ntlm_core.c:579: undefined reference to `Curl_md4it'

Edit: openssl is with build with "no-md4"

### PR DESCRIPTION
**Pull request by bagder**
Reported-by: elsamuko at github
Fixes #3921

### CODE REVIEW

**Comment by jay** [comment]
CI builds stalled at test 892 consistently but that doesn't make any sense to me since the offending commit a9499ff which added test 892 is not an ancestor, therefore there should be no test 892 right? I put a fix in master for the hang but I don't understand how this happened.

**Comment by bagder** [comment]
Me neither, looks crazy... I'll rebase and force-push to get them restarted.
